// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Manages a Cloud Desktops Desktop Group. For more information see [the official documentation](https://yandex.cloud/ru/docs/cloud-desktop/concepts/desktops-and-groups)
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// network to function
//			network, err := yandex.NewVpcNetwork(ctx, "network", nil)
//			if err != nil {
//				return err
//			}
//			subnet, err := yandex.NewVpcSubnet(ctx, "subnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-a"),
//				NetworkId: network.ID().ToIDOutput().ToStringOutput(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.1.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = yandex.GetCloudDesktopsImage(ctx, &yandex.GetCloudDesktopsImageArgs{
//				Name: pulumi.StringRef("Ubuntu 20.04 LTS (2024-12-03)"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			// desktop group
//			_, err = yandex.NewCloudDesktopsDesktopGroup(ctx, "desktopGroup", &yandex.CloudDesktopsDesktopGroupArgs{
//				FolderId:    pulumi.String("<your folder id (optional)>"),
//				ImageId:     pulumi.Any(data.Yandex_cloud_desktops_image.Image.Id),
//				Description: pulumi.String("Sample description"),
//				DesktopTemplate: &yandex.CloudDesktopsDesktopGroupDesktopTemplateArgs{
//					Resources: &yandex.CloudDesktopsDesktopGroupDesktopTemplateResourcesArgs{
//						Cores:        pulumi.Int(4),
//						Memory:       pulumi.Int(8),
//						CoreFraction: pulumi.Int(100),
//					},
//					Boot_disk: map[string]map[string]interface{}{
//						"initializeParams": map[string]interface{}{
//							"size": 24,
//							"type": "SSD",
//						},
//					},
//					Data_disk: map[string]map[string]interface{}{
//						"initializeParams": map[string]interface{}{
//							"size": 16,
//							"type": "HDD",
//						},
//					},
//					Network_interface: map[string]interface{}{
//						"networkId": network.ID(),
//						"subnetIds": pulumi.IDArray{
//							subnet.ID(),
//						},
//					},
//				},
//				GroupConfig: &yandex.CloudDesktopsDesktopGroupGroupConfigArgs{
//					Min_ready_desktops:  1,
//					Max_desktops_amount: 5,
//					Desktop_type:        "PERSISTENT",
//					Members: yandex.CloudDesktopsDesktopGroupGroupConfigMemberArray{
//						&yandex.CloudDesktopsDesktopGroupGroupConfigMemberArgs{
//							Id:   pulumi.String("<your id>"),
//							Type: pulumi.String("userAccount"),
//						},
//					},
//				},
//				Labels: pulumi.StringMap{
//					"label1": pulumi.String("label1-value"),
//					"label2": pulumi.String("label2-value"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `description` (String). The description of the desktop group.
// - `desktopGroupId` (*Read-Only*) (String). The id of the desktop group.
// - `desktopTemplate` [Block]. The configuration template for the desktop group.
//   - `bootDisk` [Block]. The boot disk configuration for each desktop in the group.
//   - `initializeParams` [Block]. General data disk configuration
//   - `size` (Number). The size of disk in gigabytes.
//   - `type` (**Required**)(String). The type of disk. Allowed values: TYPE_UNSPECIFIED, HDD or SDD
//   - `dataDisk` [Block]. The data disk configuration for each desktop in the group.
//   - `initializeParams` [Block]. General data disk configuration
//   - `size` (Number). The size of disk in gigabytes.
//   - `type` (**Required**)(String). The type of disk. Allowed values: TYPE_UNSPECIFIED, HDD or SDD
//   - `networkInterface` [Block]. The base network interface configuration for each desktop in the group.
//   - `networkId` (**Required**)(String). The id of the network desktops from the group would use.
//   - `subnetIds` (List Of String). The ids of the subnet networks desktops from the group would use.
//   - `resources` [Block]. The base resource configuration for each desktop in the group.
//   - `coreFraction` (Number). The baseline level of CPU performance each desktop in this group would have.
//   - `cores` (Number). The number of cores each desktop in this group would have.
//   - `memory` (Number). The number of gigabytes of RAM each desktop in this group would have.
//
// - `folderId` (String). The folder the dekstop group is in.
// - `groupConfig` [Block]. The group configuration.
//   - `desktopType` (String). The type of the desktop group. Allowed: DESKTOP_TYPE_UNSPECIFIED, PERSISTENT, NON_PERSISTENT
//   - `maxDesktopsAmount` (Number). Maximum number of desktops.
//   - `members` [Block]. List of members in this desktop group.
//   - `id` (**Required**)(String). The id of the member. More info in [the official documentation](https://yandex.cloud/ru/docs/cloud-desktop/api-ref/grpc/DesktopGroup/create#yandex.cloud.access.Subject).
//   - `type` (**Required**)(String). The type of the member. More info in [the official documentation](https://yandex.cloud/ru/docs/cloud-desktop/api-ref/grpc/DesktopGroup/create#yandex.cloud.access.Subject).
//   - `minReadyDesktops` (Number). Minimum number of ready desktops.
//
// - `id` (*Read-Only*) (String). The resource identifier.
// - `imageId` (**Required**)(String). The id of the desktop image the group is based on.
// - `labels` (Map Of String). A set of key/value label pairs which assigned to resource.
// - `name` (**Required**)(String). The name of the desktop group.
// - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_cloud_desktops_desktop_group.<resource Name> "name,folderID,desktopImageID"
//
// ```sh
// $ pulumi import yandex:index/cloudDesktopsDesktopGroup:CloudDesktopsDesktopGroup my_desktop_group "group,fd8go**********trjsd,fd8go**********trjsd"
// ```
type CloudDesktopsDesktopGroup struct {
	pulumi.CustomResourceState

	// The description of the desktop group.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// The id of the desktop group.
	DesktopGroupId pulumi.StringOutput `pulumi:"desktopGroupId"`
	// The configuration template for the desktop group.
	DesktopTemplate CloudDesktopsDesktopGroupDesktopTemplatePtrOutput `pulumi:"desktopTemplate"`
	// The folder the dekstop group is in.
	FolderId pulumi.StringOutput `pulumi:"folderId"`
	// The group configuration.
	GroupConfig CloudDesktopsDesktopGroupGroupConfigPtrOutput `pulumi:"groupConfig"`
	// The id of the desktop image the group is based on.
	ImageId pulumi.StringOutput `pulumi:"imageId"`
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// The name of the desktop group.
	Name     pulumi.StringOutput                        `pulumi:"name"`
	Timeouts CloudDesktopsDesktopGroupTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewCloudDesktopsDesktopGroup registers a new resource with the given unique name, arguments, and options.
func NewCloudDesktopsDesktopGroup(ctx *pulumi.Context,
	name string, args *CloudDesktopsDesktopGroupArgs, opts ...pulumi.ResourceOption) (*CloudDesktopsDesktopGroup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ImageId == nil {
		return nil, errors.New("invalid value for required argument 'ImageId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource CloudDesktopsDesktopGroup
	err := ctx.RegisterResource("yandex:index/cloudDesktopsDesktopGroup:CloudDesktopsDesktopGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetCloudDesktopsDesktopGroup gets an existing CloudDesktopsDesktopGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetCloudDesktopsDesktopGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *CloudDesktopsDesktopGroupState, opts ...pulumi.ResourceOption) (*CloudDesktopsDesktopGroup, error) {
	var resource CloudDesktopsDesktopGroup
	err := ctx.ReadResource("yandex:index/cloudDesktopsDesktopGroup:CloudDesktopsDesktopGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering CloudDesktopsDesktopGroup resources.
type cloudDesktopsDesktopGroupState struct {
	// The description of the desktop group.
	Description *string `pulumi:"description"`
	// The id of the desktop group.
	DesktopGroupId *string `pulumi:"desktopGroupId"`
	// The configuration template for the desktop group.
	DesktopTemplate *CloudDesktopsDesktopGroupDesktopTemplate `pulumi:"desktopTemplate"`
	// The folder the dekstop group is in.
	FolderId *string `pulumi:"folderId"`
	// The group configuration.
	GroupConfig *CloudDesktopsDesktopGroupGroupConfig `pulumi:"groupConfig"`
	// The id of the desktop image the group is based on.
	ImageId *string `pulumi:"imageId"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The name of the desktop group.
	Name     *string                            `pulumi:"name"`
	Timeouts *CloudDesktopsDesktopGroupTimeouts `pulumi:"timeouts"`
}

type CloudDesktopsDesktopGroupState struct {
	// The description of the desktop group.
	Description pulumi.StringPtrInput
	// The id of the desktop group.
	DesktopGroupId pulumi.StringPtrInput
	// The configuration template for the desktop group.
	DesktopTemplate CloudDesktopsDesktopGroupDesktopTemplatePtrInput
	// The folder the dekstop group is in.
	FolderId pulumi.StringPtrInput
	// The group configuration.
	GroupConfig CloudDesktopsDesktopGroupGroupConfigPtrInput
	// The id of the desktop image the group is based on.
	ImageId pulumi.StringPtrInput
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput
	// The name of the desktop group.
	Name     pulumi.StringPtrInput
	Timeouts CloudDesktopsDesktopGroupTimeoutsPtrInput
}

func (CloudDesktopsDesktopGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudDesktopsDesktopGroupState)(nil)).Elem()
}

type cloudDesktopsDesktopGroupArgs struct {
	// The description of the desktop group.
	Description *string `pulumi:"description"`
	// The configuration template for the desktop group.
	DesktopTemplate *CloudDesktopsDesktopGroupDesktopTemplate `pulumi:"desktopTemplate"`
	// The folder the dekstop group is in.
	FolderId *string `pulumi:"folderId"`
	// The group configuration.
	GroupConfig *CloudDesktopsDesktopGroupGroupConfig `pulumi:"groupConfig"`
	// The id of the desktop image the group is based on.
	ImageId string `pulumi:"imageId"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// The name of the desktop group.
	Name     *string                            `pulumi:"name"`
	Timeouts *CloudDesktopsDesktopGroupTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a CloudDesktopsDesktopGroup resource.
type CloudDesktopsDesktopGroupArgs struct {
	// The description of the desktop group.
	Description pulumi.StringPtrInput
	// The configuration template for the desktop group.
	DesktopTemplate CloudDesktopsDesktopGroupDesktopTemplatePtrInput
	// The folder the dekstop group is in.
	FolderId pulumi.StringPtrInput
	// The group configuration.
	GroupConfig CloudDesktopsDesktopGroupGroupConfigPtrInput
	// The id of the desktop image the group is based on.
	ImageId pulumi.StringInput
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput
	// The name of the desktop group.
	Name     pulumi.StringPtrInput
	Timeouts CloudDesktopsDesktopGroupTimeoutsPtrInput
}

func (CloudDesktopsDesktopGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*cloudDesktopsDesktopGroupArgs)(nil)).Elem()
}

type CloudDesktopsDesktopGroupInput interface {
	pulumi.Input

	ToCloudDesktopsDesktopGroupOutput() CloudDesktopsDesktopGroupOutput
	ToCloudDesktopsDesktopGroupOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupOutput
}

func (*CloudDesktopsDesktopGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudDesktopsDesktopGroup)(nil)).Elem()
}

func (i *CloudDesktopsDesktopGroup) ToCloudDesktopsDesktopGroupOutput() CloudDesktopsDesktopGroupOutput {
	return i.ToCloudDesktopsDesktopGroupOutputWithContext(context.Background())
}

func (i *CloudDesktopsDesktopGroup) ToCloudDesktopsDesktopGroupOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudDesktopsDesktopGroupOutput)
}

// CloudDesktopsDesktopGroupArrayInput is an input type that accepts CloudDesktopsDesktopGroupArray and CloudDesktopsDesktopGroupArrayOutput values.
// You can construct a concrete instance of `CloudDesktopsDesktopGroupArrayInput` via:
//
//	CloudDesktopsDesktopGroupArray{ CloudDesktopsDesktopGroupArgs{...} }
type CloudDesktopsDesktopGroupArrayInput interface {
	pulumi.Input

	ToCloudDesktopsDesktopGroupArrayOutput() CloudDesktopsDesktopGroupArrayOutput
	ToCloudDesktopsDesktopGroupArrayOutputWithContext(context.Context) CloudDesktopsDesktopGroupArrayOutput
}

type CloudDesktopsDesktopGroupArray []CloudDesktopsDesktopGroupInput

func (CloudDesktopsDesktopGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudDesktopsDesktopGroup)(nil)).Elem()
}

func (i CloudDesktopsDesktopGroupArray) ToCloudDesktopsDesktopGroupArrayOutput() CloudDesktopsDesktopGroupArrayOutput {
	return i.ToCloudDesktopsDesktopGroupArrayOutputWithContext(context.Background())
}

func (i CloudDesktopsDesktopGroupArray) ToCloudDesktopsDesktopGroupArrayOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudDesktopsDesktopGroupArrayOutput)
}

// CloudDesktopsDesktopGroupMapInput is an input type that accepts CloudDesktopsDesktopGroupMap and CloudDesktopsDesktopGroupMapOutput values.
// You can construct a concrete instance of `CloudDesktopsDesktopGroupMapInput` via:
//
//	CloudDesktopsDesktopGroupMap{ "key": CloudDesktopsDesktopGroupArgs{...} }
type CloudDesktopsDesktopGroupMapInput interface {
	pulumi.Input

	ToCloudDesktopsDesktopGroupMapOutput() CloudDesktopsDesktopGroupMapOutput
	ToCloudDesktopsDesktopGroupMapOutputWithContext(context.Context) CloudDesktopsDesktopGroupMapOutput
}

type CloudDesktopsDesktopGroupMap map[string]CloudDesktopsDesktopGroupInput

func (CloudDesktopsDesktopGroupMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudDesktopsDesktopGroup)(nil)).Elem()
}

func (i CloudDesktopsDesktopGroupMap) ToCloudDesktopsDesktopGroupMapOutput() CloudDesktopsDesktopGroupMapOutput {
	return i.ToCloudDesktopsDesktopGroupMapOutputWithContext(context.Background())
}

func (i CloudDesktopsDesktopGroupMap) ToCloudDesktopsDesktopGroupMapOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(CloudDesktopsDesktopGroupMapOutput)
}

type CloudDesktopsDesktopGroupOutput struct{ *pulumi.OutputState }

func (CloudDesktopsDesktopGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**CloudDesktopsDesktopGroup)(nil)).Elem()
}

func (o CloudDesktopsDesktopGroupOutput) ToCloudDesktopsDesktopGroupOutput() CloudDesktopsDesktopGroupOutput {
	return o
}

func (o CloudDesktopsDesktopGroupOutput) ToCloudDesktopsDesktopGroupOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupOutput {
	return o
}

// The description of the desktop group.
func (o CloudDesktopsDesktopGroupOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// The id of the desktop group.
func (o CloudDesktopsDesktopGroupOutput) DesktopGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) pulumi.StringOutput { return v.DesktopGroupId }).(pulumi.StringOutput)
}

// The configuration template for the desktop group.
func (o CloudDesktopsDesktopGroupOutput) DesktopTemplate() CloudDesktopsDesktopGroupDesktopTemplatePtrOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) CloudDesktopsDesktopGroupDesktopTemplatePtrOutput {
		return v.DesktopTemplate
	}).(CloudDesktopsDesktopGroupDesktopTemplatePtrOutput)
}

// The folder the dekstop group is in.
func (o CloudDesktopsDesktopGroupOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// The group configuration.
func (o CloudDesktopsDesktopGroupOutput) GroupConfig() CloudDesktopsDesktopGroupGroupConfigPtrOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) CloudDesktopsDesktopGroupGroupConfigPtrOutput { return v.GroupConfig }).(CloudDesktopsDesktopGroupGroupConfigPtrOutput)
}

// The id of the desktop image the group is based on.
func (o CloudDesktopsDesktopGroupOutput) ImageId() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) pulumi.StringOutput { return v.ImageId }).(pulumi.StringOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o CloudDesktopsDesktopGroupOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// The name of the desktop group.
func (o CloudDesktopsDesktopGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o CloudDesktopsDesktopGroupOutput) Timeouts() CloudDesktopsDesktopGroupTimeoutsPtrOutput {
	return o.ApplyT(func(v *CloudDesktopsDesktopGroup) CloudDesktopsDesktopGroupTimeoutsPtrOutput { return v.Timeouts }).(CloudDesktopsDesktopGroupTimeoutsPtrOutput)
}

type CloudDesktopsDesktopGroupArrayOutput struct{ *pulumi.OutputState }

func (CloudDesktopsDesktopGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*CloudDesktopsDesktopGroup)(nil)).Elem()
}

func (o CloudDesktopsDesktopGroupArrayOutput) ToCloudDesktopsDesktopGroupArrayOutput() CloudDesktopsDesktopGroupArrayOutput {
	return o
}

func (o CloudDesktopsDesktopGroupArrayOutput) ToCloudDesktopsDesktopGroupArrayOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupArrayOutput {
	return o
}

func (o CloudDesktopsDesktopGroupArrayOutput) Index(i pulumi.IntInput) CloudDesktopsDesktopGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *CloudDesktopsDesktopGroup {
		return vs[0].([]*CloudDesktopsDesktopGroup)[vs[1].(int)]
	}).(CloudDesktopsDesktopGroupOutput)
}

type CloudDesktopsDesktopGroupMapOutput struct{ *pulumi.OutputState }

func (CloudDesktopsDesktopGroupMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*CloudDesktopsDesktopGroup)(nil)).Elem()
}

func (o CloudDesktopsDesktopGroupMapOutput) ToCloudDesktopsDesktopGroupMapOutput() CloudDesktopsDesktopGroupMapOutput {
	return o
}

func (o CloudDesktopsDesktopGroupMapOutput) ToCloudDesktopsDesktopGroupMapOutputWithContext(ctx context.Context) CloudDesktopsDesktopGroupMapOutput {
	return o
}

func (o CloudDesktopsDesktopGroupMapOutput) MapIndex(k pulumi.StringInput) CloudDesktopsDesktopGroupOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *CloudDesktopsDesktopGroup {
		return vs[0].(map[string]*CloudDesktopsDesktopGroup)[vs[1].(string)]
	}).(CloudDesktopsDesktopGroupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*CloudDesktopsDesktopGroupInput)(nil)).Elem(), &CloudDesktopsDesktopGroup{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudDesktopsDesktopGroupArrayInput)(nil)).Elem(), CloudDesktopsDesktopGroupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*CloudDesktopsDesktopGroupMapInput)(nil)).Elem(), CloudDesktopsDesktopGroupMap{})
	pulumi.RegisterOutputType(CloudDesktopsDesktopGroupOutput{})
	pulumi.RegisterOutputType(CloudDesktopsDesktopGroupArrayOutput{})
	pulumi.RegisterOutputType(CloudDesktopsDesktopGroupMapOutput{})
}
