// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// A Registry resource. For more information, see the [Registry](https://www.terraform.io/docs/container-registry/concepts/registry) section of the documentation.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new Container Registry.
//			_, err := yandex.NewContainerRegistry(ctx, "default", &yandex.ContainerRegistryArgs{
//				FolderId: pulumi.String("test_folder_id"),
//				Labels: pulumi.StringMap{
//					"my-label": pulumi.String("my-label-value"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
//   - `createdAt` (*Read-Only*) (String). Output only. Creation timestamp in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
//   - `folderId` (String). ID of the folder that the registry belongs to.
//   - `id` (String). ID of the Registry resource to return.
//     To get the registry ID use a [RegistryService.List] request.
//   - `labels` (Map Of String). Resource labels as `key:value` pairs. Maximum of 64 per resource.
//   - `name` (String). Name of the registry.
//   - `registryId` (String). ID of the Registry resource to return.
//     To get the registry ID use a [RegistryService.List] request.
//   - `status` (*Read-Only*) (String). Output only. Status of the registry.
//   - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `read` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_container_registry.<resource Name> <resource Id>
//
// ```sh
// $ pulumi import yandex:index/containerRegistry:ContainerRegistry my_registry crps9**********k9psn
// ```
type ContainerRegistry struct {
	pulumi.CustomResourceState

	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	ContainerRegistryId pulumi.StringOutput `pulumi:"containerRegistryId"`
	// Output only. Creation timestamp in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// ID of the folder that the registry belongs to.
	FolderId pulumi.StringOutput `pulumi:"folderId"`
	// Resource labels as `key:value` pairs. Maximum of 64 per resource.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Name of the registry.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	RegistryId pulumi.StringOutput `pulumi:"registryId"`
	// Output only. Status of the registry.
	Status   pulumi.StringOutput                `pulumi:"status"`
	Timeouts ContainerRegistryTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewContainerRegistry registers a new resource with the given unique name, arguments, and options.
func NewContainerRegistry(ctx *pulumi.Context,
	name string, args *ContainerRegistryArgs, opts ...pulumi.ResourceOption) (*ContainerRegistry, error) {
	if args == nil {
		args = &ContainerRegistryArgs{}
	}

	opts = internal.PkgResourceDefaultOpts(opts)
	var resource ContainerRegistry
	err := ctx.RegisterResource("yandex:index/containerRegistry:ContainerRegistry", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetContainerRegistry gets an existing ContainerRegistry resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetContainerRegistry(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *ContainerRegistryState, opts ...pulumi.ResourceOption) (*ContainerRegistry, error) {
	var resource ContainerRegistry
	err := ctx.ReadResource("yandex:index/containerRegistry:ContainerRegistry", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering ContainerRegistry resources.
type containerRegistryState struct {
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	ContainerRegistryId *string `pulumi:"containerRegistryId"`
	// Output only. Creation timestamp in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
	CreatedAt *string `pulumi:"createdAt"`
	// ID of the folder that the registry belongs to.
	FolderId *string `pulumi:"folderId"`
	// Resource labels as `key:value` pairs. Maximum of 64 per resource.
	Labels map[string]string `pulumi:"labels"`
	// Name of the registry.
	Name *string `pulumi:"name"`
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	RegistryId *string `pulumi:"registryId"`
	// Output only. Status of the registry.
	Status   *string                    `pulumi:"status"`
	Timeouts *ContainerRegistryTimeouts `pulumi:"timeouts"`
}

type ContainerRegistryState struct {
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	ContainerRegistryId pulumi.StringPtrInput
	// Output only. Creation timestamp in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
	CreatedAt pulumi.StringPtrInput
	// ID of the folder that the registry belongs to.
	FolderId pulumi.StringPtrInput
	// Resource labels as `key:value` pairs. Maximum of 64 per resource.
	Labels pulumi.StringMapInput
	// Name of the registry.
	Name pulumi.StringPtrInput
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	RegistryId pulumi.StringPtrInput
	// Output only. Status of the registry.
	Status   pulumi.StringPtrInput
	Timeouts ContainerRegistryTimeoutsPtrInput
}

func (ContainerRegistryState) ElementType() reflect.Type {
	return reflect.TypeOf((*containerRegistryState)(nil)).Elem()
}

type containerRegistryArgs struct {
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	ContainerRegistryId *string `pulumi:"containerRegistryId"`
	// ID of the folder that the registry belongs to.
	FolderId *string `pulumi:"folderId"`
	// Resource labels as `key:value` pairs. Maximum of 64 per resource.
	Labels map[string]string `pulumi:"labels"`
	// Name of the registry.
	Name *string `pulumi:"name"`
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	RegistryId *string                    `pulumi:"registryId"`
	Timeouts   *ContainerRegistryTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a ContainerRegistry resource.
type ContainerRegistryArgs struct {
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	ContainerRegistryId pulumi.StringPtrInput
	// ID of the folder that the registry belongs to.
	FolderId pulumi.StringPtrInput
	// Resource labels as `key:value` pairs. Maximum of 64 per resource.
	Labels pulumi.StringMapInput
	// Name of the registry.
	Name pulumi.StringPtrInput
	// ID of the Registry resource to return.
	//  To get the registry ID use a [RegistryService.List] request.
	RegistryId pulumi.StringPtrInput
	Timeouts   ContainerRegistryTimeoutsPtrInput
}

func (ContainerRegistryArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*containerRegistryArgs)(nil)).Elem()
}

type ContainerRegistryInput interface {
	pulumi.Input

	ToContainerRegistryOutput() ContainerRegistryOutput
	ToContainerRegistryOutputWithContext(ctx context.Context) ContainerRegistryOutput
}

func (*ContainerRegistry) ElementType() reflect.Type {
	return reflect.TypeOf((**ContainerRegistry)(nil)).Elem()
}

func (i *ContainerRegistry) ToContainerRegistryOutput() ContainerRegistryOutput {
	return i.ToContainerRegistryOutputWithContext(context.Background())
}

func (i *ContainerRegistry) ToContainerRegistryOutputWithContext(ctx context.Context) ContainerRegistryOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerRegistryOutput)
}

// ContainerRegistryArrayInput is an input type that accepts ContainerRegistryArray and ContainerRegistryArrayOutput values.
// You can construct a concrete instance of `ContainerRegistryArrayInput` via:
//
//	ContainerRegistryArray{ ContainerRegistryArgs{...} }
type ContainerRegistryArrayInput interface {
	pulumi.Input

	ToContainerRegistryArrayOutput() ContainerRegistryArrayOutput
	ToContainerRegistryArrayOutputWithContext(context.Context) ContainerRegistryArrayOutput
}

type ContainerRegistryArray []ContainerRegistryInput

func (ContainerRegistryArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContainerRegistry)(nil)).Elem()
}

func (i ContainerRegistryArray) ToContainerRegistryArrayOutput() ContainerRegistryArrayOutput {
	return i.ToContainerRegistryArrayOutputWithContext(context.Background())
}

func (i ContainerRegistryArray) ToContainerRegistryArrayOutputWithContext(ctx context.Context) ContainerRegistryArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerRegistryArrayOutput)
}

// ContainerRegistryMapInput is an input type that accepts ContainerRegistryMap and ContainerRegistryMapOutput values.
// You can construct a concrete instance of `ContainerRegistryMapInput` via:
//
//	ContainerRegistryMap{ "key": ContainerRegistryArgs{...} }
type ContainerRegistryMapInput interface {
	pulumi.Input

	ToContainerRegistryMapOutput() ContainerRegistryMapOutput
	ToContainerRegistryMapOutputWithContext(context.Context) ContainerRegistryMapOutput
}

type ContainerRegistryMap map[string]ContainerRegistryInput

func (ContainerRegistryMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContainerRegistry)(nil)).Elem()
}

func (i ContainerRegistryMap) ToContainerRegistryMapOutput() ContainerRegistryMapOutput {
	return i.ToContainerRegistryMapOutputWithContext(context.Background())
}

func (i ContainerRegistryMap) ToContainerRegistryMapOutputWithContext(ctx context.Context) ContainerRegistryMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(ContainerRegistryMapOutput)
}

type ContainerRegistryOutput struct{ *pulumi.OutputState }

func (ContainerRegistryOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**ContainerRegistry)(nil)).Elem()
}

func (o ContainerRegistryOutput) ToContainerRegistryOutput() ContainerRegistryOutput {
	return o
}

func (o ContainerRegistryOutput) ToContainerRegistryOutputWithContext(ctx context.Context) ContainerRegistryOutput {
	return o
}

// ID of the Registry resource to return.
//
//	To get the registry ID use a [RegistryService.List] request.
func (o ContainerRegistryOutput) ContainerRegistryId() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringOutput { return v.ContainerRegistryId }).(pulumi.StringOutput)
}

// Output only. Creation timestamp in [RFC3339](https://www.ietf.org/rfc/rfc3339.txt) text format.
func (o ContainerRegistryOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// ID of the folder that the registry belongs to.
func (o ContainerRegistryOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// Resource labels as `key:value` pairs. Maximum of 64 per resource.
func (o ContainerRegistryOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Name of the registry.
func (o ContainerRegistryOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the Registry resource to return.
//
//	To get the registry ID use a [RegistryService.List] request.
func (o ContainerRegistryOutput) RegistryId() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringOutput { return v.RegistryId }).(pulumi.StringOutput)
}

// Output only. Status of the registry.
func (o ContainerRegistryOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *ContainerRegistry) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o ContainerRegistryOutput) Timeouts() ContainerRegistryTimeoutsPtrOutput {
	return o.ApplyT(func(v *ContainerRegistry) ContainerRegistryTimeoutsPtrOutput { return v.Timeouts }).(ContainerRegistryTimeoutsPtrOutput)
}

type ContainerRegistryArrayOutput struct{ *pulumi.OutputState }

func (ContainerRegistryArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*ContainerRegistry)(nil)).Elem()
}

func (o ContainerRegistryArrayOutput) ToContainerRegistryArrayOutput() ContainerRegistryArrayOutput {
	return o
}

func (o ContainerRegistryArrayOutput) ToContainerRegistryArrayOutputWithContext(ctx context.Context) ContainerRegistryArrayOutput {
	return o
}

func (o ContainerRegistryArrayOutput) Index(i pulumi.IntInput) ContainerRegistryOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *ContainerRegistry {
		return vs[0].([]*ContainerRegistry)[vs[1].(int)]
	}).(ContainerRegistryOutput)
}

type ContainerRegistryMapOutput struct{ *pulumi.OutputState }

func (ContainerRegistryMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*ContainerRegistry)(nil)).Elem()
}

func (o ContainerRegistryMapOutput) ToContainerRegistryMapOutput() ContainerRegistryMapOutput {
	return o
}

func (o ContainerRegistryMapOutput) ToContainerRegistryMapOutputWithContext(ctx context.Context) ContainerRegistryMapOutput {
	return o
}

func (o ContainerRegistryMapOutput) MapIndex(k pulumi.StringInput) ContainerRegistryOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *ContainerRegistry {
		return vs[0].(map[string]*ContainerRegistry)[vs[1].(string)]
	}).(ContainerRegistryOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerRegistryInput)(nil)).Elem(), &ContainerRegistry{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerRegistryArrayInput)(nil)).Elem(), ContainerRegistryArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*ContainerRegistryMapInput)(nil)).Elem(), ContainerRegistryMap{})
	pulumi.RegisterOutputType(ContainerRegistryOutput{})
	pulumi.RegisterOutputType(ContainerRegistryArrayOutput{})
	pulumi.RegisterOutputType(ContainerRegistryMapOutput{})
}
