// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Get information about a Yandex Container Registry IP Permission. For more information, see [the official documentation](https://yandex.cloud/docs/container-registry/operations/registry/registry-access).
//
// > Either `registryId` or `registryName` must be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := yandex.GetContainerRegistryIpPermission(ctx, &yandex.LookupContainerRegistryIpPermissionArgs{
//				RegistryId: pulumi.StringRef(yandex_container_registry.My_registry.Id),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `id` (String).
// - `pull` (*Read-Only*) (Set Of String). List of configured CIDRs, from which `pull` is allowed.
// - `push` (*Read-Only*) (Set Of String). List of configured CIDRs, from which `push` is allowed.
// - `registryId` (String). The ID of the registry that ip restrictions applied to.
// - `registryName` (String). The Name of specific Container Registry.
// - `timeouts` [Block].
//   - `default` (String).
func LookupContainerRegistryIpPermission(ctx *pulumi.Context, args *LookupContainerRegistryIpPermissionArgs, opts ...pulumi.InvokeOption) (*LookupContainerRegistryIpPermissionResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupContainerRegistryIpPermissionResult
	err := ctx.Invoke("yandex:index/getContainerRegistryIpPermission:getContainerRegistryIpPermission", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getContainerRegistryIpPermission.
type LookupContainerRegistryIpPermissionArgs struct {
	RegistryId   *string `pulumi:"registryId"`
	RegistryName *string `pulumi:"registryName"`
}

// A collection of values returned by getContainerRegistryIpPermission.
type LookupContainerRegistryIpPermissionResult struct {
	// The provider-assigned unique ID for this managed resource.
	Id           string   `pulumi:"id"`
	Pulls        []string `pulumi:"pulls"`
	Pushes       []string `pulumi:"pushes"`
	RegistryId   string   `pulumi:"registryId"`
	RegistryName string   `pulumi:"registryName"`
}

func LookupContainerRegistryIpPermissionOutput(ctx *pulumi.Context, args LookupContainerRegistryIpPermissionOutputArgs, opts ...pulumi.InvokeOption) LookupContainerRegistryIpPermissionResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupContainerRegistryIpPermissionResultOutput, error) {
			args := v.(LookupContainerRegistryIpPermissionArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getContainerRegistryIpPermission:getContainerRegistryIpPermission", args, LookupContainerRegistryIpPermissionResultOutput{}, options).(LookupContainerRegistryIpPermissionResultOutput), nil
		}).(LookupContainerRegistryIpPermissionResultOutput)
}

// A collection of arguments for invoking getContainerRegistryIpPermission.
type LookupContainerRegistryIpPermissionOutputArgs struct {
	RegistryId   pulumi.StringPtrInput `pulumi:"registryId"`
	RegistryName pulumi.StringPtrInput `pulumi:"registryName"`
}

func (LookupContainerRegistryIpPermissionOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContainerRegistryIpPermissionArgs)(nil)).Elem()
}

// A collection of values returned by getContainerRegistryIpPermission.
type LookupContainerRegistryIpPermissionResultOutput struct{ *pulumi.OutputState }

func (LookupContainerRegistryIpPermissionResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupContainerRegistryIpPermissionResult)(nil)).Elem()
}

func (o LookupContainerRegistryIpPermissionResultOutput) ToLookupContainerRegistryIpPermissionResultOutput() LookupContainerRegistryIpPermissionResultOutput {
	return o
}

func (o LookupContainerRegistryIpPermissionResultOutput) ToLookupContainerRegistryIpPermissionResultOutputWithContext(ctx context.Context) LookupContainerRegistryIpPermissionResultOutput {
	return o
}

// The provider-assigned unique ID for this managed resource.
func (o LookupContainerRegistryIpPermissionResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerRegistryIpPermissionResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupContainerRegistryIpPermissionResultOutput) Pulls() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupContainerRegistryIpPermissionResult) []string { return v.Pulls }).(pulumi.StringArrayOutput)
}

func (o LookupContainerRegistryIpPermissionResultOutput) Pushes() pulumi.StringArrayOutput {
	return o.ApplyT(func(v LookupContainerRegistryIpPermissionResult) []string { return v.Pushes }).(pulumi.StringArrayOutput)
}

func (o LookupContainerRegistryIpPermissionResultOutput) RegistryId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerRegistryIpPermissionResult) string { return v.RegistryId }).(pulumi.StringOutput)
}

func (o LookupContainerRegistryIpPermissionResultOutput) RegistryName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupContainerRegistryIpPermissionResult) string { return v.RegistryName }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupContainerRegistryIpPermissionResultOutput{})
}
