// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Generates an [IAM](https://yandex.cloud/docs/iam/) role document that may be referenced by and applied to other Yandex Cloud Platform resources, such as the `ResourcemanagerFolder` resource. For more information, see [the official documentation](https://yandex.cloud/docs/iam/concepts/access-control/roles).
//
// This data source is used to define [IAM](https://yandex.cloud/docs/iam/) roles in order to apply them to other resources. Currently, defining a role through a data source and referencing that role from another resource is the only way to apply an IAM role to a resource.
//
// ## Example Usage
//
// ## Arguments & Attributes Reference
//
// - `description` (String).
// - `id` (String).
// - `roleId` (String).
func GetIamRole(ctx *pulumi.Context, args *GetIamRoleArgs, opts ...pulumi.InvokeOption) (*GetIamRoleResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv GetIamRoleResult
	err := ctx.Invoke("yandex:index/getIamRole:getIamRole", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getIamRole.
type GetIamRoleArgs struct {
	Description *string `pulumi:"description"`
	RoleId      *string `pulumi:"roleId"`
}

// A collection of values returned by getIamRole.
type GetIamRoleResult struct {
	Description *string `pulumi:"description"`
	// The provider-assigned unique ID for this managed resource.
	Id     string `pulumi:"id"`
	RoleId string `pulumi:"roleId"`
}

func GetIamRoleOutput(ctx *pulumi.Context, args GetIamRoleOutputArgs, opts ...pulumi.InvokeOption) GetIamRoleResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (GetIamRoleResultOutput, error) {
			args := v.(GetIamRoleArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getIamRole:getIamRole", args, GetIamRoleResultOutput{}, options).(GetIamRoleResultOutput), nil
		}).(GetIamRoleResultOutput)
}

// A collection of arguments for invoking getIamRole.
type GetIamRoleOutputArgs struct {
	Description pulumi.StringPtrInput `pulumi:"description"`
	RoleId      pulumi.StringPtrInput `pulumi:"roleId"`
}

func (GetIamRoleOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamRoleArgs)(nil)).Elem()
}

// A collection of values returned by getIamRole.
type GetIamRoleResultOutput struct{ *pulumi.OutputState }

func (GetIamRoleResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*GetIamRoleResult)(nil)).Elem()
}

func (o GetIamRoleResultOutput) ToGetIamRoleResultOutput() GetIamRoleResultOutput {
	return o
}

func (o GetIamRoleResultOutput) ToGetIamRoleResultOutputWithContext(ctx context.Context) GetIamRoleResultOutput {
	return o
}

func (o GetIamRoleResultOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v GetIamRoleResult) *string { return v.Description }).(pulumi.StringPtrOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o GetIamRoleResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamRoleResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o GetIamRoleResultOutput) RoleId() pulumi.StringOutput {
	return o.ApplyT(func(v GetIamRoleResult) string { return v.RoleId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(GetIamRoleResultOutput{})
}
