// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// A user in the Identity Provider system.
//
//	Users are created within a userpool and can authenticate to access cloud resources.
//	Each user has a unique identifier, credentials, and profile information.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			user, err := yandex.GetOrganizationmanagerIdpUser(ctx, &yandex.LookupOrganizationmanagerIdpUserArgs{
//				UserId: pulumi.StringRef("some_user_id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("myUser.username", user.Username)
//			ctx.Export("myUser.fullName", user.FullName)
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
//   - `companyName` (*Read-Only*) (String). User's company name.
//   - `createdAt` (*Read-Only*) (String). Timestamp when the user was created.
//   - `department` (*Read-Only*) (String). User's department.
//   - `email` (*Read-Only*) (String). User's email address.
//   - `employeeId` (*Read-Only*) (String). User's employee ID
//   - `expiresAt` (*Read-Only*) (String). Timestamp when the user account expires.
//   - `externalId` (*Read-Only*) (String). External identifier for federation with external identity systems.
//     This ID can be used to link this user with an account in an external system.
//   - `familyName` (*Read-Only*) (String). User's last name.
//     Part of the user's profile information.
//   - `fullName` (*Read-Only*) (String). User's full name (display name).
//     This is typically shown in the UI and used for identification purposes.
//   - `givenName` (*Read-Only*) (String). User's first name.
//     Part of the user's profile information.
//   - `id` (String). ID of the user to return.
//   - `jobTitle` (*Read-Only*) (String). User's job title.
//   - `passwordCreatedAt` (*Read-Only*) (String). Timestamp when the user's current password was created.
//     For synchronized passwords, this is the time when the password was last set in the source directory.
//   - `phoneNumber` (*Read-Only*) (String). User's phone number.
//   - `status` (*Read-Only*) (String). Current status of the user.
//     Determines whether the user can authenticate and access the system.
//   - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `read` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `updatedAt` (*Read-Only*) (String). Timestamp when the user was last updated.
//   - `userId` (String). ID of the user to return.
//   - `username` (*Read-Only*) (String). Username used for authentication.
//     Usually in the format of an email address.
//   - `userpoolId` (*Read-Only*) (String). ID of the userpool this user belongs to.
//     To get the userpool ID, make a [UserpoolService.List] request.
func LookupOrganizationmanagerIdpUser(ctx *pulumi.Context, args *LookupOrganizationmanagerIdpUserArgs, opts ...pulumi.InvokeOption) (*LookupOrganizationmanagerIdpUserResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOrganizationmanagerIdpUserResult
	err := ctx.Invoke("yandex:index/getOrganizationmanagerIdpUser:getOrganizationmanagerIdpUser", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationmanagerIdpUser.
type LookupOrganizationmanagerIdpUserArgs struct {
	Id       *string                                `pulumi:"id"`
	Timeouts *GetOrganizationmanagerIdpUserTimeouts `pulumi:"timeouts"`
	UserId   *string                                `pulumi:"userId"`
}

// A collection of values returned by getOrganizationmanagerIdpUser.
type LookupOrganizationmanagerIdpUserResult struct {
	CompanyName       string                                 `pulumi:"companyName"`
	CreatedAt         string                                 `pulumi:"createdAt"`
	Department        string                                 `pulumi:"department"`
	Email             string                                 `pulumi:"email"`
	EmployeeId        string                                 `pulumi:"employeeId"`
	ExpiresAt         string                                 `pulumi:"expiresAt"`
	ExternalId        string                                 `pulumi:"externalId"`
	FamilyName        string                                 `pulumi:"familyName"`
	FullName          string                                 `pulumi:"fullName"`
	GivenName         string                                 `pulumi:"givenName"`
	Id                string                                 `pulumi:"id"`
	JobTitle          string                                 `pulumi:"jobTitle"`
	PasswordCreatedAt string                                 `pulumi:"passwordCreatedAt"`
	PhoneNumber       string                                 `pulumi:"phoneNumber"`
	Status            string                                 `pulumi:"status"`
	Timeouts          *GetOrganizationmanagerIdpUserTimeouts `pulumi:"timeouts"`
	UpdatedAt         string                                 `pulumi:"updatedAt"`
	UserId            string                                 `pulumi:"userId"`
	Username          string                                 `pulumi:"username"`
	UserpoolId        string                                 `pulumi:"userpoolId"`
}

func LookupOrganizationmanagerIdpUserOutput(ctx *pulumi.Context, args LookupOrganizationmanagerIdpUserOutputArgs, opts ...pulumi.InvokeOption) LookupOrganizationmanagerIdpUserResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOrganizationmanagerIdpUserResultOutput, error) {
			args := v.(LookupOrganizationmanagerIdpUserArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getOrganizationmanagerIdpUser:getOrganizationmanagerIdpUser", args, LookupOrganizationmanagerIdpUserResultOutput{}, options).(LookupOrganizationmanagerIdpUserResultOutput), nil
		}).(LookupOrganizationmanagerIdpUserResultOutput)
}

// A collection of arguments for invoking getOrganizationmanagerIdpUser.
type LookupOrganizationmanagerIdpUserOutputArgs struct {
	Id       pulumi.StringPtrInput                         `pulumi:"id"`
	Timeouts GetOrganizationmanagerIdpUserTimeoutsPtrInput `pulumi:"timeouts"`
	UserId   pulumi.StringPtrInput                         `pulumi:"userId"`
}

func (LookupOrganizationmanagerIdpUserOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationmanagerIdpUserArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationmanagerIdpUser.
type LookupOrganizationmanagerIdpUserResultOutput struct{ *pulumi.OutputState }

func (LookupOrganizationmanagerIdpUserResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationmanagerIdpUserResult)(nil)).Elem()
}

func (o LookupOrganizationmanagerIdpUserResultOutput) ToLookupOrganizationmanagerIdpUserResultOutput() LookupOrganizationmanagerIdpUserResultOutput {
	return o
}

func (o LookupOrganizationmanagerIdpUserResultOutput) ToLookupOrganizationmanagerIdpUserResultOutputWithContext(ctx context.Context) LookupOrganizationmanagerIdpUserResultOutput {
	return o
}

func (o LookupOrganizationmanagerIdpUserResultOutput) CompanyName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.CompanyName }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) Department() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.Department }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) Email() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.Email }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) EmployeeId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.EmployeeId }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) ExpiresAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.ExpiresAt }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) ExternalId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.ExternalId }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) FamilyName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.FamilyName }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) FullName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.FullName }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) GivenName() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.GivenName }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) JobTitle() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.JobTitle }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) PasswordCreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.PasswordCreatedAt }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) PhoneNumber() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.PhoneNumber }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.Status }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) Timeouts() GetOrganizationmanagerIdpUserTimeoutsPtrOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) *GetOrganizationmanagerIdpUserTimeouts {
		return v.Timeouts
	}).(GetOrganizationmanagerIdpUserTimeoutsPtrOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.UpdatedAt }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) UserId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.UserId }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) Username() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.Username }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerIdpUserResultOutput) UserpoolId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerIdpUserResult) string { return v.UserpoolId }).(pulumi.StringOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOrganizationmanagerIdpUserResultOutput{})
}
