// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Get information about a Yandex Cloud Organization Manager Group. For more information, see [the official documentation](https://yandex.cloud/docs/organization/manage-groups).
//
// > One of `groupId` or `name` should be specified.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			group, err := yandex.GetOrganizationmanagerGroup(ctx, &yandex.LookupOrganizationmanagerGroupArgs{
//				GroupId:        pulumi.StringRef("some_group_id"),
//				OrganizationId: pulumi.StringRef("some_organization_id"),
//			}, nil)
//			if err != nil {
//				return err
//			}
//			ctx.Export("myGroup.name", group.Name)
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `createdAt` (*Read-Only*) (String). The creation timestamp of the resource.
// - `description` (*Read-Only*) (String). The resource description.
// - `groupId` (String). ID of a Group.
// - `id` (String).
// - `members` (*Read-Only*) (List Of Object). A list of members of the Group.
//   - `id` .
//   - `type` .
//
// - `name` (String). The resource name.
// - `organizationId` (String). Organization that the Group belongs to. If value is omitted, the default provider organization is used.
func LookupOrganizationmanagerGroup(ctx *pulumi.Context, args *LookupOrganizationmanagerGroupArgs, opts ...pulumi.InvokeOption) (*LookupOrganizationmanagerGroupResult, error) {
	opts = internal.PkgInvokeDefaultOpts(opts)
	var rv LookupOrganizationmanagerGroupResult
	err := ctx.Invoke("yandex:index/getOrganizationmanagerGroup:getOrganizationmanagerGroup", args, &rv, opts...)
	if err != nil {
		return nil, err
	}
	return &rv, nil
}

// A collection of arguments for invoking getOrganizationmanagerGroup.
type LookupOrganizationmanagerGroupArgs struct {
	GroupId        *string `pulumi:"groupId"`
	Name           *string `pulumi:"name"`
	OrganizationId *string `pulumi:"organizationId"`
}

// A collection of values returned by getOrganizationmanagerGroup.
type LookupOrganizationmanagerGroupResult struct {
	CreatedAt   string `pulumi:"createdAt"`
	Description string `pulumi:"description"`
	GroupId     string `pulumi:"groupId"`
	// The provider-assigned unique ID for this managed resource.
	Id             string                              `pulumi:"id"`
	Members        []GetOrganizationmanagerGroupMember `pulumi:"members"`
	Name           string                              `pulumi:"name"`
	OrganizationId *string                             `pulumi:"organizationId"`
}

func LookupOrganizationmanagerGroupOutput(ctx *pulumi.Context, args LookupOrganizationmanagerGroupOutputArgs, opts ...pulumi.InvokeOption) LookupOrganizationmanagerGroupResultOutput {
	return pulumi.ToOutputWithContext(ctx.Context(), args).
		ApplyT(func(v interface{}) (LookupOrganizationmanagerGroupResultOutput, error) {
			args := v.(LookupOrganizationmanagerGroupArgs)
			options := pulumi.InvokeOutputOptions{InvokeOptions: internal.PkgInvokeDefaultOpts(opts)}
			return ctx.InvokeOutput("yandex:index/getOrganizationmanagerGroup:getOrganizationmanagerGroup", args, LookupOrganizationmanagerGroupResultOutput{}, options).(LookupOrganizationmanagerGroupResultOutput), nil
		}).(LookupOrganizationmanagerGroupResultOutput)
}

// A collection of arguments for invoking getOrganizationmanagerGroup.
type LookupOrganizationmanagerGroupOutputArgs struct {
	GroupId        pulumi.StringPtrInput `pulumi:"groupId"`
	Name           pulumi.StringPtrInput `pulumi:"name"`
	OrganizationId pulumi.StringPtrInput `pulumi:"organizationId"`
}

func (LookupOrganizationmanagerGroupOutputArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationmanagerGroupArgs)(nil)).Elem()
}

// A collection of values returned by getOrganizationmanagerGroup.
type LookupOrganizationmanagerGroupResultOutput struct{ *pulumi.OutputState }

func (LookupOrganizationmanagerGroupResultOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*LookupOrganizationmanagerGroupResult)(nil)).Elem()
}

func (o LookupOrganizationmanagerGroupResultOutput) ToLookupOrganizationmanagerGroupResultOutput() LookupOrganizationmanagerGroupResultOutput {
	return o
}

func (o LookupOrganizationmanagerGroupResultOutput) ToLookupOrganizationmanagerGroupResultOutputWithContext(ctx context.Context) LookupOrganizationmanagerGroupResultOutput {
	return o
}

func (o LookupOrganizationmanagerGroupResultOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) string { return v.CreatedAt }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerGroupResultOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) string { return v.Description }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerGroupResultOutput) GroupId() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) string { return v.GroupId }).(pulumi.StringOutput)
}

// The provider-assigned unique ID for this managed resource.
func (o LookupOrganizationmanagerGroupResultOutput) Id() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) string { return v.Id }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerGroupResultOutput) Members() GetOrganizationmanagerGroupMemberArrayOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) []GetOrganizationmanagerGroupMember { return v.Members }).(GetOrganizationmanagerGroupMemberArrayOutput)
}

func (o LookupOrganizationmanagerGroupResultOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) string { return v.Name }).(pulumi.StringOutput)
}

func (o LookupOrganizationmanagerGroupResultOutput) OrganizationId() pulumi.StringPtrOutput {
	return o.ApplyT(func(v LookupOrganizationmanagerGroupResult) *string { return v.OrganizationId }).(pulumi.StringPtrOutput)
}

func init() {
	pulumi.RegisterOutputType(LookupOrganizationmanagerGroupResultOutput{})
}
