// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Manages a Greenplum resource group within the Yandex Cloud. For more information, see [the official documentation](https://yandex.cloud/docs/managed-greenplum/).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Auxiliary resources
//			fooVpcNetwork, err := yandex.NewVpcNetwork(ctx, "fooVpcNetwork", nil)
//			if err != nil {
//				return err
//			}
//			myCluster, err := yandex.NewMdbGreenplumCluster(ctx, "myCluster", &yandex.MdbGreenplumClusterArgs{
//				Environment: pulumi.String("PRESTABLE"),
//				NetworkId:   fooVpcNetwork.ID().ToIDOutput().ToStringOutput(),
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new MDB Greenplum database resource group.
//			_, err = yandex.NewMdbGreenplumResourceGroup(ctx, "myResourceGroup", &yandex.MdbGreenplumResourceGroupArgs{
//				ClusterId:     myCluster.ID().ToIDOutput().ToStringOutput(),
//				Password:      "password",
//				ResourceGroup: "default_group",
//			})
//			if err != nil {
//				return err
//			}
//			_, err = yandex.NewVpcSubnet(ctx, "fooVpcSubnet", &yandex.VpcSubnetArgs{
//				Zone:      pulumi.String("ru-central1-d"),
//				NetworkId: fooVpcNetwork.ID().ToIDOutput().ToStringOutput(),
//				V4CidrBlocks: pulumi.StringArray{
//					pulumi.String("10.5.0.0/24"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `clusterId` (**Required**)(String). The ID of the cluster to which resource group belongs to.
// - `concurrency` (Number). The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
// - `cpuRateLimit` (Number). The percentage of CPU resources available to this resource group.
// - `id` (*Read-Only*) (String). The resource identifier.
// - `isUserDefined` (*Read-Only*) (Bool). If false, the resource group is immutable and controlled by yandex
// - `memoryLimit` (Number). The percentage of reserved memory resources available to this resource group.
// - `memorySharedQuota` (Number). The percentage of reserved memory to share across transactions submitted in this resource group.
// - `memorySpillRatio` (Number). The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
// - `name` (**Required**)(String). The name of the resource group.
// - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_mdb_greenplum_resource_group.<resource Name> <resource Id>
//
// ```sh
// $ pulumi import yandex:index/mdbGreenplumResourceGroup:MdbGreenplumResourceGroup my_resource_group ...
// ```
type MdbGreenplumResourceGroup struct {
	pulumi.CustomResourceState

	// The ID of the cluster to which resource group belongs to.
	ClusterId pulumi.StringOutput `pulumi:"clusterId"`
	// The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
	Concurrency pulumi.IntPtrOutput `pulumi:"concurrency"`
	// The percentage of CPU resources available to this resource group.
	CpuRateLimit pulumi.IntPtrOutput `pulumi:"cpuRateLimit"`
	// If false, the resource group is immutable and controlled by yandex
	IsUserDefined pulumi.BoolOutput `pulumi:"isUserDefined"`
	// The percentage of reserved memory resources available to this resource group.
	MemoryLimit pulumi.IntPtrOutput `pulumi:"memoryLimit"`
	// The percentage of reserved memory to share across transactions submitted in this resource group.
	MemorySharedQuota pulumi.IntPtrOutput `pulumi:"memorySharedQuota"`
	// The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
	MemorySpillRatio pulumi.IntPtrOutput `pulumi:"memorySpillRatio"`
	// The name of the resource group.
	Name     pulumi.StringOutput                        `pulumi:"name"`
	Timeouts MdbGreenplumResourceGroupTimeoutsPtrOutput `pulumi:"timeouts"`
}

// NewMdbGreenplumResourceGroup registers a new resource with the given unique name, arguments, and options.
func NewMdbGreenplumResourceGroup(ctx *pulumi.Context,
	name string, args *MdbGreenplumResourceGroupArgs, opts ...pulumi.ResourceOption) (*MdbGreenplumResourceGroup, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterId == nil {
		return nil, errors.New("invalid value for required argument 'ClusterId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MdbGreenplumResourceGroup
	err := ctx.RegisterResource("yandex:index/mdbGreenplumResourceGroup:MdbGreenplumResourceGroup", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMdbGreenplumResourceGroup gets an existing MdbGreenplumResourceGroup resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMdbGreenplumResourceGroup(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MdbGreenplumResourceGroupState, opts ...pulumi.ResourceOption) (*MdbGreenplumResourceGroup, error) {
	var resource MdbGreenplumResourceGroup
	err := ctx.ReadResource("yandex:index/mdbGreenplumResourceGroup:MdbGreenplumResourceGroup", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MdbGreenplumResourceGroup resources.
type mdbGreenplumResourceGroupState struct {
	// The ID of the cluster to which resource group belongs to.
	ClusterId *string `pulumi:"clusterId"`
	// The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
	Concurrency *int `pulumi:"concurrency"`
	// The percentage of CPU resources available to this resource group.
	CpuRateLimit *int `pulumi:"cpuRateLimit"`
	// If false, the resource group is immutable and controlled by yandex
	IsUserDefined *bool `pulumi:"isUserDefined"`
	// The percentage of reserved memory resources available to this resource group.
	MemoryLimit *int `pulumi:"memoryLimit"`
	// The percentage of reserved memory to share across transactions submitted in this resource group.
	MemorySharedQuota *int `pulumi:"memorySharedQuota"`
	// The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
	MemorySpillRatio *int `pulumi:"memorySpillRatio"`
	// The name of the resource group.
	Name     *string                            `pulumi:"name"`
	Timeouts *MdbGreenplumResourceGroupTimeouts `pulumi:"timeouts"`
}

type MdbGreenplumResourceGroupState struct {
	// The ID of the cluster to which resource group belongs to.
	ClusterId pulumi.StringPtrInput
	// The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
	Concurrency pulumi.IntPtrInput
	// The percentage of CPU resources available to this resource group.
	CpuRateLimit pulumi.IntPtrInput
	// If false, the resource group is immutable and controlled by yandex
	IsUserDefined pulumi.BoolPtrInput
	// The percentage of reserved memory resources available to this resource group.
	MemoryLimit pulumi.IntPtrInput
	// The percentage of reserved memory to share across transactions submitted in this resource group.
	MemorySharedQuota pulumi.IntPtrInput
	// The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
	MemorySpillRatio pulumi.IntPtrInput
	// The name of the resource group.
	Name     pulumi.StringPtrInput
	Timeouts MdbGreenplumResourceGroupTimeoutsPtrInput
}

func (MdbGreenplumResourceGroupState) ElementType() reflect.Type {
	return reflect.TypeOf((*mdbGreenplumResourceGroupState)(nil)).Elem()
}

type mdbGreenplumResourceGroupArgs struct {
	// The ID of the cluster to which resource group belongs to.
	ClusterId string `pulumi:"clusterId"`
	// The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
	Concurrency *int `pulumi:"concurrency"`
	// The percentage of CPU resources available to this resource group.
	CpuRateLimit *int `pulumi:"cpuRateLimit"`
	// The percentage of reserved memory resources available to this resource group.
	MemoryLimit *int `pulumi:"memoryLimit"`
	// The percentage of reserved memory to share across transactions submitted in this resource group.
	MemorySharedQuota *int `pulumi:"memorySharedQuota"`
	// The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
	MemorySpillRatio *int `pulumi:"memorySpillRatio"`
	// The name of the resource group.
	Name     *string                            `pulumi:"name"`
	Timeouts *MdbGreenplumResourceGroupTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a MdbGreenplumResourceGroup resource.
type MdbGreenplumResourceGroupArgs struct {
	// The ID of the cluster to which resource group belongs to.
	ClusterId pulumi.StringInput
	// The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
	Concurrency pulumi.IntPtrInput
	// The percentage of CPU resources available to this resource group.
	CpuRateLimit pulumi.IntPtrInput
	// The percentage of reserved memory resources available to this resource group.
	MemoryLimit pulumi.IntPtrInput
	// The percentage of reserved memory to share across transactions submitted in this resource group.
	MemorySharedQuota pulumi.IntPtrInput
	// The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
	MemorySpillRatio pulumi.IntPtrInput
	// The name of the resource group.
	Name     pulumi.StringPtrInput
	Timeouts MdbGreenplumResourceGroupTimeoutsPtrInput
}

func (MdbGreenplumResourceGroupArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mdbGreenplumResourceGroupArgs)(nil)).Elem()
}

type MdbGreenplumResourceGroupInput interface {
	pulumi.Input

	ToMdbGreenplumResourceGroupOutput() MdbGreenplumResourceGroupOutput
	ToMdbGreenplumResourceGroupOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupOutput
}

func (*MdbGreenplumResourceGroup) ElementType() reflect.Type {
	return reflect.TypeOf((**MdbGreenplumResourceGroup)(nil)).Elem()
}

func (i *MdbGreenplumResourceGroup) ToMdbGreenplumResourceGroupOutput() MdbGreenplumResourceGroupOutput {
	return i.ToMdbGreenplumResourceGroupOutputWithContext(context.Background())
}

func (i *MdbGreenplumResourceGroup) ToMdbGreenplumResourceGroupOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbGreenplumResourceGroupOutput)
}

// MdbGreenplumResourceGroupArrayInput is an input type that accepts MdbGreenplumResourceGroupArray and MdbGreenplumResourceGroupArrayOutput values.
// You can construct a concrete instance of `MdbGreenplumResourceGroupArrayInput` via:
//
//	MdbGreenplumResourceGroupArray{ MdbGreenplumResourceGroupArgs{...} }
type MdbGreenplumResourceGroupArrayInput interface {
	pulumi.Input

	ToMdbGreenplumResourceGroupArrayOutput() MdbGreenplumResourceGroupArrayOutput
	ToMdbGreenplumResourceGroupArrayOutputWithContext(context.Context) MdbGreenplumResourceGroupArrayOutput
}

type MdbGreenplumResourceGroupArray []MdbGreenplumResourceGroupInput

func (MdbGreenplumResourceGroupArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MdbGreenplumResourceGroup)(nil)).Elem()
}

func (i MdbGreenplumResourceGroupArray) ToMdbGreenplumResourceGroupArrayOutput() MdbGreenplumResourceGroupArrayOutput {
	return i.ToMdbGreenplumResourceGroupArrayOutputWithContext(context.Background())
}

func (i MdbGreenplumResourceGroupArray) ToMdbGreenplumResourceGroupArrayOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbGreenplumResourceGroupArrayOutput)
}

// MdbGreenplumResourceGroupMapInput is an input type that accepts MdbGreenplumResourceGroupMap and MdbGreenplumResourceGroupMapOutput values.
// You can construct a concrete instance of `MdbGreenplumResourceGroupMapInput` via:
//
//	MdbGreenplumResourceGroupMap{ "key": MdbGreenplumResourceGroupArgs{...} }
type MdbGreenplumResourceGroupMapInput interface {
	pulumi.Input

	ToMdbGreenplumResourceGroupMapOutput() MdbGreenplumResourceGroupMapOutput
	ToMdbGreenplumResourceGroupMapOutputWithContext(context.Context) MdbGreenplumResourceGroupMapOutput
}

type MdbGreenplumResourceGroupMap map[string]MdbGreenplumResourceGroupInput

func (MdbGreenplumResourceGroupMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MdbGreenplumResourceGroup)(nil)).Elem()
}

func (i MdbGreenplumResourceGroupMap) ToMdbGreenplumResourceGroupMapOutput() MdbGreenplumResourceGroupMapOutput {
	return i.ToMdbGreenplumResourceGroupMapOutputWithContext(context.Background())
}

func (i MdbGreenplumResourceGroupMap) ToMdbGreenplumResourceGroupMapOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbGreenplumResourceGroupMapOutput)
}

type MdbGreenplumResourceGroupOutput struct{ *pulumi.OutputState }

func (MdbGreenplumResourceGroupOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MdbGreenplumResourceGroup)(nil)).Elem()
}

func (o MdbGreenplumResourceGroupOutput) ToMdbGreenplumResourceGroupOutput() MdbGreenplumResourceGroupOutput {
	return o
}

func (o MdbGreenplumResourceGroupOutput) ToMdbGreenplumResourceGroupOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupOutput {
	return o
}

// The ID of the cluster to which resource group belongs to.
func (o MdbGreenplumResourceGroupOutput) ClusterId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.StringOutput { return v.ClusterId }).(pulumi.StringOutput)
}

// The maximum number of concurrent transactions, including active and idle transactions, that are permitted in the resource group.
func (o MdbGreenplumResourceGroupOutput) Concurrency() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.IntPtrOutput { return v.Concurrency }).(pulumi.IntPtrOutput)
}

// The percentage of CPU resources available to this resource group.
func (o MdbGreenplumResourceGroupOutput) CpuRateLimit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.IntPtrOutput { return v.CpuRateLimit }).(pulumi.IntPtrOutput)
}

// If false, the resource group is immutable and controlled by yandex
func (o MdbGreenplumResourceGroupOutput) IsUserDefined() pulumi.BoolOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.BoolOutput { return v.IsUserDefined }).(pulumi.BoolOutput)
}

// The percentage of reserved memory resources available to this resource group.
func (o MdbGreenplumResourceGroupOutput) MemoryLimit() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.IntPtrOutput { return v.MemoryLimit }).(pulumi.IntPtrOutput)
}

// The percentage of reserved memory to share across transactions submitted in this resource group.
func (o MdbGreenplumResourceGroupOutput) MemorySharedQuota() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.IntPtrOutput { return v.MemorySharedQuota }).(pulumi.IntPtrOutput)
}

// The memory usage threshold for memory-intensive transactions. When a transaction reaches this threshold, it spills to disk.
func (o MdbGreenplumResourceGroupOutput) MemorySpillRatio() pulumi.IntPtrOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.IntPtrOutput { return v.MemorySpillRatio }).(pulumi.IntPtrOutput)
}

// The name of the resource group.
func (o MdbGreenplumResourceGroupOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

func (o MdbGreenplumResourceGroupOutput) Timeouts() MdbGreenplumResourceGroupTimeoutsPtrOutput {
	return o.ApplyT(func(v *MdbGreenplumResourceGroup) MdbGreenplumResourceGroupTimeoutsPtrOutput { return v.Timeouts }).(MdbGreenplumResourceGroupTimeoutsPtrOutput)
}

type MdbGreenplumResourceGroupArrayOutput struct{ *pulumi.OutputState }

func (MdbGreenplumResourceGroupArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MdbGreenplumResourceGroup)(nil)).Elem()
}

func (o MdbGreenplumResourceGroupArrayOutput) ToMdbGreenplumResourceGroupArrayOutput() MdbGreenplumResourceGroupArrayOutput {
	return o
}

func (o MdbGreenplumResourceGroupArrayOutput) ToMdbGreenplumResourceGroupArrayOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupArrayOutput {
	return o
}

func (o MdbGreenplumResourceGroupArrayOutput) Index(i pulumi.IntInput) MdbGreenplumResourceGroupOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MdbGreenplumResourceGroup {
		return vs[0].([]*MdbGreenplumResourceGroup)[vs[1].(int)]
	}).(MdbGreenplumResourceGroupOutput)
}

type MdbGreenplumResourceGroupMapOutput struct{ *pulumi.OutputState }

func (MdbGreenplumResourceGroupMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MdbGreenplumResourceGroup)(nil)).Elem()
}

func (o MdbGreenplumResourceGroupMapOutput) ToMdbGreenplumResourceGroupMapOutput() MdbGreenplumResourceGroupMapOutput {
	return o
}

func (o MdbGreenplumResourceGroupMapOutput) ToMdbGreenplumResourceGroupMapOutputWithContext(ctx context.Context) MdbGreenplumResourceGroupMapOutput {
	return o
}

func (o MdbGreenplumResourceGroupMapOutput) MapIndex(k pulumi.StringInput) MdbGreenplumResourceGroupOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MdbGreenplumResourceGroup {
		return vs[0].(map[string]*MdbGreenplumResourceGroup)[vs[1].(string)]
	}).(MdbGreenplumResourceGroupOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MdbGreenplumResourceGroupInput)(nil)).Elem(), &MdbGreenplumResourceGroup{})
	pulumi.RegisterInputType(reflect.TypeOf((*MdbGreenplumResourceGroupArrayInput)(nil)).Elem(), MdbGreenplumResourceGroupArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MdbGreenplumResourceGroupMapInput)(nil)).Elem(), MdbGreenplumResourceGroupMap{})
	pulumi.RegisterOutputType(MdbGreenplumResourceGroupOutput{})
	pulumi.RegisterOutputType(MdbGreenplumResourceGroupArrayOutput{})
	pulumi.RegisterOutputType(MdbGreenplumResourceGroupMapOutput{})
}
