// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			_, err := yandex.NewMdbMongodbClusterChangeFreeze(ctx, "example", &yandex.MdbMongodbClusterChangeFreezeArgs{
//				ResourceId: pulumi.Any(yandex_mdb_mongodb_cluster.Example.Id),
//				StartAt:    pulumi.String("2026-12-30T00:00:00Z"),
//				EndAt:      pulumi.String("2027-01-06T00:00:00Z"),
//				Reason:     pulumi.String("New Year holidays"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `changeFreezeId` (String). ID of the change freeze to retrieve.
// - `createdAt` (*Read-Only*) (String). The creation time of the change freeze.
// - `createdBy` (*Read-Only*) (String). The user who created the change freeze.
// - `durationSeconds` (*Read-Only*) (Number). Duration of the change freeze in seconds.
// - `endAt` (**Required**)(String). The time when the change freeze is scheduled to end.
// - `id` (String). ID of the change freeze to retrieve.
// - `reason` (String). Reason for the change freeze.
// - `resourceId` (**Required**)(String). ID of the resource to create a change freeze for.
// - `startAt` (**Required**)(String). The time when the change freeze is scheduled to start.
// - `status` (*Read-Only*) (String). Status of the change freeze.
// - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `read` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//
// - `updatedAt` (*Read-Only*) (String). The time when the change freeze was last updated.
// - `updatedBy` (*Read-Only*) (String). The user who last updated the change freeze.
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_mdb_mongodb_cluster_change_freeze.<resource Name> <resource_id>:<change_freeze_id>
//
// ```sh
// $ pulumi import yandex:index/mdbMongodbClusterChangeFreeze:MdbMongodbClusterChangeFreeze example c9q-resource-id:change-freeze-id
// ```
type MdbMongodbClusterChangeFreeze struct {
	pulumi.CustomResourceState

	// ID of the change freeze to retrieve.
	ChangeFreezeId pulumi.StringOutput `pulumi:"changeFreezeId"`
	// The creation time of the change freeze.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The user who created the change freeze.
	CreatedBy pulumi.StringOutput `pulumi:"createdBy"`
	// Duration of the change freeze in seconds.
	DurationSeconds pulumi.IntOutput `pulumi:"durationSeconds"`
	// The time when the change freeze is scheduled to end.
	EndAt pulumi.StringOutput `pulumi:"endAt"`
	// ID of the change freeze to retrieve.
	MdbMongodbClusterChangeFreezeId pulumi.StringOutput `pulumi:"mdbMongodbClusterChangeFreezeId"`
	// Reason for the change freeze.
	Reason pulumi.StringOutput `pulumi:"reason"`
	// ID of the resource to create a change freeze for.
	ResourceId pulumi.StringOutput `pulumi:"resourceId"`
	// The time when the change freeze is scheduled to start.
	StartAt pulumi.StringOutput `pulumi:"startAt"`
	// Status of the change freeze.
	Status   pulumi.StringOutput                            `pulumi:"status"`
	Timeouts MdbMongodbClusterChangeFreezeTimeoutsPtrOutput `pulumi:"timeouts"`
	// The time when the change freeze was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// The user who last updated the change freeze.
	UpdatedBy pulumi.StringOutput `pulumi:"updatedBy"`
}

// NewMdbMongodbClusterChangeFreeze registers a new resource with the given unique name, arguments, and options.
func NewMdbMongodbClusterChangeFreeze(ctx *pulumi.Context,
	name string, args *MdbMongodbClusterChangeFreezeArgs, opts ...pulumi.ResourceOption) (*MdbMongodbClusterChangeFreeze, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.EndAt == nil {
		return nil, errors.New("invalid value for required argument 'EndAt'")
	}
	if args.ResourceId == nil {
		return nil, errors.New("invalid value for required argument 'ResourceId'")
	}
	if args.StartAt == nil {
		return nil, errors.New("invalid value for required argument 'StartAt'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MdbMongodbClusterChangeFreeze
	err := ctx.RegisterResource("yandex:index/mdbMongodbClusterChangeFreeze:MdbMongodbClusterChangeFreeze", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMdbMongodbClusterChangeFreeze gets an existing MdbMongodbClusterChangeFreeze resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMdbMongodbClusterChangeFreeze(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MdbMongodbClusterChangeFreezeState, opts ...pulumi.ResourceOption) (*MdbMongodbClusterChangeFreeze, error) {
	var resource MdbMongodbClusterChangeFreeze
	err := ctx.ReadResource("yandex:index/mdbMongodbClusterChangeFreeze:MdbMongodbClusterChangeFreeze", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MdbMongodbClusterChangeFreeze resources.
type mdbMongodbClusterChangeFreezeState struct {
	// ID of the change freeze to retrieve.
	ChangeFreezeId *string `pulumi:"changeFreezeId"`
	// The creation time of the change freeze.
	CreatedAt *string `pulumi:"createdAt"`
	// The user who created the change freeze.
	CreatedBy *string `pulumi:"createdBy"`
	// Duration of the change freeze in seconds.
	DurationSeconds *int `pulumi:"durationSeconds"`
	// The time when the change freeze is scheduled to end.
	EndAt *string `pulumi:"endAt"`
	// ID of the change freeze to retrieve.
	MdbMongodbClusterChangeFreezeId *string `pulumi:"mdbMongodbClusterChangeFreezeId"`
	// Reason for the change freeze.
	Reason *string `pulumi:"reason"`
	// ID of the resource to create a change freeze for.
	ResourceId *string `pulumi:"resourceId"`
	// The time when the change freeze is scheduled to start.
	StartAt *string `pulumi:"startAt"`
	// Status of the change freeze.
	Status   *string                                `pulumi:"status"`
	Timeouts *MdbMongodbClusterChangeFreezeTimeouts `pulumi:"timeouts"`
	// The time when the change freeze was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// The user who last updated the change freeze.
	UpdatedBy *string `pulumi:"updatedBy"`
}

type MdbMongodbClusterChangeFreezeState struct {
	// ID of the change freeze to retrieve.
	ChangeFreezeId pulumi.StringPtrInput
	// The creation time of the change freeze.
	CreatedAt pulumi.StringPtrInput
	// The user who created the change freeze.
	CreatedBy pulumi.StringPtrInput
	// Duration of the change freeze in seconds.
	DurationSeconds pulumi.IntPtrInput
	// The time when the change freeze is scheduled to end.
	EndAt pulumi.StringPtrInput
	// ID of the change freeze to retrieve.
	MdbMongodbClusterChangeFreezeId pulumi.StringPtrInput
	// Reason for the change freeze.
	Reason pulumi.StringPtrInput
	// ID of the resource to create a change freeze for.
	ResourceId pulumi.StringPtrInput
	// The time when the change freeze is scheduled to start.
	StartAt pulumi.StringPtrInput
	// Status of the change freeze.
	Status   pulumi.StringPtrInput
	Timeouts MdbMongodbClusterChangeFreezeTimeoutsPtrInput
	// The time when the change freeze was last updated.
	UpdatedAt pulumi.StringPtrInput
	// The user who last updated the change freeze.
	UpdatedBy pulumi.StringPtrInput
}

func (MdbMongodbClusterChangeFreezeState) ElementType() reflect.Type {
	return reflect.TypeOf((*mdbMongodbClusterChangeFreezeState)(nil)).Elem()
}

type mdbMongodbClusterChangeFreezeArgs struct {
	// ID of the change freeze to retrieve.
	ChangeFreezeId *string `pulumi:"changeFreezeId"`
	// The time when the change freeze is scheduled to end.
	EndAt string `pulumi:"endAt"`
	// ID of the change freeze to retrieve.
	MdbMongodbClusterChangeFreezeId *string `pulumi:"mdbMongodbClusterChangeFreezeId"`
	// Reason for the change freeze.
	Reason *string `pulumi:"reason"`
	// ID of the resource to create a change freeze for.
	ResourceId string `pulumi:"resourceId"`
	// The time when the change freeze is scheduled to start.
	StartAt  string                                 `pulumi:"startAt"`
	Timeouts *MdbMongodbClusterChangeFreezeTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a MdbMongodbClusterChangeFreeze resource.
type MdbMongodbClusterChangeFreezeArgs struct {
	// ID of the change freeze to retrieve.
	ChangeFreezeId pulumi.StringPtrInput
	// The time when the change freeze is scheduled to end.
	EndAt pulumi.StringInput
	// ID of the change freeze to retrieve.
	MdbMongodbClusterChangeFreezeId pulumi.StringPtrInput
	// Reason for the change freeze.
	Reason pulumi.StringPtrInput
	// ID of the resource to create a change freeze for.
	ResourceId pulumi.StringInput
	// The time when the change freeze is scheduled to start.
	StartAt  pulumi.StringInput
	Timeouts MdbMongodbClusterChangeFreezeTimeoutsPtrInput
}

func (MdbMongodbClusterChangeFreezeArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*mdbMongodbClusterChangeFreezeArgs)(nil)).Elem()
}

type MdbMongodbClusterChangeFreezeInput interface {
	pulumi.Input

	ToMdbMongodbClusterChangeFreezeOutput() MdbMongodbClusterChangeFreezeOutput
	ToMdbMongodbClusterChangeFreezeOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeOutput
}

func (*MdbMongodbClusterChangeFreeze) ElementType() reflect.Type {
	return reflect.TypeOf((**MdbMongodbClusterChangeFreeze)(nil)).Elem()
}

func (i *MdbMongodbClusterChangeFreeze) ToMdbMongodbClusterChangeFreezeOutput() MdbMongodbClusterChangeFreezeOutput {
	return i.ToMdbMongodbClusterChangeFreezeOutputWithContext(context.Background())
}

func (i *MdbMongodbClusterChangeFreeze) ToMdbMongodbClusterChangeFreezeOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbMongodbClusterChangeFreezeOutput)
}

// MdbMongodbClusterChangeFreezeArrayInput is an input type that accepts MdbMongodbClusterChangeFreezeArray and MdbMongodbClusterChangeFreezeArrayOutput values.
// You can construct a concrete instance of `MdbMongodbClusterChangeFreezeArrayInput` via:
//
//	MdbMongodbClusterChangeFreezeArray{ MdbMongodbClusterChangeFreezeArgs{...} }
type MdbMongodbClusterChangeFreezeArrayInput interface {
	pulumi.Input

	ToMdbMongodbClusterChangeFreezeArrayOutput() MdbMongodbClusterChangeFreezeArrayOutput
	ToMdbMongodbClusterChangeFreezeArrayOutputWithContext(context.Context) MdbMongodbClusterChangeFreezeArrayOutput
}

type MdbMongodbClusterChangeFreezeArray []MdbMongodbClusterChangeFreezeInput

func (MdbMongodbClusterChangeFreezeArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MdbMongodbClusterChangeFreeze)(nil)).Elem()
}

func (i MdbMongodbClusterChangeFreezeArray) ToMdbMongodbClusterChangeFreezeArrayOutput() MdbMongodbClusterChangeFreezeArrayOutput {
	return i.ToMdbMongodbClusterChangeFreezeArrayOutputWithContext(context.Background())
}

func (i MdbMongodbClusterChangeFreezeArray) ToMdbMongodbClusterChangeFreezeArrayOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbMongodbClusterChangeFreezeArrayOutput)
}

// MdbMongodbClusterChangeFreezeMapInput is an input type that accepts MdbMongodbClusterChangeFreezeMap and MdbMongodbClusterChangeFreezeMapOutput values.
// You can construct a concrete instance of `MdbMongodbClusterChangeFreezeMapInput` via:
//
//	MdbMongodbClusterChangeFreezeMap{ "key": MdbMongodbClusterChangeFreezeArgs{...} }
type MdbMongodbClusterChangeFreezeMapInput interface {
	pulumi.Input

	ToMdbMongodbClusterChangeFreezeMapOutput() MdbMongodbClusterChangeFreezeMapOutput
	ToMdbMongodbClusterChangeFreezeMapOutputWithContext(context.Context) MdbMongodbClusterChangeFreezeMapOutput
}

type MdbMongodbClusterChangeFreezeMap map[string]MdbMongodbClusterChangeFreezeInput

func (MdbMongodbClusterChangeFreezeMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MdbMongodbClusterChangeFreeze)(nil)).Elem()
}

func (i MdbMongodbClusterChangeFreezeMap) ToMdbMongodbClusterChangeFreezeMapOutput() MdbMongodbClusterChangeFreezeMapOutput {
	return i.ToMdbMongodbClusterChangeFreezeMapOutputWithContext(context.Background())
}

func (i MdbMongodbClusterChangeFreezeMap) ToMdbMongodbClusterChangeFreezeMapOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MdbMongodbClusterChangeFreezeMapOutput)
}

type MdbMongodbClusterChangeFreezeOutput struct{ *pulumi.OutputState }

func (MdbMongodbClusterChangeFreezeOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MdbMongodbClusterChangeFreeze)(nil)).Elem()
}

func (o MdbMongodbClusterChangeFreezeOutput) ToMdbMongodbClusterChangeFreezeOutput() MdbMongodbClusterChangeFreezeOutput {
	return o
}

func (o MdbMongodbClusterChangeFreezeOutput) ToMdbMongodbClusterChangeFreezeOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeOutput {
	return o
}

// ID of the change freeze to retrieve.
func (o MdbMongodbClusterChangeFreezeOutput) ChangeFreezeId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.ChangeFreezeId }).(pulumi.StringOutput)
}

// The creation time of the change freeze.
func (o MdbMongodbClusterChangeFreezeOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The user who created the change freeze.
func (o MdbMongodbClusterChangeFreezeOutput) CreatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.CreatedBy }).(pulumi.StringOutput)
}

// Duration of the change freeze in seconds.
func (o MdbMongodbClusterChangeFreezeOutput) DurationSeconds() pulumi.IntOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.IntOutput { return v.DurationSeconds }).(pulumi.IntOutput)
}

// The time when the change freeze is scheduled to end.
func (o MdbMongodbClusterChangeFreezeOutput) EndAt() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.EndAt }).(pulumi.StringOutput)
}

// ID of the change freeze to retrieve.
func (o MdbMongodbClusterChangeFreezeOutput) MdbMongodbClusterChangeFreezeId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.MdbMongodbClusterChangeFreezeId }).(pulumi.StringOutput)
}

// Reason for the change freeze.
func (o MdbMongodbClusterChangeFreezeOutput) Reason() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.Reason }).(pulumi.StringOutput)
}

// ID of the resource to create a change freeze for.
func (o MdbMongodbClusterChangeFreezeOutput) ResourceId() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.ResourceId }).(pulumi.StringOutput)
}

// The time when the change freeze is scheduled to start.
func (o MdbMongodbClusterChangeFreezeOutput) StartAt() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.StartAt }).(pulumi.StringOutput)
}

// Status of the change freeze.
func (o MdbMongodbClusterChangeFreezeOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o MdbMongodbClusterChangeFreezeOutput) Timeouts() MdbMongodbClusterChangeFreezeTimeoutsPtrOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) MdbMongodbClusterChangeFreezeTimeoutsPtrOutput {
		return v.Timeouts
	}).(MdbMongodbClusterChangeFreezeTimeoutsPtrOutput)
}

// The time when the change freeze was last updated.
func (o MdbMongodbClusterChangeFreezeOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// The user who last updated the change freeze.
func (o MdbMongodbClusterChangeFreezeOutput) UpdatedBy() pulumi.StringOutput {
	return o.ApplyT(func(v *MdbMongodbClusterChangeFreeze) pulumi.StringOutput { return v.UpdatedBy }).(pulumi.StringOutput)
}

type MdbMongodbClusterChangeFreezeArrayOutput struct{ *pulumi.OutputState }

func (MdbMongodbClusterChangeFreezeArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MdbMongodbClusterChangeFreeze)(nil)).Elem()
}

func (o MdbMongodbClusterChangeFreezeArrayOutput) ToMdbMongodbClusterChangeFreezeArrayOutput() MdbMongodbClusterChangeFreezeArrayOutput {
	return o
}

func (o MdbMongodbClusterChangeFreezeArrayOutput) ToMdbMongodbClusterChangeFreezeArrayOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeArrayOutput {
	return o
}

func (o MdbMongodbClusterChangeFreezeArrayOutput) Index(i pulumi.IntInput) MdbMongodbClusterChangeFreezeOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MdbMongodbClusterChangeFreeze {
		return vs[0].([]*MdbMongodbClusterChangeFreeze)[vs[1].(int)]
	}).(MdbMongodbClusterChangeFreezeOutput)
}

type MdbMongodbClusterChangeFreezeMapOutput struct{ *pulumi.OutputState }

func (MdbMongodbClusterChangeFreezeMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MdbMongodbClusterChangeFreeze)(nil)).Elem()
}

func (o MdbMongodbClusterChangeFreezeMapOutput) ToMdbMongodbClusterChangeFreezeMapOutput() MdbMongodbClusterChangeFreezeMapOutput {
	return o
}

func (o MdbMongodbClusterChangeFreezeMapOutput) ToMdbMongodbClusterChangeFreezeMapOutputWithContext(ctx context.Context) MdbMongodbClusterChangeFreezeMapOutput {
	return o
}

func (o MdbMongodbClusterChangeFreezeMapOutput) MapIndex(k pulumi.StringInput) MdbMongodbClusterChangeFreezeOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MdbMongodbClusterChangeFreeze {
		return vs[0].(map[string]*MdbMongodbClusterChangeFreeze)[vs[1].(string)]
	}).(MdbMongodbClusterChangeFreezeOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MdbMongodbClusterChangeFreezeInput)(nil)).Elem(), &MdbMongodbClusterChangeFreeze{})
	pulumi.RegisterInputType(reflect.TypeOf((*MdbMongodbClusterChangeFreezeArrayInput)(nil)).Elem(), MdbMongodbClusterChangeFreezeArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MdbMongodbClusterChangeFreezeMapInput)(nil)).Elem(), MdbMongodbClusterChangeFreezeMap{})
	pulumi.RegisterOutputType(MdbMongodbClusterChangeFreezeOutput{})
	pulumi.RegisterOutputType(MdbMongodbClusterChangeFreezeArrayOutput{})
	pulumi.RegisterOutputType(MdbMongodbClusterChangeFreezeMapOutput{})
}
