// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Managed Metastore cluster.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new Metastore Cluster.
//			_, err := yandex.NewMetastoreCluster(ctx, "myMetastoreCluster", &yandex.MetastoreClusterArgs{
//				SubnetIds: pulumi.StringArray{
//					yandex_vpc_subnet.A.Id,
//				},
//				SecurityGroupIds: pulumi.StringArray{
//					yandex_vpc_security_group.MetastoreSg.Id,
//				},
//				ServiceAccountId: pulumi.Any(yandex_iam_service_account.ForMetastore.Id),
//				ClusterConfig: &yandex.MetastoreClusterClusterConfigArgs{
//					Resource_preset_id: "c2-m8",
//					Warehouse_config: map[string]map[string]string{
//						"s3": map[string]string{
//							"bucket": "my-metastore-warehouse",
//							"path":   "data/warehouse",
//						},
//					},
//				},
//				Version: pulumi.String("4.2"),
//				MaintenanceWindow: &yandex.MetastoreClusterMaintenanceWindowArgs{
//					Type: pulumi.String("WEEKLY"),
//					Day:  pulumi.String("MON"),
//					Hour: pulumi.Int(12),
//				},
//				Description: pulumi.String("My awesome Metastore"),
//				Logging: &yandex.MetastoreClusterLoggingArgs{
//					Enabled:   pulumi.Bool(true),
//					Folder_id: _var.Folder_id,
//					Min_level: "INFO",
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `clusterConfig` [Block]. Hive Metastore cluster configuration.
//   - `resourcePresetId` (**Required**)(String). The identifier of the preset for computational resources available to an instance (CPU, memory etc.).
//   - `warehouseConfig` [Block]. Warehouse configuration for Hive Metastore. Required for HMS version 4.2+.
//   - `s3` [Block]. S3-compatible storage configuration for warehouse.
//   - `bucket` (**Required**)(String). Name of the S3 bucket used as warehouse storage.
//   - `path` (String). Path prefix within the bucket for warehouse data.
//
// - `createdAt` (*Read-Only*) (String). The creation timestamp of the resource.
// - `deletionProtection` (Bool). The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
// - `description` (String). The resource description.
// - `endpointIp` (*Read-Only*) (String). IP address of Metastore server balancer endpoint.
// - `folderId` (String). The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
// - `id` (*Read-Only*) (String). The resource identifier.
// - `labels` (Map Of String). A set of key/value label pairs which assigned to resource.
// - `logging` [Block]. Cloud Logging configuration.
//   - `enabled` (**Required**)(Bool). Enables delivery of logs generated by Metastore to [Cloud Logging](https://yandex.cloud/docs/logging/).
//   - `folderId` (String). Logs will be written to **default log group** of specified folder. Exactly one of the attributes `folderId` or `logGroupId` should be specified.
//   - `logGroupId` (String). Logs will be written to the **specified log group**. Exactly one of the attributes `folderId` or `logGroupId` should be specified.
//   - `minLevel` (String). Minimum level of messages that will be sent to Cloud Logging. Can be either `TRACE`, `DEBUG`, `INFO`, `WARN`, `ERROR` or `FATAL`. If not set then server default is applied (currently `INFO`).
//
// - `maintenanceWindow` [Block]. Configuration of window for maintenance operations.
//   - `day` (String). Day of week for maintenance window. One of `MON`, `TUE`, `WED`, `THU`, `FRI`, `SAT`, `SUN`.
//   - `hour` (Number). Hour of day in UTC time zone (1-24) for maintenance window.
//   - `type` (String). Type of maintenance window. Can be either `ANYTIME` or `WEEKLY`. If `WEEKLY`, day and hour must be specified.
//
// - `name` (**Required**)(String). The resource name.
// - `networkId` (*Read-Only*) (String). VPC network identifier which resource is attached.
// - `securityGroupIds` (Set Of String). The list of security groups applied to resource or their components.
// - `serviceAccountId` (**Required**)(String). [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
// - `status` (*Read-Only*) (String). Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`.
// - `subnetIds` (**Required**)(Set Of String). The list of VPC subnets identifiers which resource is attached.
// - `version` (String). Metastore server version.
// - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_metastore_cluster.<resource Name> <resource Id>
//
// ```sh
// $ pulumi import yandex:index/metastoreCluster:MetastoreCluster my_metastore_cluster <cluster-id>
// ```
type MetastoreCluster struct {
	pulumi.CustomResourceState

	// Hive Metastore cluster configuration.
	ClusterConfig MetastoreClusterClusterConfigOutput `pulumi:"clusterConfig"`
	// The creation timestamp of the resource.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
	DeletionProtection pulumi.BoolOutput `pulumi:"deletionProtection"`
	// The resource description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// IP address of Metastore server balancer endpoint.
	EndpointIp pulumi.StringOutput `pulumi:"endpointIp"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringOutput `pulumi:"folderId"`
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Cloud Logging configuration.
	Logging MetastoreClusterLoggingPtrOutput `pulumi:"logging"`
	// Configuration of window for maintenance operations.
	MaintenanceWindow MetastoreClusterMaintenanceWindowOutput `pulumi:"maintenanceWindow"`
	// The resource name.
	Name pulumi.StringOutput `pulumi:"name"`
	// VPC network identifier which resource is attached.
	NetworkId pulumi.StringOutput `pulumi:"networkId"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds pulumi.StringArrayOutput `pulumi:"securityGroupIds"`
	// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
	ServiceAccountId pulumi.StringOutput `pulumi:"serviceAccountId"`
	// Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`.
	Status pulumi.StringOutput `pulumi:"status"`
	// The list of VPC subnets identifiers which resource is attached.
	SubnetIds pulumi.StringArrayOutput          `pulumi:"subnetIds"`
	Timeouts  MetastoreClusterTimeoutsPtrOutput `pulumi:"timeouts"`
	// Metastore server version.
	Version pulumi.StringOutput `pulumi:"version"`
}

// NewMetastoreCluster registers a new resource with the given unique name, arguments, and options.
func NewMetastoreCluster(ctx *pulumi.Context,
	name string, args *MetastoreClusterArgs, opts ...pulumi.ResourceOption) (*MetastoreCluster, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.ClusterConfig == nil {
		return nil, errors.New("invalid value for required argument 'ClusterConfig'")
	}
	if args.ServiceAccountId == nil {
		return nil, errors.New("invalid value for required argument 'ServiceAccountId'")
	}
	if args.SubnetIds == nil {
		return nil, errors.New("invalid value for required argument 'SubnetIds'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource MetastoreCluster
	err := ctx.RegisterResource("yandex:index/metastoreCluster:MetastoreCluster", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetMetastoreCluster gets an existing MetastoreCluster resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetMetastoreCluster(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *MetastoreClusterState, opts ...pulumi.ResourceOption) (*MetastoreCluster, error) {
	var resource MetastoreCluster
	err := ctx.ReadResource("yandex:index/metastoreCluster:MetastoreCluster", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering MetastoreCluster resources.
type metastoreClusterState struct {
	// Hive Metastore cluster configuration.
	ClusterConfig *MetastoreClusterClusterConfig `pulumi:"clusterConfig"`
	// The creation timestamp of the resource.
	CreatedAt *string `pulumi:"createdAt"`
	// The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// The resource description.
	Description *string `pulumi:"description"`
	// IP address of Metastore server balancer endpoint.
	EndpointIp *string `pulumi:"endpointIp"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// Cloud Logging configuration.
	Logging *MetastoreClusterLogging `pulumi:"logging"`
	// Configuration of window for maintenance operations.
	MaintenanceWindow *MetastoreClusterMaintenanceWindow `pulumi:"maintenanceWindow"`
	// The resource name.
	Name *string `pulumi:"name"`
	// VPC network identifier which resource is attached.
	NetworkId *string `pulumi:"networkId"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
	ServiceAccountId *string `pulumi:"serviceAccountId"`
	// Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`.
	Status *string `pulumi:"status"`
	// The list of VPC subnets identifiers which resource is attached.
	SubnetIds []string                  `pulumi:"subnetIds"`
	Timeouts  *MetastoreClusterTimeouts `pulumi:"timeouts"`
	// Metastore server version.
	Version *string `pulumi:"version"`
}

type MetastoreClusterState struct {
	// Hive Metastore cluster configuration.
	ClusterConfig MetastoreClusterClusterConfigPtrInput
	// The creation timestamp of the resource.
	CreatedAt pulumi.StringPtrInput
	// The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
	DeletionProtection pulumi.BoolPtrInput
	// The resource description.
	Description pulumi.StringPtrInput
	// IP address of Metastore server balancer endpoint.
	EndpointIp pulumi.StringPtrInput
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput
	// Cloud Logging configuration.
	Logging MetastoreClusterLoggingPtrInput
	// Configuration of window for maintenance operations.
	MaintenanceWindow MetastoreClusterMaintenanceWindowPtrInput
	// The resource name.
	Name pulumi.StringPtrInput
	// VPC network identifier which resource is attached.
	NetworkId pulumi.StringPtrInput
	// The list of security groups applied to resource or their components.
	SecurityGroupIds pulumi.StringArrayInput
	// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
	ServiceAccountId pulumi.StringPtrInput
	// Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`.
	Status pulumi.StringPtrInput
	// The list of VPC subnets identifiers which resource is attached.
	SubnetIds pulumi.StringArrayInput
	Timeouts  MetastoreClusterTimeoutsPtrInput
	// Metastore server version.
	Version pulumi.StringPtrInput
}

func (MetastoreClusterState) ElementType() reflect.Type {
	return reflect.TypeOf((*metastoreClusterState)(nil)).Elem()
}

type metastoreClusterArgs struct {
	// Hive Metastore cluster configuration.
	ClusterConfig MetastoreClusterClusterConfig `pulumi:"clusterConfig"`
	// The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// The resource description.
	Description *string `pulumi:"description"`
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId *string `pulumi:"folderId"`
	// A set of key/value label pairs which assigned to resource.
	Labels map[string]string `pulumi:"labels"`
	// Cloud Logging configuration.
	Logging *MetastoreClusterLogging `pulumi:"logging"`
	// Configuration of window for maintenance operations.
	MaintenanceWindow *MetastoreClusterMaintenanceWindow `pulumi:"maintenanceWindow"`
	// The resource name.
	Name *string `pulumi:"name"`
	// The list of security groups applied to resource or their components.
	SecurityGroupIds []string `pulumi:"securityGroupIds"`
	// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
	ServiceAccountId string `pulumi:"serviceAccountId"`
	// The list of VPC subnets identifiers which resource is attached.
	SubnetIds []string                  `pulumi:"subnetIds"`
	Timeouts  *MetastoreClusterTimeouts `pulumi:"timeouts"`
	// Metastore server version.
	Version *string `pulumi:"version"`
}

// The set of arguments for constructing a MetastoreCluster resource.
type MetastoreClusterArgs struct {
	// Hive Metastore cluster configuration.
	ClusterConfig MetastoreClusterClusterConfigInput
	// The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
	DeletionProtection pulumi.BoolPtrInput
	// The resource description.
	Description pulumi.StringPtrInput
	// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
	FolderId pulumi.StringPtrInput
	// A set of key/value label pairs which assigned to resource.
	Labels pulumi.StringMapInput
	// Cloud Logging configuration.
	Logging MetastoreClusterLoggingPtrInput
	// Configuration of window for maintenance operations.
	MaintenanceWindow MetastoreClusterMaintenanceWindowPtrInput
	// The resource name.
	Name pulumi.StringPtrInput
	// The list of security groups applied to resource or their components.
	SecurityGroupIds pulumi.StringArrayInput
	// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
	ServiceAccountId pulumi.StringInput
	// The list of VPC subnets identifiers which resource is attached.
	SubnetIds pulumi.StringArrayInput
	Timeouts  MetastoreClusterTimeoutsPtrInput
	// Metastore server version.
	Version pulumi.StringPtrInput
}

func (MetastoreClusterArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*metastoreClusterArgs)(nil)).Elem()
}

type MetastoreClusterInput interface {
	pulumi.Input

	ToMetastoreClusterOutput() MetastoreClusterOutput
	ToMetastoreClusterOutputWithContext(ctx context.Context) MetastoreClusterOutput
}

func (*MetastoreCluster) ElementType() reflect.Type {
	return reflect.TypeOf((**MetastoreCluster)(nil)).Elem()
}

func (i *MetastoreCluster) ToMetastoreClusterOutput() MetastoreClusterOutput {
	return i.ToMetastoreClusterOutputWithContext(context.Background())
}

func (i *MetastoreCluster) ToMetastoreClusterOutputWithContext(ctx context.Context) MetastoreClusterOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetastoreClusterOutput)
}

// MetastoreClusterArrayInput is an input type that accepts MetastoreClusterArray and MetastoreClusterArrayOutput values.
// You can construct a concrete instance of `MetastoreClusterArrayInput` via:
//
//	MetastoreClusterArray{ MetastoreClusterArgs{...} }
type MetastoreClusterArrayInput interface {
	pulumi.Input

	ToMetastoreClusterArrayOutput() MetastoreClusterArrayOutput
	ToMetastoreClusterArrayOutputWithContext(context.Context) MetastoreClusterArrayOutput
}

type MetastoreClusterArray []MetastoreClusterInput

func (MetastoreClusterArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MetastoreCluster)(nil)).Elem()
}

func (i MetastoreClusterArray) ToMetastoreClusterArrayOutput() MetastoreClusterArrayOutput {
	return i.ToMetastoreClusterArrayOutputWithContext(context.Background())
}

func (i MetastoreClusterArray) ToMetastoreClusterArrayOutputWithContext(ctx context.Context) MetastoreClusterArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetastoreClusterArrayOutput)
}

// MetastoreClusterMapInput is an input type that accepts MetastoreClusterMap and MetastoreClusterMapOutput values.
// You can construct a concrete instance of `MetastoreClusterMapInput` via:
//
//	MetastoreClusterMap{ "key": MetastoreClusterArgs{...} }
type MetastoreClusterMapInput interface {
	pulumi.Input

	ToMetastoreClusterMapOutput() MetastoreClusterMapOutput
	ToMetastoreClusterMapOutputWithContext(context.Context) MetastoreClusterMapOutput
}

type MetastoreClusterMap map[string]MetastoreClusterInput

func (MetastoreClusterMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MetastoreCluster)(nil)).Elem()
}

func (i MetastoreClusterMap) ToMetastoreClusterMapOutput() MetastoreClusterMapOutput {
	return i.ToMetastoreClusterMapOutputWithContext(context.Background())
}

func (i MetastoreClusterMap) ToMetastoreClusterMapOutputWithContext(ctx context.Context) MetastoreClusterMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(MetastoreClusterMapOutput)
}

type MetastoreClusterOutput struct{ *pulumi.OutputState }

func (MetastoreClusterOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**MetastoreCluster)(nil)).Elem()
}

func (o MetastoreClusterOutput) ToMetastoreClusterOutput() MetastoreClusterOutput {
	return o
}

func (o MetastoreClusterOutput) ToMetastoreClusterOutputWithContext(ctx context.Context) MetastoreClusterOutput {
	return o
}

// Hive Metastore cluster configuration.
func (o MetastoreClusterOutput) ClusterConfig() MetastoreClusterClusterConfigOutput {
	return o.ApplyT(func(v *MetastoreCluster) MetastoreClusterClusterConfigOutput { return v.ClusterConfig }).(MetastoreClusterClusterConfigOutput)
}

// The creation timestamp of the resource.
func (o MetastoreClusterOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// The `true` value means that resource is protected from accidental deletion. By default is set to `false`.
func (o MetastoreClusterOutput) DeletionProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.BoolOutput { return v.DeletionProtection }).(pulumi.BoolOutput)
}

// The resource description.
func (o MetastoreClusterOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// IP address of Metastore server balancer endpoint.
func (o MetastoreClusterOutput) EndpointIp() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.EndpointIp }).(pulumi.StringOutput)
}

// The folder identifier that resource belongs to. If it is not provided, the default provider `folder-id` is used.
func (o MetastoreClusterOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// A set of key/value label pairs which assigned to resource.
func (o MetastoreClusterOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Cloud Logging configuration.
func (o MetastoreClusterOutput) Logging() MetastoreClusterLoggingPtrOutput {
	return o.ApplyT(func(v *MetastoreCluster) MetastoreClusterLoggingPtrOutput { return v.Logging }).(MetastoreClusterLoggingPtrOutput)
}

// Configuration of window for maintenance operations.
func (o MetastoreClusterOutput) MaintenanceWindow() MetastoreClusterMaintenanceWindowOutput {
	return o.ApplyT(func(v *MetastoreCluster) MetastoreClusterMaintenanceWindowOutput { return v.MaintenanceWindow }).(MetastoreClusterMaintenanceWindowOutput)
}

// The resource name.
func (o MetastoreClusterOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// VPC network identifier which resource is attached.
func (o MetastoreClusterOutput) NetworkId() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.NetworkId }).(pulumi.StringOutput)
}

// The list of security groups applied to resource or their components.
func (o MetastoreClusterOutput) SecurityGroupIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringArrayOutput { return v.SecurityGroupIds }).(pulumi.StringArrayOutput)
}

// [Service account](https://yandex.cloud/docs/iam/concepts/users/service-accounts) with role `managed-metastore.integrationProvider`. For more information, see [documentation](https://yandex.cloud/docs/metadata-hub/concepts/metastore-impersonation).
func (o MetastoreClusterOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// Status of the cluster. Can be either `CREATING`, `STARTING`, `RUNNING`, `UPDATING`, `STOPPING`, `STOPPED`, `ERROR` or `STATUS_UNKNOWN`.
func (o MetastoreClusterOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// The list of VPC subnets identifiers which resource is attached.
func (o MetastoreClusterOutput) SubnetIds() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringArrayOutput { return v.SubnetIds }).(pulumi.StringArrayOutput)
}

func (o MetastoreClusterOutput) Timeouts() MetastoreClusterTimeoutsPtrOutput {
	return o.ApplyT(func(v *MetastoreCluster) MetastoreClusterTimeoutsPtrOutput { return v.Timeouts }).(MetastoreClusterTimeoutsPtrOutput)
}

// Metastore server version.
func (o MetastoreClusterOutput) Version() pulumi.StringOutput {
	return o.ApplyT(func(v *MetastoreCluster) pulumi.StringOutput { return v.Version }).(pulumi.StringOutput)
}

type MetastoreClusterArrayOutput struct{ *pulumi.OutputState }

func (MetastoreClusterArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*MetastoreCluster)(nil)).Elem()
}

func (o MetastoreClusterArrayOutput) ToMetastoreClusterArrayOutput() MetastoreClusterArrayOutput {
	return o
}

func (o MetastoreClusterArrayOutput) ToMetastoreClusterArrayOutputWithContext(ctx context.Context) MetastoreClusterArrayOutput {
	return o
}

func (o MetastoreClusterArrayOutput) Index(i pulumi.IntInput) MetastoreClusterOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *MetastoreCluster {
		return vs[0].([]*MetastoreCluster)[vs[1].(int)]
	}).(MetastoreClusterOutput)
}

type MetastoreClusterMapOutput struct{ *pulumi.OutputState }

func (MetastoreClusterMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*MetastoreCluster)(nil)).Elem()
}

func (o MetastoreClusterMapOutput) ToMetastoreClusterMapOutput() MetastoreClusterMapOutput {
	return o
}

func (o MetastoreClusterMapOutput) ToMetastoreClusterMapOutputWithContext(ctx context.Context) MetastoreClusterMapOutput {
	return o
}

func (o MetastoreClusterMapOutput) MapIndex(k pulumi.StringInput) MetastoreClusterOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *MetastoreCluster {
		return vs[0].(map[string]*MetastoreCluster)[vs[1].(string)]
	}).(MetastoreClusterOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*MetastoreClusterInput)(nil)).Elem(), &MetastoreCluster{})
	pulumi.RegisterInputType(reflect.TypeOf((*MetastoreClusterArrayInput)(nil)).Elem(), MetastoreClusterArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*MetastoreClusterMapInput)(nil)).Elem(), MetastoreClusterMap{})
	pulumi.RegisterOutputType(MetastoreClusterOutput{})
	pulumi.RegisterOutputType(MetastoreClusterArrayOutput{})
	pulumi.RegisterOutputType(MetastoreClusterMapOutput{})
}
