// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// A userpool is a container for users in the Identity Provider system.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new OrganizationManager Idp Userpool.
//			_, err := yandex.NewOrganizationmanagerIdpUserpool(ctx, "exampleUserpool", &yandex.OrganizationmanagerIdpUserpoolArgs{
//				DefaultSubdomain: pulumi.String("example-subdomain"),
//				Description:      pulumi.String("Description example"),
//				Labels: pulumi.StringMap{
//					"example-label": pulumi.String("example-label-value"),
//				},
//				OrganizationId: pulumi.String("your_organization_id"),
//				PasswordQualityPolicy: &yandex.OrganizationmanagerIdpUserpoolPasswordQualityPolicyArgs{
//					Allow_similar: true,
//					Fixed: &yandex.OrganizationmanagerIdpUserpoolPasswordQualityPolicyFixedArgs{
//						DigitsRequired: pulumi.Bool(true),
//						LowersRequired: pulumi.Bool(true),
//						MinLength:      pulumi.Int(8),
//						UppersRequired: pulumi.Bool(true),
//					},
//					Match_length: 4,
//					Max_length:   128,
//				},
//				UserSettings: &yandex.OrganizationmanagerIdpUserpoolUserSettingsArgs{
//					Allow_edit_self_login: true,
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `bruteforceProtectionPolicy` [Block]. Bruteforce protection policy for this userpool.
//   - `attempts` (Number). Number of failed attempts allowed within the window before blocking.
//   - `block` (String). Duration of the block after too many failed attempts.
//   - `window` (String). Time window for counting failed authentication attempts.
//   - `createdAt` (*Read-Only*) (String). Timestamp when the userpool was created.
//   - `defaultSubdomain` (**Required**)(String). Default subdomain for the userpool.
//   - `description` (String). Description of the userpool.
//   - `domains` (*Read-Only*) (List Of String). List of domains associated with this userpool.
//   - `id` (String). ID of the userpool to return.
//     To get the userpool ID, make a [UserpoolService.List] request.
//   - `labels` (Map Of String). Resource labels as key:value pairs.
//   - `name` (**Required**)(String). Name of the userpool.
//   - `organizationId` (**Required**)(String). ID of the organization this userpool belongs to.
//   - `passwordBlacklistPolicy` [Block]. Password blacklist policy for this userpool.
//   - `checkCommon` (Bool). Whether check in common password database is enabled. Default value is true.
//   - `passwordLifetimePolicy` [Block]. Password lifetime policy for this userpool.
//   - `maxDaysCount` (Number). Maximum number of days a password remains valid.
//     Zero means passwords never expire.
//   - `minDaysCount` (Number). Minimum number of days before a password can be changed.
//   - `passwordQualityPolicy` [Block]. Password quality policy for this userpool.
//   - `allowSimilar` (Bool). Whether passwords similar to previous ones are allowed.
//   - `fixed` [Block]. Fixed complexity requirements. Exactly one of complexity requirements must be specified.
//   - `digitsRequired` (Bool). Whether digits are required in the password.
//   - `lowersRequired` (Bool). Whether lowercase letters are required in the password.
//   - `minLength` (Number). Minimum length required for all passwords.
//   - `specialsRequired` (Bool). Whether special characters are required in the password.
//   - `uppersRequired` (Bool). Whether uppercase letters are required in the password.
//   - `matchLength` (Number). Minimum length of substrings to check for similarity to vulnerable sequences.
//   - `maxLength` (Number). Maximum password length. Zero means no maximum length is enforced.
//   - `smart` [Block]. Smart complexity requirements. Exactly one of complexity requirements must be specified.
//   - `fourClasses` (Number). For passwords with all four classes of characters
//   - `oneClass` (Number). For passwords with one class of characters
//   - `threeClasses` (Number). For passwords with three classes of characters
//   - `twoClasses` (Number). For passwords with two classes of characters
//   - `status` (*Read-Only*) (String). Current status of the userpool.
//   - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `read` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `updatedAt` (*Read-Only*) (String). Timestamp when the userpool was last updated.
//   - `userSettings` [Block]. User settings for this userpool.
//   - `allowEditSelfContacts` (Bool). Whether users can edit their own contact information.
//   - `allowEditSelfInfo` (Bool). Whether users can edit their own profile information.
//   - `allowEditSelfLogin` (Bool). Whether users can edit their own login information.
//   - `allowEditSelfPassword` (Bool). Whether users can change their own passwords.
//   - `userpoolId` (String). ID of the userpool to return.
//     To get the userpool ID, make a [UserpoolService.List] request.
type OrganizationmanagerIdpUserpool struct {
	pulumi.CustomResourceState

	// Bruteforce protection policy for this userpool.
	BruteforceProtectionPolicy OrganizationmanagerIdpUserpoolBruteforceProtectionPolicyOutput `pulumi:"bruteforceProtectionPolicy"`
	// Timestamp when the userpool was created.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// Default subdomain for the userpool.
	DefaultSubdomain pulumi.StringOutput `pulumi:"defaultSubdomain"`
	// Description of the userpool.
	Description pulumi.StringOutput `pulumi:"description"`
	// List of domains associated with this userpool.
	Domains pulumi.StringArrayOutput `pulumi:"domains"`
	// Resource labels as key:value pairs.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// Name of the userpool.
	Name pulumi.StringOutput `pulumi:"name"`
	// ID of the organization this userpool belongs to.
	OrganizationId pulumi.StringOutput `pulumi:"organizationId"`
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	OrganizationmanagerIdpUserpoolId pulumi.StringOutput `pulumi:"organizationmanagerIdpUserpoolId"`
	// Password blacklist policy for this userpool.
	PasswordBlacklistPolicy OrganizationmanagerIdpUserpoolPasswordBlacklistPolicyOutput `pulumi:"passwordBlacklistPolicy"`
	// Password lifetime policy for this userpool.
	PasswordLifetimePolicy OrganizationmanagerIdpUserpoolPasswordLifetimePolicyOutput `pulumi:"passwordLifetimePolicy"`
	// Password quality policy for this userpool.
	PasswordQualityPolicy OrganizationmanagerIdpUserpoolPasswordQualityPolicyOutput `pulumi:"passwordQualityPolicy"`
	// Current status of the userpool.
	Status   pulumi.StringOutput                             `pulumi:"status"`
	Timeouts OrganizationmanagerIdpUserpoolTimeoutsPtrOutput `pulumi:"timeouts"`
	// Timestamp when the userpool was last updated.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
	// User settings for this userpool.
	UserSettings OrganizationmanagerIdpUserpoolUserSettingsOutput `pulumi:"userSettings"`
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	UserpoolId pulumi.StringOutput `pulumi:"userpoolId"`
}

// NewOrganizationmanagerIdpUserpool registers a new resource with the given unique name, arguments, and options.
func NewOrganizationmanagerIdpUserpool(ctx *pulumi.Context,
	name string, args *OrganizationmanagerIdpUserpoolArgs, opts ...pulumi.ResourceOption) (*OrganizationmanagerIdpUserpool, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DefaultSubdomain == nil {
		return nil, errors.New("invalid value for required argument 'DefaultSubdomain'")
	}
	if args.OrganizationId == nil {
		return nil, errors.New("invalid value for required argument 'OrganizationId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OrganizationmanagerIdpUserpool
	err := ctx.RegisterResource("yandex:index/organizationmanagerIdpUserpool:OrganizationmanagerIdpUserpool", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganizationmanagerIdpUserpool gets an existing OrganizationmanagerIdpUserpool resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganizationmanagerIdpUserpool(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationmanagerIdpUserpoolState, opts ...pulumi.ResourceOption) (*OrganizationmanagerIdpUserpool, error) {
	var resource OrganizationmanagerIdpUserpool
	err := ctx.ReadResource("yandex:index/organizationmanagerIdpUserpool:OrganizationmanagerIdpUserpool", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrganizationmanagerIdpUserpool resources.
type organizationmanagerIdpUserpoolState struct {
	// Bruteforce protection policy for this userpool.
	BruteforceProtectionPolicy *OrganizationmanagerIdpUserpoolBruteforceProtectionPolicy `pulumi:"bruteforceProtectionPolicy"`
	// Timestamp when the userpool was created.
	CreatedAt *string `pulumi:"createdAt"`
	// Default subdomain for the userpool.
	DefaultSubdomain *string `pulumi:"defaultSubdomain"`
	// Description of the userpool.
	Description *string `pulumi:"description"`
	// List of domains associated with this userpool.
	Domains []string `pulumi:"domains"`
	// Resource labels as key:value pairs.
	Labels map[string]string `pulumi:"labels"`
	// Name of the userpool.
	Name *string `pulumi:"name"`
	// ID of the organization this userpool belongs to.
	OrganizationId *string `pulumi:"organizationId"`
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	OrganizationmanagerIdpUserpoolId *string `pulumi:"organizationmanagerIdpUserpoolId"`
	// Password blacklist policy for this userpool.
	PasswordBlacklistPolicy *OrganizationmanagerIdpUserpoolPasswordBlacklistPolicy `pulumi:"passwordBlacklistPolicy"`
	// Password lifetime policy for this userpool.
	PasswordLifetimePolicy *OrganizationmanagerIdpUserpoolPasswordLifetimePolicy `pulumi:"passwordLifetimePolicy"`
	// Password quality policy for this userpool.
	PasswordQualityPolicy *OrganizationmanagerIdpUserpoolPasswordQualityPolicy `pulumi:"passwordQualityPolicy"`
	// Current status of the userpool.
	Status   *string                                 `pulumi:"status"`
	Timeouts *OrganizationmanagerIdpUserpoolTimeouts `pulumi:"timeouts"`
	// Timestamp when the userpool was last updated.
	UpdatedAt *string `pulumi:"updatedAt"`
	// User settings for this userpool.
	UserSettings *OrganizationmanagerIdpUserpoolUserSettings `pulumi:"userSettings"`
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	UserpoolId *string `pulumi:"userpoolId"`
}

type OrganizationmanagerIdpUserpoolState struct {
	// Bruteforce protection policy for this userpool.
	BruteforceProtectionPolicy OrganizationmanagerIdpUserpoolBruteforceProtectionPolicyPtrInput
	// Timestamp when the userpool was created.
	CreatedAt pulumi.StringPtrInput
	// Default subdomain for the userpool.
	DefaultSubdomain pulumi.StringPtrInput
	// Description of the userpool.
	Description pulumi.StringPtrInput
	// List of domains associated with this userpool.
	Domains pulumi.StringArrayInput
	// Resource labels as key:value pairs.
	Labels pulumi.StringMapInput
	// Name of the userpool.
	Name pulumi.StringPtrInput
	// ID of the organization this userpool belongs to.
	OrganizationId pulumi.StringPtrInput
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	OrganizationmanagerIdpUserpoolId pulumi.StringPtrInput
	// Password blacklist policy for this userpool.
	PasswordBlacklistPolicy OrganizationmanagerIdpUserpoolPasswordBlacklistPolicyPtrInput
	// Password lifetime policy for this userpool.
	PasswordLifetimePolicy OrganizationmanagerIdpUserpoolPasswordLifetimePolicyPtrInput
	// Password quality policy for this userpool.
	PasswordQualityPolicy OrganizationmanagerIdpUserpoolPasswordQualityPolicyPtrInput
	// Current status of the userpool.
	Status   pulumi.StringPtrInput
	Timeouts OrganizationmanagerIdpUserpoolTimeoutsPtrInput
	// Timestamp when the userpool was last updated.
	UpdatedAt pulumi.StringPtrInput
	// User settings for this userpool.
	UserSettings OrganizationmanagerIdpUserpoolUserSettingsPtrInput
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	UserpoolId pulumi.StringPtrInput
}

func (OrganizationmanagerIdpUserpoolState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationmanagerIdpUserpoolState)(nil)).Elem()
}

type organizationmanagerIdpUserpoolArgs struct {
	// Bruteforce protection policy for this userpool.
	BruteforceProtectionPolicy *OrganizationmanagerIdpUserpoolBruteforceProtectionPolicy `pulumi:"bruteforceProtectionPolicy"`
	// Default subdomain for the userpool.
	DefaultSubdomain string `pulumi:"defaultSubdomain"`
	// Description of the userpool.
	Description *string `pulumi:"description"`
	// Resource labels as key:value pairs.
	Labels map[string]string `pulumi:"labels"`
	// Name of the userpool.
	Name *string `pulumi:"name"`
	// ID of the organization this userpool belongs to.
	OrganizationId string `pulumi:"organizationId"`
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	OrganizationmanagerIdpUserpoolId *string `pulumi:"organizationmanagerIdpUserpoolId"`
	// Password blacklist policy for this userpool.
	PasswordBlacklistPolicy *OrganizationmanagerIdpUserpoolPasswordBlacklistPolicy `pulumi:"passwordBlacklistPolicy"`
	// Password lifetime policy for this userpool.
	PasswordLifetimePolicy *OrganizationmanagerIdpUserpoolPasswordLifetimePolicy `pulumi:"passwordLifetimePolicy"`
	// Password quality policy for this userpool.
	PasswordQualityPolicy *OrganizationmanagerIdpUserpoolPasswordQualityPolicy `pulumi:"passwordQualityPolicy"`
	Timeouts              *OrganizationmanagerIdpUserpoolTimeouts              `pulumi:"timeouts"`
	// User settings for this userpool.
	UserSettings *OrganizationmanagerIdpUserpoolUserSettings `pulumi:"userSettings"`
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	UserpoolId *string `pulumi:"userpoolId"`
}

// The set of arguments for constructing a OrganizationmanagerIdpUserpool resource.
type OrganizationmanagerIdpUserpoolArgs struct {
	// Bruteforce protection policy for this userpool.
	BruteforceProtectionPolicy OrganizationmanagerIdpUserpoolBruteforceProtectionPolicyPtrInput
	// Default subdomain for the userpool.
	DefaultSubdomain pulumi.StringInput
	// Description of the userpool.
	Description pulumi.StringPtrInput
	// Resource labels as key:value pairs.
	Labels pulumi.StringMapInput
	// Name of the userpool.
	Name pulumi.StringPtrInput
	// ID of the organization this userpool belongs to.
	OrganizationId pulumi.StringInput
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	OrganizationmanagerIdpUserpoolId pulumi.StringPtrInput
	// Password blacklist policy for this userpool.
	PasswordBlacklistPolicy OrganizationmanagerIdpUserpoolPasswordBlacklistPolicyPtrInput
	// Password lifetime policy for this userpool.
	PasswordLifetimePolicy OrganizationmanagerIdpUserpoolPasswordLifetimePolicyPtrInput
	// Password quality policy for this userpool.
	PasswordQualityPolicy OrganizationmanagerIdpUserpoolPasswordQualityPolicyPtrInput
	Timeouts              OrganizationmanagerIdpUserpoolTimeoutsPtrInput
	// User settings for this userpool.
	UserSettings OrganizationmanagerIdpUserpoolUserSettingsPtrInput
	// ID of the userpool to return.
	//  To get the userpool ID, make a [UserpoolService.List] request.
	UserpoolId pulumi.StringPtrInput
}

func (OrganizationmanagerIdpUserpoolArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationmanagerIdpUserpoolArgs)(nil)).Elem()
}

type OrganizationmanagerIdpUserpoolInput interface {
	pulumi.Input

	ToOrganizationmanagerIdpUserpoolOutput() OrganizationmanagerIdpUserpoolOutput
	ToOrganizationmanagerIdpUserpoolOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolOutput
}

func (*OrganizationmanagerIdpUserpool) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationmanagerIdpUserpool)(nil)).Elem()
}

func (i *OrganizationmanagerIdpUserpool) ToOrganizationmanagerIdpUserpoolOutput() OrganizationmanagerIdpUserpoolOutput {
	return i.ToOrganizationmanagerIdpUserpoolOutputWithContext(context.Background())
}

func (i *OrganizationmanagerIdpUserpool) ToOrganizationmanagerIdpUserpoolOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationmanagerIdpUserpoolOutput)
}

// OrganizationmanagerIdpUserpoolArrayInput is an input type that accepts OrganizationmanagerIdpUserpoolArray and OrganizationmanagerIdpUserpoolArrayOutput values.
// You can construct a concrete instance of `OrganizationmanagerIdpUserpoolArrayInput` via:
//
//	OrganizationmanagerIdpUserpoolArray{ OrganizationmanagerIdpUserpoolArgs{...} }
type OrganizationmanagerIdpUserpoolArrayInput interface {
	pulumi.Input

	ToOrganizationmanagerIdpUserpoolArrayOutput() OrganizationmanagerIdpUserpoolArrayOutput
	ToOrganizationmanagerIdpUserpoolArrayOutputWithContext(context.Context) OrganizationmanagerIdpUserpoolArrayOutput
}

type OrganizationmanagerIdpUserpoolArray []OrganizationmanagerIdpUserpoolInput

func (OrganizationmanagerIdpUserpoolArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OrganizationmanagerIdpUserpool)(nil)).Elem()
}

func (i OrganizationmanagerIdpUserpoolArray) ToOrganizationmanagerIdpUserpoolArrayOutput() OrganizationmanagerIdpUserpoolArrayOutput {
	return i.ToOrganizationmanagerIdpUserpoolArrayOutputWithContext(context.Background())
}

func (i OrganizationmanagerIdpUserpoolArray) ToOrganizationmanagerIdpUserpoolArrayOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationmanagerIdpUserpoolArrayOutput)
}

// OrganizationmanagerIdpUserpoolMapInput is an input type that accepts OrganizationmanagerIdpUserpoolMap and OrganizationmanagerIdpUserpoolMapOutput values.
// You can construct a concrete instance of `OrganizationmanagerIdpUserpoolMapInput` via:
//
//	OrganizationmanagerIdpUserpoolMap{ "key": OrganizationmanagerIdpUserpoolArgs{...} }
type OrganizationmanagerIdpUserpoolMapInput interface {
	pulumi.Input

	ToOrganizationmanagerIdpUserpoolMapOutput() OrganizationmanagerIdpUserpoolMapOutput
	ToOrganizationmanagerIdpUserpoolMapOutputWithContext(context.Context) OrganizationmanagerIdpUserpoolMapOutput
}

type OrganizationmanagerIdpUserpoolMap map[string]OrganizationmanagerIdpUserpoolInput

func (OrganizationmanagerIdpUserpoolMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OrganizationmanagerIdpUserpool)(nil)).Elem()
}

func (i OrganizationmanagerIdpUserpoolMap) ToOrganizationmanagerIdpUserpoolMapOutput() OrganizationmanagerIdpUserpoolMapOutput {
	return i.ToOrganizationmanagerIdpUserpoolMapOutputWithContext(context.Background())
}

func (i OrganizationmanagerIdpUserpoolMap) ToOrganizationmanagerIdpUserpoolMapOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationmanagerIdpUserpoolMapOutput)
}

type OrganizationmanagerIdpUserpoolOutput struct{ *pulumi.OutputState }

func (OrganizationmanagerIdpUserpoolOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationmanagerIdpUserpool)(nil)).Elem()
}

func (o OrganizationmanagerIdpUserpoolOutput) ToOrganizationmanagerIdpUserpoolOutput() OrganizationmanagerIdpUserpoolOutput {
	return o
}

func (o OrganizationmanagerIdpUserpoolOutput) ToOrganizationmanagerIdpUserpoolOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolOutput {
	return o
}

// Bruteforce protection policy for this userpool.
func (o OrganizationmanagerIdpUserpoolOutput) BruteforceProtectionPolicy() OrganizationmanagerIdpUserpoolBruteforceProtectionPolicyOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) OrganizationmanagerIdpUserpoolBruteforceProtectionPolicyOutput {
		return v.BruteforceProtectionPolicy
	}).(OrganizationmanagerIdpUserpoolBruteforceProtectionPolicyOutput)
}

// Timestamp when the userpool was created.
func (o OrganizationmanagerIdpUserpoolOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// Default subdomain for the userpool.
func (o OrganizationmanagerIdpUserpoolOutput) DefaultSubdomain() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.DefaultSubdomain }).(pulumi.StringOutput)
}

// Description of the userpool.
func (o OrganizationmanagerIdpUserpoolOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// List of domains associated with this userpool.
func (o OrganizationmanagerIdpUserpoolOutput) Domains() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringArrayOutput { return v.Domains }).(pulumi.StringArrayOutput)
}

// Resource labels as key:value pairs.
func (o OrganizationmanagerIdpUserpoolOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// Name of the userpool.
func (o OrganizationmanagerIdpUserpoolOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// ID of the organization this userpool belongs to.
func (o OrganizationmanagerIdpUserpoolOutput) OrganizationId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.OrganizationId }).(pulumi.StringOutput)
}

// ID of the userpool to return.
//
//	To get the userpool ID, make a [UserpoolService.List] request.
func (o OrganizationmanagerIdpUserpoolOutput) OrganizationmanagerIdpUserpoolId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.OrganizationmanagerIdpUserpoolId }).(pulumi.StringOutput)
}

// Password blacklist policy for this userpool.
func (o OrganizationmanagerIdpUserpoolOutput) PasswordBlacklistPolicy() OrganizationmanagerIdpUserpoolPasswordBlacklistPolicyOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) OrganizationmanagerIdpUserpoolPasswordBlacklistPolicyOutput {
		return v.PasswordBlacklistPolicy
	}).(OrganizationmanagerIdpUserpoolPasswordBlacklistPolicyOutput)
}

// Password lifetime policy for this userpool.
func (o OrganizationmanagerIdpUserpoolOutput) PasswordLifetimePolicy() OrganizationmanagerIdpUserpoolPasswordLifetimePolicyOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) OrganizationmanagerIdpUserpoolPasswordLifetimePolicyOutput {
		return v.PasswordLifetimePolicy
	}).(OrganizationmanagerIdpUserpoolPasswordLifetimePolicyOutput)
}

// Password quality policy for this userpool.
func (o OrganizationmanagerIdpUserpoolOutput) PasswordQualityPolicy() OrganizationmanagerIdpUserpoolPasswordQualityPolicyOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) OrganizationmanagerIdpUserpoolPasswordQualityPolicyOutput {
		return v.PasswordQualityPolicy
	}).(OrganizationmanagerIdpUserpoolPasswordQualityPolicyOutput)
}

// Current status of the userpool.
func (o OrganizationmanagerIdpUserpoolOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

func (o OrganizationmanagerIdpUserpoolOutput) Timeouts() OrganizationmanagerIdpUserpoolTimeoutsPtrOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) OrganizationmanagerIdpUserpoolTimeoutsPtrOutput {
		return v.Timeouts
	}).(OrganizationmanagerIdpUserpoolTimeoutsPtrOutput)
}

// Timestamp when the userpool was last updated.
func (o OrganizationmanagerIdpUserpoolOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

// User settings for this userpool.
func (o OrganizationmanagerIdpUserpoolOutput) UserSettings() OrganizationmanagerIdpUserpoolUserSettingsOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) OrganizationmanagerIdpUserpoolUserSettingsOutput {
		return v.UserSettings
	}).(OrganizationmanagerIdpUserpoolUserSettingsOutput)
}

// ID of the userpool to return.
//
//	To get the userpool ID, make a [UserpoolService.List] request.
func (o OrganizationmanagerIdpUserpoolOutput) UserpoolId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerIdpUserpool) pulumi.StringOutput { return v.UserpoolId }).(pulumi.StringOutput)
}

type OrganizationmanagerIdpUserpoolArrayOutput struct{ *pulumi.OutputState }

func (OrganizationmanagerIdpUserpoolArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OrganizationmanagerIdpUserpool)(nil)).Elem()
}

func (o OrganizationmanagerIdpUserpoolArrayOutput) ToOrganizationmanagerIdpUserpoolArrayOutput() OrganizationmanagerIdpUserpoolArrayOutput {
	return o
}

func (o OrganizationmanagerIdpUserpoolArrayOutput) ToOrganizationmanagerIdpUserpoolArrayOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolArrayOutput {
	return o
}

func (o OrganizationmanagerIdpUserpoolArrayOutput) Index(i pulumi.IntInput) OrganizationmanagerIdpUserpoolOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OrganizationmanagerIdpUserpool {
		return vs[0].([]*OrganizationmanagerIdpUserpool)[vs[1].(int)]
	}).(OrganizationmanagerIdpUserpoolOutput)
}

type OrganizationmanagerIdpUserpoolMapOutput struct{ *pulumi.OutputState }

func (OrganizationmanagerIdpUserpoolMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OrganizationmanagerIdpUserpool)(nil)).Elem()
}

func (o OrganizationmanagerIdpUserpoolMapOutput) ToOrganizationmanagerIdpUserpoolMapOutput() OrganizationmanagerIdpUserpoolMapOutput {
	return o
}

func (o OrganizationmanagerIdpUserpoolMapOutput) ToOrganizationmanagerIdpUserpoolMapOutputWithContext(ctx context.Context) OrganizationmanagerIdpUserpoolMapOutput {
	return o
}

func (o OrganizationmanagerIdpUserpoolMapOutput) MapIndex(k pulumi.StringInput) OrganizationmanagerIdpUserpoolOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OrganizationmanagerIdpUserpool {
		return vs[0].(map[string]*OrganizationmanagerIdpUserpool)[vs[1].(string)]
	}).(OrganizationmanagerIdpUserpoolOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationmanagerIdpUserpoolInput)(nil)).Elem(), &OrganizationmanagerIdpUserpool{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationmanagerIdpUserpoolArrayInput)(nil)).Elem(), OrganizationmanagerIdpUserpoolArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationmanagerIdpUserpoolMapInput)(nil)).Elem(), OrganizationmanagerIdpUserpoolMap{})
	pulumi.RegisterOutputType(OrganizationmanagerIdpUserpoolOutput{})
	pulumi.RegisterOutputType(OrganizationmanagerIdpUserpoolArrayOutput{})
	pulumi.RegisterOutputType(OrganizationmanagerIdpUserpoolMapOutput{})
}
