// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// MFA enforcement audience resource
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Example OrganizationManager MFA Enforcement.
//			exampleMfaEnforcement, err := yandex.NewOrganizationmanagerMfaEnforcement(ctx, "exampleMfaEnforcement", &yandex.OrganizationmanagerMfaEnforcementArgs{
//				OrganizationId: pulumi.String("your_organization_id"),
//				AcrId:          pulumi.String("any-mfa"),
//				Ttl:            pulumi.String("2h45m"),
//				Status:         pulumi.String("MFA_ENFORCEMENT_STATUS_ACTIVE"),
//				EnrollWindow:   pulumi.String("2h45m"),
//				Description:    pulumi.String("Description example"),
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new OrganizationManager MFA Enforcement Audience.
//			_, err = yandex.NewOrganizationmanagerMfaEnforcementAudience(ctx, "exampleMfaEnforcementAudience", &yandex.OrganizationmanagerMfaEnforcementAudienceArgs{
//				MfaEnforcementId: exampleMfaEnforcement.OrganizationmanagerMfaEnforcementId,
//				SubjectId:        pulumi.String("your_subject_id"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `mfaEnforcementId` (**Required**)(String). MFA enforcement id
// - `subjectId` (**Required**)(String). Subject id
type OrganizationmanagerMfaEnforcementAudience struct {
	pulumi.CustomResourceState

	// MFA enforcement id
	MfaEnforcementId pulumi.StringOutput `pulumi:"mfaEnforcementId"`
	// Subject id
	SubjectId pulumi.StringOutput `pulumi:"subjectId"`
}

// NewOrganizationmanagerMfaEnforcementAudience registers a new resource with the given unique name, arguments, and options.
func NewOrganizationmanagerMfaEnforcementAudience(ctx *pulumi.Context,
	name string, args *OrganizationmanagerMfaEnforcementAudienceArgs, opts ...pulumi.ResourceOption) (*OrganizationmanagerMfaEnforcementAudience, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.MfaEnforcementId == nil {
		return nil, errors.New("invalid value for required argument 'MfaEnforcementId'")
	}
	if args.SubjectId == nil {
		return nil, errors.New("invalid value for required argument 'SubjectId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource OrganizationmanagerMfaEnforcementAudience
	err := ctx.RegisterResource("yandex:index/organizationmanagerMfaEnforcementAudience:OrganizationmanagerMfaEnforcementAudience", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetOrganizationmanagerMfaEnforcementAudience gets an existing OrganizationmanagerMfaEnforcementAudience resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetOrganizationmanagerMfaEnforcementAudience(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *OrganizationmanagerMfaEnforcementAudienceState, opts ...pulumi.ResourceOption) (*OrganizationmanagerMfaEnforcementAudience, error) {
	var resource OrganizationmanagerMfaEnforcementAudience
	err := ctx.ReadResource("yandex:index/organizationmanagerMfaEnforcementAudience:OrganizationmanagerMfaEnforcementAudience", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering OrganizationmanagerMfaEnforcementAudience resources.
type organizationmanagerMfaEnforcementAudienceState struct {
	// MFA enforcement id
	MfaEnforcementId *string `pulumi:"mfaEnforcementId"`
	// Subject id
	SubjectId *string `pulumi:"subjectId"`
}

type OrganizationmanagerMfaEnforcementAudienceState struct {
	// MFA enforcement id
	MfaEnforcementId pulumi.StringPtrInput
	// Subject id
	SubjectId pulumi.StringPtrInput
}

func (OrganizationmanagerMfaEnforcementAudienceState) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationmanagerMfaEnforcementAudienceState)(nil)).Elem()
}

type organizationmanagerMfaEnforcementAudienceArgs struct {
	// MFA enforcement id
	MfaEnforcementId string `pulumi:"mfaEnforcementId"`
	// Subject id
	SubjectId string `pulumi:"subjectId"`
}

// The set of arguments for constructing a OrganizationmanagerMfaEnforcementAudience resource.
type OrganizationmanagerMfaEnforcementAudienceArgs struct {
	// MFA enforcement id
	MfaEnforcementId pulumi.StringInput
	// Subject id
	SubjectId pulumi.StringInput
}

func (OrganizationmanagerMfaEnforcementAudienceArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*organizationmanagerMfaEnforcementAudienceArgs)(nil)).Elem()
}

type OrganizationmanagerMfaEnforcementAudienceInput interface {
	pulumi.Input

	ToOrganizationmanagerMfaEnforcementAudienceOutput() OrganizationmanagerMfaEnforcementAudienceOutput
	ToOrganizationmanagerMfaEnforcementAudienceOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceOutput
}

func (*OrganizationmanagerMfaEnforcementAudience) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationmanagerMfaEnforcementAudience)(nil)).Elem()
}

func (i *OrganizationmanagerMfaEnforcementAudience) ToOrganizationmanagerMfaEnforcementAudienceOutput() OrganizationmanagerMfaEnforcementAudienceOutput {
	return i.ToOrganizationmanagerMfaEnforcementAudienceOutputWithContext(context.Background())
}

func (i *OrganizationmanagerMfaEnforcementAudience) ToOrganizationmanagerMfaEnforcementAudienceOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationmanagerMfaEnforcementAudienceOutput)
}

// OrganizationmanagerMfaEnforcementAudienceArrayInput is an input type that accepts OrganizationmanagerMfaEnforcementAudienceArray and OrganizationmanagerMfaEnforcementAudienceArrayOutput values.
// You can construct a concrete instance of `OrganizationmanagerMfaEnforcementAudienceArrayInput` via:
//
//	OrganizationmanagerMfaEnforcementAudienceArray{ OrganizationmanagerMfaEnforcementAudienceArgs{...} }
type OrganizationmanagerMfaEnforcementAudienceArrayInput interface {
	pulumi.Input

	ToOrganizationmanagerMfaEnforcementAudienceArrayOutput() OrganizationmanagerMfaEnforcementAudienceArrayOutput
	ToOrganizationmanagerMfaEnforcementAudienceArrayOutputWithContext(context.Context) OrganizationmanagerMfaEnforcementAudienceArrayOutput
}

type OrganizationmanagerMfaEnforcementAudienceArray []OrganizationmanagerMfaEnforcementAudienceInput

func (OrganizationmanagerMfaEnforcementAudienceArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OrganizationmanagerMfaEnforcementAudience)(nil)).Elem()
}

func (i OrganizationmanagerMfaEnforcementAudienceArray) ToOrganizationmanagerMfaEnforcementAudienceArrayOutput() OrganizationmanagerMfaEnforcementAudienceArrayOutput {
	return i.ToOrganizationmanagerMfaEnforcementAudienceArrayOutputWithContext(context.Background())
}

func (i OrganizationmanagerMfaEnforcementAudienceArray) ToOrganizationmanagerMfaEnforcementAudienceArrayOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationmanagerMfaEnforcementAudienceArrayOutput)
}

// OrganizationmanagerMfaEnforcementAudienceMapInput is an input type that accepts OrganizationmanagerMfaEnforcementAudienceMap and OrganizationmanagerMfaEnforcementAudienceMapOutput values.
// You can construct a concrete instance of `OrganizationmanagerMfaEnforcementAudienceMapInput` via:
//
//	OrganizationmanagerMfaEnforcementAudienceMap{ "key": OrganizationmanagerMfaEnforcementAudienceArgs{...} }
type OrganizationmanagerMfaEnforcementAudienceMapInput interface {
	pulumi.Input

	ToOrganizationmanagerMfaEnforcementAudienceMapOutput() OrganizationmanagerMfaEnforcementAudienceMapOutput
	ToOrganizationmanagerMfaEnforcementAudienceMapOutputWithContext(context.Context) OrganizationmanagerMfaEnforcementAudienceMapOutput
}

type OrganizationmanagerMfaEnforcementAudienceMap map[string]OrganizationmanagerMfaEnforcementAudienceInput

func (OrganizationmanagerMfaEnforcementAudienceMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OrganizationmanagerMfaEnforcementAudience)(nil)).Elem()
}

func (i OrganizationmanagerMfaEnforcementAudienceMap) ToOrganizationmanagerMfaEnforcementAudienceMapOutput() OrganizationmanagerMfaEnforcementAudienceMapOutput {
	return i.ToOrganizationmanagerMfaEnforcementAudienceMapOutputWithContext(context.Background())
}

func (i OrganizationmanagerMfaEnforcementAudienceMap) ToOrganizationmanagerMfaEnforcementAudienceMapOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(OrganizationmanagerMfaEnforcementAudienceMapOutput)
}

type OrganizationmanagerMfaEnforcementAudienceOutput struct{ *pulumi.OutputState }

func (OrganizationmanagerMfaEnforcementAudienceOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**OrganizationmanagerMfaEnforcementAudience)(nil)).Elem()
}

func (o OrganizationmanagerMfaEnforcementAudienceOutput) ToOrganizationmanagerMfaEnforcementAudienceOutput() OrganizationmanagerMfaEnforcementAudienceOutput {
	return o
}

func (o OrganizationmanagerMfaEnforcementAudienceOutput) ToOrganizationmanagerMfaEnforcementAudienceOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceOutput {
	return o
}

// MFA enforcement id
func (o OrganizationmanagerMfaEnforcementAudienceOutput) MfaEnforcementId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerMfaEnforcementAudience) pulumi.StringOutput { return v.MfaEnforcementId }).(pulumi.StringOutput)
}

// Subject id
func (o OrganizationmanagerMfaEnforcementAudienceOutput) SubjectId() pulumi.StringOutput {
	return o.ApplyT(func(v *OrganizationmanagerMfaEnforcementAudience) pulumi.StringOutput { return v.SubjectId }).(pulumi.StringOutput)
}

type OrganizationmanagerMfaEnforcementAudienceArrayOutput struct{ *pulumi.OutputState }

func (OrganizationmanagerMfaEnforcementAudienceArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*OrganizationmanagerMfaEnforcementAudience)(nil)).Elem()
}

func (o OrganizationmanagerMfaEnforcementAudienceArrayOutput) ToOrganizationmanagerMfaEnforcementAudienceArrayOutput() OrganizationmanagerMfaEnforcementAudienceArrayOutput {
	return o
}

func (o OrganizationmanagerMfaEnforcementAudienceArrayOutput) ToOrganizationmanagerMfaEnforcementAudienceArrayOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceArrayOutput {
	return o
}

func (o OrganizationmanagerMfaEnforcementAudienceArrayOutput) Index(i pulumi.IntInput) OrganizationmanagerMfaEnforcementAudienceOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *OrganizationmanagerMfaEnforcementAudience {
		return vs[0].([]*OrganizationmanagerMfaEnforcementAudience)[vs[1].(int)]
	}).(OrganizationmanagerMfaEnforcementAudienceOutput)
}

type OrganizationmanagerMfaEnforcementAudienceMapOutput struct{ *pulumi.OutputState }

func (OrganizationmanagerMfaEnforcementAudienceMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*OrganizationmanagerMfaEnforcementAudience)(nil)).Elem()
}

func (o OrganizationmanagerMfaEnforcementAudienceMapOutput) ToOrganizationmanagerMfaEnforcementAudienceMapOutput() OrganizationmanagerMfaEnforcementAudienceMapOutput {
	return o
}

func (o OrganizationmanagerMfaEnforcementAudienceMapOutput) ToOrganizationmanagerMfaEnforcementAudienceMapOutputWithContext(ctx context.Context) OrganizationmanagerMfaEnforcementAudienceMapOutput {
	return o
}

func (o OrganizationmanagerMfaEnforcementAudienceMapOutput) MapIndex(k pulumi.StringInput) OrganizationmanagerMfaEnforcementAudienceOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *OrganizationmanagerMfaEnforcementAudience {
		return vs[0].(map[string]*OrganizationmanagerMfaEnforcementAudience)[vs[1].(string)]
	}).(OrganizationmanagerMfaEnforcementAudienceOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationmanagerMfaEnforcementAudienceInput)(nil)).Elem(), &OrganizationmanagerMfaEnforcementAudience{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationmanagerMfaEnforcementAudienceArrayInput)(nil)).Elem(), OrganizationmanagerMfaEnforcementAudienceArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*OrganizationmanagerMfaEnforcementAudienceMapInput)(nil)).Elem(), OrganizationmanagerMfaEnforcementAudienceMap{})
	pulumi.RegisterOutputType(OrganizationmanagerMfaEnforcementAudienceOutput{})
	pulumi.RegisterOutputType(OrganizationmanagerMfaEnforcementAudienceArrayOutput{})
	pulumi.RegisterOutputType(OrganizationmanagerMfaEnforcementAudienceMapOutput{})
}
