// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// A Smart Web Security load balancer resource.
//
// ## Arguments & Attributes Reference
//
//   - `createdAt` (*Read-Only*) (String). Creation time.
//   - `ddosProtectionProvider` (*Read-Only*) (String). L3-L4 DDoS protection provider. Currently supported: "" or "qrator".
//   - `deletionProtection` (Bool). Forbids Delete() calls.
//     NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
//   - `description` (String). Description of the load balancer.
//   - `folderId` (String). ID of the folder that the load balancer belongs to.
//   - `id` (String). ID of the load balancer to return.
//   - `ipAddress` (*Read-Only*) (String). IP address of resulting balancer.
//   - `labels` (Map Of String). Resource labels as `key:value` pairs.
//   - `loadBalancerId` (String). ID of the load balancer to return.
//   - `logGroupId` (*Read-Only*) (String). Cloud logging log group ID.
//     If empty string was passed to log options, this field will contain ID of default log group.
//     If logs are disabled, this field will contain empty string.
//   - `logOptions` [Block]. Cloud logging settings.
//   - `disable` (Bool). Do not send logs to Cloud Logging log group.
//   - `discardRule` [Block]. Ordered list of rules, first matching rule applies.
//   - `discardPercent` (Number). Percent of logs to be discarded: 0 - keep all, 100 or unset - discard all.
//   - `httpCodeIntervals` (List Of String). Groups of HTTP codes like 4xx that should be discarded.
//   - `httpCodes` (List Of Number). HTTP codes that should be discarded.
//   - `logGroupId` (String). ID of Cloud Logging log group.
//     Keep empty to use default log group.
//   - `name` (**Required**)(String). Name of the load balancer.
//   - `regionId` (**Required**)(String). "ru-central1", "kz1", etc.
//   - `resourceUnits` (Number). Number of initially allocated resource units.
//     Zero means the minimum configured for the service installation.
//   - `routeOptions` [Block]. Options that apply to all domains.
//   - `modifyRequestHeaders` [Block]. Apply the following modifications to the request headers.
//   - `append` (String). Append string to the header value.
//   - `name` (**Required**)(String). Name of the header.
//   - `remove` (Bool). Remove the header.
//   - `rename` (String). New name for a header.
//   - `replace` (String). New value for a header.
//   - `modifyResponseHeaders` [Block]. Apply the following modifications to the response headers.
//   - `append` (String). Append string to the header value.
//   - `name` (**Required**)(String). Name of the header.
//   - `remove` (Bool). Remove the header.
//   - `rename` (String). New name for a header.
//   - `replace` (String). New value for a header.
//   - `serviceAccountId` (String). Service account for access to certificate, securityProfile and logGroup.
//   - `status` (*Read-Only*) (String). Status of the load balancer.
//   - `timeouts` [Block].
//   - `create` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `delete` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Setting a timeout for a Delete operation is only applicable if changes are saved into state before the destroy operation occurs.
//   - `read` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours). Read operations occur during any refresh or planning operation when refresh is enabled.
//   - `update` (String). A string that can be [parsed as a duration](https://pkg.go.dev/time#ParseDuration) consisting of numbers and unit suffixes, such as "30s" or "2h45m". Valid time units are "s" (seconds), "m" (minutes), "h" (hours).
//   - `updatedAt` (*Read-Only*) (String). Last time when the load balancer was modified.
type SwsLoadBalancer struct {
	pulumi.CustomResourceState

	// Creation time.
	CreatedAt pulumi.StringOutput `pulumi:"createdAt"`
	// L3-L4 DDoS protection provider. Currently supported: "" or "qrator".
	DdosProtectionProvider pulumi.StringOutput `pulumi:"ddosProtectionProvider"`
	// Forbids Delete() calls.
	//  NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
	DeletionProtection pulumi.BoolOutput `pulumi:"deletionProtection"`
	// Description of the load balancer.
	Description pulumi.StringOutput `pulumi:"description"`
	// ID of the folder that the load balancer belongs to.
	FolderId pulumi.StringOutput `pulumi:"folderId"`
	// IP address of resulting balancer.
	IpAddress pulumi.StringOutput `pulumi:"ipAddress"`
	// Resource labels as `key:value` pairs.
	Labels pulumi.StringMapOutput `pulumi:"labels"`
	// ID of the load balancer to return.
	LoadBalancerId pulumi.StringOutput `pulumi:"loadBalancerId"`
	// Cloud logging log group ID.
	//  If empty string was passed to log options, this field will contain ID of default log group.
	//  If logs are disabled, this field will contain empty string.
	LogGroupId pulumi.StringOutput `pulumi:"logGroupId"`
	// Cloud logging settings.
	LogOptions SwsLoadBalancerLogOptionsOutput `pulumi:"logOptions"`
	// Name of the load balancer.
	Name pulumi.StringOutput `pulumi:"name"`
	// "ru-central1", "kz1", etc.
	RegionId pulumi.StringOutput `pulumi:"regionId"`
	// Number of initially allocated resource units.
	//  Zero means the minimum configured for the service installation.
	ResourceUnits pulumi.IntOutput `pulumi:"resourceUnits"`
	// Options that apply to all domains.
	RouteOptions SwsLoadBalancerRouteOptionsOutput `pulumi:"routeOptions"`
	// Service account for access to certificate, securityProfile and logGroup.
	ServiceAccountId pulumi.StringOutput `pulumi:"serviceAccountId"`
	// Status of the load balancer.
	Status pulumi.StringOutput `pulumi:"status"`
	// ID of the load balancer to return.
	SwsLoadBalancerId pulumi.StringOutput              `pulumi:"swsLoadBalancerId"`
	Timeouts          SwsLoadBalancerTimeoutsPtrOutput `pulumi:"timeouts"`
	// Last time when the load balancer was modified.
	UpdatedAt pulumi.StringOutput `pulumi:"updatedAt"`
}

// NewSwsLoadBalancer registers a new resource with the given unique name, arguments, and options.
func NewSwsLoadBalancer(ctx *pulumi.Context,
	name string, args *SwsLoadBalancerArgs, opts ...pulumi.ResourceOption) (*SwsLoadBalancer, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.RegionId == nil {
		return nil, errors.New("invalid value for required argument 'RegionId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SwsLoadBalancer
	err := ctx.RegisterResource("yandex:index/swsLoadBalancer:SwsLoadBalancer", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSwsLoadBalancer gets an existing SwsLoadBalancer resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSwsLoadBalancer(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SwsLoadBalancerState, opts ...pulumi.ResourceOption) (*SwsLoadBalancer, error) {
	var resource SwsLoadBalancer
	err := ctx.ReadResource("yandex:index/swsLoadBalancer:SwsLoadBalancer", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SwsLoadBalancer resources.
type swsLoadBalancerState struct {
	// Creation time.
	CreatedAt *string `pulumi:"createdAt"`
	// L3-L4 DDoS protection provider. Currently supported: "" or "qrator".
	DdosProtectionProvider *string `pulumi:"ddosProtectionProvider"`
	// Forbids Delete() calls.
	//  NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// Description of the load balancer.
	Description *string `pulumi:"description"`
	// ID of the folder that the load balancer belongs to.
	FolderId *string `pulumi:"folderId"`
	// IP address of resulting balancer.
	IpAddress *string `pulumi:"ipAddress"`
	// Resource labels as `key:value` pairs.
	Labels map[string]string `pulumi:"labels"`
	// ID of the load balancer to return.
	LoadBalancerId *string `pulumi:"loadBalancerId"`
	// Cloud logging log group ID.
	//  If empty string was passed to log options, this field will contain ID of default log group.
	//  If logs are disabled, this field will contain empty string.
	LogGroupId *string `pulumi:"logGroupId"`
	// Cloud logging settings.
	LogOptions *SwsLoadBalancerLogOptions `pulumi:"logOptions"`
	// Name of the load balancer.
	Name *string `pulumi:"name"`
	// "ru-central1", "kz1", etc.
	RegionId *string `pulumi:"regionId"`
	// Number of initially allocated resource units.
	//  Zero means the minimum configured for the service installation.
	ResourceUnits *int `pulumi:"resourceUnits"`
	// Options that apply to all domains.
	RouteOptions *SwsLoadBalancerRouteOptions `pulumi:"routeOptions"`
	// Service account for access to certificate, securityProfile and logGroup.
	ServiceAccountId *string `pulumi:"serviceAccountId"`
	// Status of the load balancer.
	Status *string `pulumi:"status"`
	// ID of the load balancer to return.
	SwsLoadBalancerId *string                  `pulumi:"swsLoadBalancerId"`
	Timeouts          *SwsLoadBalancerTimeouts `pulumi:"timeouts"`
	// Last time when the load balancer was modified.
	UpdatedAt *string `pulumi:"updatedAt"`
}

type SwsLoadBalancerState struct {
	// Creation time.
	CreatedAt pulumi.StringPtrInput
	// L3-L4 DDoS protection provider. Currently supported: "" or "qrator".
	DdosProtectionProvider pulumi.StringPtrInput
	// Forbids Delete() calls.
	//  NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
	DeletionProtection pulumi.BoolPtrInput
	// Description of the load balancer.
	Description pulumi.StringPtrInput
	// ID of the folder that the load balancer belongs to.
	FolderId pulumi.StringPtrInput
	// IP address of resulting balancer.
	IpAddress pulumi.StringPtrInput
	// Resource labels as `key:value` pairs.
	Labels pulumi.StringMapInput
	// ID of the load balancer to return.
	LoadBalancerId pulumi.StringPtrInput
	// Cloud logging log group ID.
	//  If empty string was passed to log options, this field will contain ID of default log group.
	//  If logs are disabled, this field will contain empty string.
	LogGroupId pulumi.StringPtrInput
	// Cloud logging settings.
	LogOptions SwsLoadBalancerLogOptionsPtrInput
	// Name of the load balancer.
	Name pulumi.StringPtrInput
	// "ru-central1", "kz1", etc.
	RegionId pulumi.StringPtrInput
	// Number of initially allocated resource units.
	//  Zero means the minimum configured for the service installation.
	ResourceUnits pulumi.IntPtrInput
	// Options that apply to all domains.
	RouteOptions SwsLoadBalancerRouteOptionsPtrInput
	// Service account for access to certificate, securityProfile and logGroup.
	ServiceAccountId pulumi.StringPtrInput
	// Status of the load balancer.
	Status pulumi.StringPtrInput
	// ID of the load balancer to return.
	SwsLoadBalancerId pulumi.StringPtrInput
	Timeouts          SwsLoadBalancerTimeoutsPtrInput
	// Last time when the load balancer was modified.
	UpdatedAt pulumi.StringPtrInput
}

func (SwsLoadBalancerState) ElementType() reflect.Type {
	return reflect.TypeOf((*swsLoadBalancerState)(nil)).Elem()
}

type swsLoadBalancerArgs struct {
	// Forbids Delete() calls.
	//  NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
	DeletionProtection *bool `pulumi:"deletionProtection"`
	// Description of the load balancer.
	Description *string `pulumi:"description"`
	// ID of the folder that the load balancer belongs to.
	FolderId *string `pulumi:"folderId"`
	// Resource labels as `key:value` pairs.
	Labels map[string]string `pulumi:"labels"`
	// ID of the load balancer to return.
	LoadBalancerId *string `pulumi:"loadBalancerId"`
	// Cloud logging settings.
	LogOptions *SwsLoadBalancerLogOptions `pulumi:"logOptions"`
	// Name of the load balancer.
	Name *string `pulumi:"name"`
	// "ru-central1", "kz1", etc.
	RegionId string `pulumi:"regionId"`
	// Number of initially allocated resource units.
	//  Zero means the minimum configured for the service installation.
	ResourceUnits *int `pulumi:"resourceUnits"`
	// Options that apply to all domains.
	RouteOptions *SwsLoadBalancerRouteOptions `pulumi:"routeOptions"`
	// Service account for access to certificate, securityProfile and logGroup.
	ServiceAccountId *string `pulumi:"serviceAccountId"`
	// ID of the load balancer to return.
	SwsLoadBalancerId *string                  `pulumi:"swsLoadBalancerId"`
	Timeouts          *SwsLoadBalancerTimeouts `pulumi:"timeouts"`
}

// The set of arguments for constructing a SwsLoadBalancer resource.
type SwsLoadBalancerArgs struct {
	// Forbids Delete() calls.
	//  NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
	DeletionProtection pulumi.BoolPtrInput
	// Description of the load balancer.
	Description pulumi.StringPtrInput
	// ID of the folder that the load balancer belongs to.
	FolderId pulumi.StringPtrInput
	// Resource labels as `key:value` pairs.
	Labels pulumi.StringMapInput
	// ID of the load balancer to return.
	LoadBalancerId pulumi.StringPtrInput
	// Cloud logging settings.
	LogOptions SwsLoadBalancerLogOptionsPtrInput
	// Name of the load balancer.
	Name pulumi.StringPtrInput
	// "ru-central1", "kz1", etc.
	RegionId pulumi.StringInput
	// Number of initially allocated resource units.
	//  Zero means the minimum configured for the service installation.
	ResourceUnits pulumi.IntPtrInput
	// Options that apply to all domains.
	RouteOptions SwsLoadBalancerRouteOptionsPtrInput
	// Service account for access to certificate, securityProfile and logGroup.
	ServiceAccountId pulumi.StringPtrInput
	// ID of the load balancer to return.
	SwsLoadBalancerId pulumi.StringPtrInput
	Timeouts          SwsLoadBalancerTimeoutsPtrInput
}

func (SwsLoadBalancerArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*swsLoadBalancerArgs)(nil)).Elem()
}

type SwsLoadBalancerInput interface {
	pulumi.Input

	ToSwsLoadBalancerOutput() SwsLoadBalancerOutput
	ToSwsLoadBalancerOutputWithContext(ctx context.Context) SwsLoadBalancerOutput
}

func (*SwsLoadBalancer) ElementType() reflect.Type {
	return reflect.TypeOf((**SwsLoadBalancer)(nil)).Elem()
}

func (i *SwsLoadBalancer) ToSwsLoadBalancerOutput() SwsLoadBalancerOutput {
	return i.ToSwsLoadBalancerOutputWithContext(context.Background())
}

func (i *SwsLoadBalancer) ToSwsLoadBalancerOutputWithContext(ctx context.Context) SwsLoadBalancerOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwsLoadBalancerOutput)
}

// SwsLoadBalancerArrayInput is an input type that accepts SwsLoadBalancerArray and SwsLoadBalancerArrayOutput values.
// You can construct a concrete instance of `SwsLoadBalancerArrayInput` via:
//
//	SwsLoadBalancerArray{ SwsLoadBalancerArgs{...} }
type SwsLoadBalancerArrayInput interface {
	pulumi.Input

	ToSwsLoadBalancerArrayOutput() SwsLoadBalancerArrayOutput
	ToSwsLoadBalancerArrayOutputWithContext(context.Context) SwsLoadBalancerArrayOutput
}

type SwsLoadBalancerArray []SwsLoadBalancerInput

func (SwsLoadBalancerArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwsLoadBalancer)(nil)).Elem()
}

func (i SwsLoadBalancerArray) ToSwsLoadBalancerArrayOutput() SwsLoadBalancerArrayOutput {
	return i.ToSwsLoadBalancerArrayOutputWithContext(context.Background())
}

func (i SwsLoadBalancerArray) ToSwsLoadBalancerArrayOutputWithContext(ctx context.Context) SwsLoadBalancerArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwsLoadBalancerArrayOutput)
}

// SwsLoadBalancerMapInput is an input type that accepts SwsLoadBalancerMap and SwsLoadBalancerMapOutput values.
// You can construct a concrete instance of `SwsLoadBalancerMapInput` via:
//
//	SwsLoadBalancerMap{ "key": SwsLoadBalancerArgs{...} }
type SwsLoadBalancerMapInput interface {
	pulumi.Input

	ToSwsLoadBalancerMapOutput() SwsLoadBalancerMapOutput
	ToSwsLoadBalancerMapOutputWithContext(context.Context) SwsLoadBalancerMapOutput
}

type SwsLoadBalancerMap map[string]SwsLoadBalancerInput

func (SwsLoadBalancerMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwsLoadBalancer)(nil)).Elem()
}

func (i SwsLoadBalancerMap) ToSwsLoadBalancerMapOutput() SwsLoadBalancerMapOutput {
	return i.ToSwsLoadBalancerMapOutputWithContext(context.Background())
}

func (i SwsLoadBalancerMap) ToSwsLoadBalancerMapOutputWithContext(ctx context.Context) SwsLoadBalancerMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwsLoadBalancerMapOutput)
}

type SwsLoadBalancerOutput struct{ *pulumi.OutputState }

func (SwsLoadBalancerOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SwsLoadBalancer)(nil)).Elem()
}

func (o SwsLoadBalancerOutput) ToSwsLoadBalancerOutput() SwsLoadBalancerOutput {
	return o
}

func (o SwsLoadBalancerOutput) ToSwsLoadBalancerOutputWithContext(ctx context.Context) SwsLoadBalancerOutput {
	return o
}

// Creation time.
func (o SwsLoadBalancerOutput) CreatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.CreatedAt }).(pulumi.StringOutput)
}

// L3-L4 DDoS protection provider. Currently supported: "" or "qrator".
func (o SwsLoadBalancerOutput) DdosProtectionProvider() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.DdosProtectionProvider }).(pulumi.StringOutput)
}

// Forbids Delete() calls.
//
//	NOTE: Deletion in status CREATING still allow even if deletionProtection is set.
func (o SwsLoadBalancerOutput) DeletionProtection() pulumi.BoolOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.BoolOutput { return v.DeletionProtection }).(pulumi.BoolOutput)
}

// Description of the load balancer.
func (o SwsLoadBalancerOutput) Description() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.Description }).(pulumi.StringOutput)
}

// ID of the folder that the load balancer belongs to.
func (o SwsLoadBalancerOutput) FolderId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.FolderId }).(pulumi.StringOutput)
}

// IP address of resulting balancer.
func (o SwsLoadBalancerOutput) IpAddress() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.IpAddress }).(pulumi.StringOutput)
}

// Resource labels as `key:value` pairs.
func (o SwsLoadBalancerOutput) Labels() pulumi.StringMapOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringMapOutput { return v.Labels }).(pulumi.StringMapOutput)
}

// ID of the load balancer to return.
func (o SwsLoadBalancerOutput) LoadBalancerId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.LoadBalancerId }).(pulumi.StringOutput)
}

// Cloud logging log group ID.
//
//	If empty string was passed to log options, this field will contain ID of default log group.
//	If logs are disabled, this field will contain empty string.
func (o SwsLoadBalancerOutput) LogGroupId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.LogGroupId }).(pulumi.StringOutput)
}

// Cloud logging settings.
func (o SwsLoadBalancerOutput) LogOptions() SwsLoadBalancerLogOptionsOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) SwsLoadBalancerLogOptionsOutput { return v.LogOptions }).(SwsLoadBalancerLogOptionsOutput)
}

// Name of the load balancer.
func (o SwsLoadBalancerOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// "ru-central1", "kz1", etc.
func (o SwsLoadBalancerOutput) RegionId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.RegionId }).(pulumi.StringOutput)
}

// Number of initially allocated resource units.
//
//	Zero means the minimum configured for the service installation.
func (o SwsLoadBalancerOutput) ResourceUnits() pulumi.IntOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.IntOutput { return v.ResourceUnits }).(pulumi.IntOutput)
}

// Options that apply to all domains.
func (o SwsLoadBalancerOutput) RouteOptions() SwsLoadBalancerRouteOptionsOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) SwsLoadBalancerRouteOptionsOutput { return v.RouteOptions }).(SwsLoadBalancerRouteOptionsOutput)
}

// Service account for access to certificate, securityProfile and logGroup.
func (o SwsLoadBalancerOutput) ServiceAccountId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.ServiceAccountId }).(pulumi.StringOutput)
}

// Status of the load balancer.
func (o SwsLoadBalancerOutput) Status() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.Status }).(pulumi.StringOutput)
}

// ID of the load balancer to return.
func (o SwsLoadBalancerOutput) SwsLoadBalancerId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.SwsLoadBalancerId }).(pulumi.StringOutput)
}

func (o SwsLoadBalancerOutput) Timeouts() SwsLoadBalancerTimeoutsPtrOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) SwsLoadBalancerTimeoutsPtrOutput { return v.Timeouts }).(SwsLoadBalancerTimeoutsPtrOutput)
}

// Last time when the load balancer was modified.
func (o SwsLoadBalancerOutput) UpdatedAt() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsLoadBalancer) pulumi.StringOutput { return v.UpdatedAt }).(pulumi.StringOutput)
}

type SwsLoadBalancerArrayOutput struct{ *pulumi.OutputState }

func (SwsLoadBalancerArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwsLoadBalancer)(nil)).Elem()
}

func (o SwsLoadBalancerArrayOutput) ToSwsLoadBalancerArrayOutput() SwsLoadBalancerArrayOutput {
	return o
}

func (o SwsLoadBalancerArrayOutput) ToSwsLoadBalancerArrayOutputWithContext(ctx context.Context) SwsLoadBalancerArrayOutput {
	return o
}

func (o SwsLoadBalancerArrayOutput) Index(i pulumi.IntInput) SwsLoadBalancerOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SwsLoadBalancer {
		return vs[0].([]*SwsLoadBalancer)[vs[1].(int)]
	}).(SwsLoadBalancerOutput)
}

type SwsLoadBalancerMapOutput struct{ *pulumi.OutputState }

func (SwsLoadBalancerMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwsLoadBalancer)(nil)).Elem()
}

func (o SwsLoadBalancerMapOutput) ToSwsLoadBalancerMapOutput() SwsLoadBalancerMapOutput {
	return o
}

func (o SwsLoadBalancerMapOutput) ToSwsLoadBalancerMapOutputWithContext(ctx context.Context) SwsLoadBalancerMapOutput {
	return o
}

func (o SwsLoadBalancerMapOutput) MapIndex(k pulumi.StringInput) SwsLoadBalancerOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SwsLoadBalancer {
		return vs[0].(map[string]*SwsLoadBalancer)[vs[1].(string)]
	}).(SwsLoadBalancerOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SwsLoadBalancerInput)(nil)).Elem(), &SwsLoadBalancer{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwsLoadBalancerArrayInput)(nil)).Elem(), SwsLoadBalancerArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwsLoadBalancerMapInput)(nil)).Elem(), SwsLoadBalancerMap{})
	pulumi.RegisterOutputType(SwsLoadBalancerOutput{})
	pulumi.RegisterOutputType(SwsLoadBalancerArrayOutput{})
	pulumi.RegisterOutputType(SwsLoadBalancerMapOutput{})
}
