// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Tracks a WAF rule attachment in a Smart Web Security profile and removes the rule before the WAF profile is deleted. The WAF rule itself must be configured in `SwsSecurityProfile`.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			waf, err := yandex.NewSwsWafProfile(ctx, "waf", &yandex.SwsWafProfileArgs{
//				CoreRuleSet: &yandex.SwsWafProfileCoreRuleSetArgs{
//					InboundAnomalyScore: pulumi.Int(2),
//					ParanoiaLevel:       pulumi.Int(4),
//					RuleSet: &yandex.SwsWafProfileCoreRuleSetRuleSetArgs{
//						Name:    pulumi.String("OWASP Core Ruleset"),
//						Version: pulumi.String("4.0.0"),
//						Type:    pulumi.String("CORE"),
//					},
//				},
//				AnalyzeRequestBody: &yandex.SwsWafProfileAnalyzeRequestBodyArgs{
//					IsEnabled:       pulumi.Bool(true),
//					SizeLimit:       pulumi.Int(8),
//					SizeLimitAction: pulumi.String("IGNORE"),
//				},
//				RuleSets: yandex.SwsWafProfileRuleSetArray{
//					&yandex.SwsWafProfileRuleSetArgs{
//						Action:    pulumi.String("DENY"),
//						IsEnabled: pulumi.Bool(true),
//						Priority:  pulumi.Int(1),
//						CoreRuleSet: &yandex.SwsWafProfileRuleSetCoreRuleSetArgs{
//							InboundAnomalyScore: pulumi.Int(2),
//							ParanoiaLevel:       pulumi.Int(4),
//							RuleSet: &yandex.SwsWafProfileRuleSetCoreRuleSetRuleSetArgs{
//								Name:    pulumi.String("OWASP Core Ruleset"),
//								Version: pulumi.String("4.0.0"),
//								Type:    pulumi.String("CORE"),
//								Id:      pulumi.String("OWASP_CRS_4_0_0"),
//							},
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			securityProfile, err := yandex.NewSwsSecurityProfile(ctx, "securityProfile", &yandex.SwsSecurityProfileArgs{
//				DefaultAction:          pulumi.String("ALLOW"),
//				DisallowDataProcessing: pulumi.Bool(false),
//				SecurityRules: yandex.SwsSecurityProfileSecurityRuleArray{
//					&yandex.SwsSecurityProfileSecurityRuleArgs{
//						Name:     pulumi.String("waf"),
//						Priority: pulumi.Int(1),
//						Waf: &yandex.SwsSecurityProfileSecurityRuleWafArgs{
//							Mode:         pulumi.String("FULL"),
//							WafProfileId: waf.SwsWafProfileId,
//						},
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			_, err = yandex.NewSwsSecurityProfileWafProfileAttachment(ctx, "attachment", &yandex.SwsSecurityProfileWafProfileAttachmentArgs{
//				SecurityProfileId: securityProfile.SwsSecurityProfileId,
//				WafProfileId:      waf.SwsWafProfileId,
//				SecurityRuleName:  pulumi.String("waf"),
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `id` (String).
// - `securityProfileId` (**Required**)(String). ID of the Smart Web Security profile.
// - `securityRuleName` (**Required**)(String). Name of the WAF security rule managed by `SwsSecurityProfile`.
// - `wafProfileId` (**Required**)(String). ID of the WAF profile.
// - `timeouts` [Block].
//   - `create` (String).
//   - `delete` (String).
//   - `read` (String).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// !/bin/bash
//
// ```sh
// $ pulumi import yandex:index/swsSecurityProfileWafProfileAttachment:SwsSecurityProfileWafProfileAttachment attachment '<security_profile_id>/<waf_profile_id>/<security_rule_name>'
// ```
type SwsSecurityProfileWafProfileAttachment struct {
	pulumi.CustomResourceState

	// ID of the Smart Web Security profile.
	SecurityProfileId pulumi.StringOutput `pulumi:"securityProfileId"`
	// Name of the WAF security rule managed by `SwsSecurityProfile`.
	SecurityRuleName pulumi.StringOutput `pulumi:"securityRuleName"`
	// ID of the WAF profile.
	WafProfileId pulumi.StringOutput `pulumi:"wafProfileId"`
}

// NewSwsSecurityProfileWafProfileAttachment registers a new resource with the given unique name, arguments, and options.
func NewSwsSecurityProfileWafProfileAttachment(ctx *pulumi.Context,
	name string, args *SwsSecurityProfileWafProfileAttachmentArgs, opts ...pulumi.ResourceOption) (*SwsSecurityProfileWafProfileAttachment, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.SecurityProfileId == nil {
		return nil, errors.New("invalid value for required argument 'SecurityProfileId'")
	}
	if args.SecurityRuleName == nil {
		return nil, errors.New("invalid value for required argument 'SecurityRuleName'")
	}
	if args.WafProfileId == nil {
		return nil, errors.New("invalid value for required argument 'WafProfileId'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource SwsSecurityProfileWafProfileAttachment
	err := ctx.RegisterResource("yandex:index/swsSecurityProfileWafProfileAttachment:SwsSecurityProfileWafProfileAttachment", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetSwsSecurityProfileWafProfileAttachment gets an existing SwsSecurityProfileWafProfileAttachment resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetSwsSecurityProfileWafProfileAttachment(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *SwsSecurityProfileWafProfileAttachmentState, opts ...pulumi.ResourceOption) (*SwsSecurityProfileWafProfileAttachment, error) {
	var resource SwsSecurityProfileWafProfileAttachment
	err := ctx.ReadResource("yandex:index/swsSecurityProfileWafProfileAttachment:SwsSecurityProfileWafProfileAttachment", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering SwsSecurityProfileWafProfileAttachment resources.
type swsSecurityProfileWafProfileAttachmentState struct {
	// ID of the Smart Web Security profile.
	SecurityProfileId *string `pulumi:"securityProfileId"`
	// Name of the WAF security rule managed by `SwsSecurityProfile`.
	SecurityRuleName *string `pulumi:"securityRuleName"`
	// ID of the WAF profile.
	WafProfileId *string `pulumi:"wafProfileId"`
}

type SwsSecurityProfileWafProfileAttachmentState struct {
	// ID of the Smart Web Security profile.
	SecurityProfileId pulumi.StringPtrInput
	// Name of the WAF security rule managed by `SwsSecurityProfile`.
	SecurityRuleName pulumi.StringPtrInput
	// ID of the WAF profile.
	WafProfileId pulumi.StringPtrInput
}

func (SwsSecurityProfileWafProfileAttachmentState) ElementType() reflect.Type {
	return reflect.TypeOf((*swsSecurityProfileWafProfileAttachmentState)(nil)).Elem()
}

type swsSecurityProfileWafProfileAttachmentArgs struct {
	// ID of the Smart Web Security profile.
	SecurityProfileId string `pulumi:"securityProfileId"`
	// Name of the WAF security rule managed by `SwsSecurityProfile`.
	SecurityRuleName string `pulumi:"securityRuleName"`
	// ID of the WAF profile.
	WafProfileId string `pulumi:"wafProfileId"`
}

// The set of arguments for constructing a SwsSecurityProfileWafProfileAttachment resource.
type SwsSecurityProfileWafProfileAttachmentArgs struct {
	// ID of the Smart Web Security profile.
	SecurityProfileId pulumi.StringInput
	// Name of the WAF security rule managed by `SwsSecurityProfile`.
	SecurityRuleName pulumi.StringInput
	// ID of the WAF profile.
	WafProfileId pulumi.StringInput
}

func (SwsSecurityProfileWafProfileAttachmentArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*swsSecurityProfileWafProfileAttachmentArgs)(nil)).Elem()
}

type SwsSecurityProfileWafProfileAttachmentInput interface {
	pulumi.Input

	ToSwsSecurityProfileWafProfileAttachmentOutput() SwsSecurityProfileWafProfileAttachmentOutput
	ToSwsSecurityProfileWafProfileAttachmentOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentOutput
}

func (*SwsSecurityProfileWafProfileAttachment) ElementType() reflect.Type {
	return reflect.TypeOf((**SwsSecurityProfileWafProfileAttachment)(nil)).Elem()
}

func (i *SwsSecurityProfileWafProfileAttachment) ToSwsSecurityProfileWafProfileAttachmentOutput() SwsSecurityProfileWafProfileAttachmentOutput {
	return i.ToSwsSecurityProfileWafProfileAttachmentOutputWithContext(context.Background())
}

func (i *SwsSecurityProfileWafProfileAttachment) ToSwsSecurityProfileWafProfileAttachmentOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwsSecurityProfileWafProfileAttachmentOutput)
}

// SwsSecurityProfileWafProfileAttachmentArrayInput is an input type that accepts SwsSecurityProfileWafProfileAttachmentArray and SwsSecurityProfileWafProfileAttachmentArrayOutput values.
// You can construct a concrete instance of `SwsSecurityProfileWafProfileAttachmentArrayInput` via:
//
//	SwsSecurityProfileWafProfileAttachmentArray{ SwsSecurityProfileWafProfileAttachmentArgs{...} }
type SwsSecurityProfileWafProfileAttachmentArrayInput interface {
	pulumi.Input

	ToSwsSecurityProfileWafProfileAttachmentArrayOutput() SwsSecurityProfileWafProfileAttachmentArrayOutput
	ToSwsSecurityProfileWafProfileAttachmentArrayOutputWithContext(context.Context) SwsSecurityProfileWafProfileAttachmentArrayOutput
}

type SwsSecurityProfileWafProfileAttachmentArray []SwsSecurityProfileWafProfileAttachmentInput

func (SwsSecurityProfileWafProfileAttachmentArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwsSecurityProfileWafProfileAttachment)(nil)).Elem()
}

func (i SwsSecurityProfileWafProfileAttachmentArray) ToSwsSecurityProfileWafProfileAttachmentArrayOutput() SwsSecurityProfileWafProfileAttachmentArrayOutput {
	return i.ToSwsSecurityProfileWafProfileAttachmentArrayOutputWithContext(context.Background())
}

func (i SwsSecurityProfileWafProfileAttachmentArray) ToSwsSecurityProfileWafProfileAttachmentArrayOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwsSecurityProfileWafProfileAttachmentArrayOutput)
}

// SwsSecurityProfileWafProfileAttachmentMapInput is an input type that accepts SwsSecurityProfileWafProfileAttachmentMap and SwsSecurityProfileWafProfileAttachmentMapOutput values.
// You can construct a concrete instance of `SwsSecurityProfileWafProfileAttachmentMapInput` via:
//
//	SwsSecurityProfileWafProfileAttachmentMap{ "key": SwsSecurityProfileWafProfileAttachmentArgs{...} }
type SwsSecurityProfileWafProfileAttachmentMapInput interface {
	pulumi.Input

	ToSwsSecurityProfileWafProfileAttachmentMapOutput() SwsSecurityProfileWafProfileAttachmentMapOutput
	ToSwsSecurityProfileWafProfileAttachmentMapOutputWithContext(context.Context) SwsSecurityProfileWafProfileAttachmentMapOutput
}

type SwsSecurityProfileWafProfileAttachmentMap map[string]SwsSecurityProfileWafProfileAttachmentInput

func (SwsSecurityProfileWafProfileAttachmentMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwsSecurityProfileWafProfileAttachment)(nil)).Elem()
}

func (i SwsSecurityProfileWafProfileAttachmentMap) ToSwsSecurityProfileWafProfileAttachmentMapOutput() SwsSecurityProfileWafProfileAttachmentMapOutput {
	return i.ToSwsSecurityProfileWafProfileAttachmentMapOutputWithContext(context.Background())
}

func (i SwsSecurityProfileWafProfileAttachmentMap) ToSwsSecurityProfileWafProfileAttachmentMapOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(SwsSecurityProfileWafProfileAttachmentMapOutput)
}

type SwsSecurityProfileWafProfileAttachmentOutput struct{ *pulumi.OutputState }

func (SwsSecurityProfileWafProfileAttachmentOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**SwsSecurityProfileWafProfileAttachment)(nil)).Elem()
}

func (o SwsSecurityProfileWafProfileAttachmentOutput) ToSwsSecurityProfileWafProfileAttachmentOutput() SwsSecurityProfileWafProfileAttachmentOutput {
	return o
}

func (o SwsSecurityProfileWafProfileAttachmentOutput) ToSwsSecurityProfileWafProfileAttachmentOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentOutput {
	return o
}

// ID of the Smart Web Security profile.
func (o SwsSecurityProfileWafProfileAttachmentOutput) SecurityProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsSecurityProfileWafProfileAttachment) pulumi.StringOutput { return v.SecurityProfileId }).(pulumi.StringOutput)
}

// Name of the WAF security rule managed by `SwsSecurityProfile`.
func (o SwsSecurityProfileWafProfileAttachmentOutput) SecurityRuleName() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsSecurityProfileWafProfileAttachment) pulumi.StringOutput { return v.SecurityRuleName }).(pulumi.StringOutput)
}

// ID of the WAF profile.
func (o SwsSecurityProfileWafProfileAttachmentOutput) WafProfileId() pulumi.StringOutput {
	return o.ApplyT(func(v *SwsSecurityProfileWafProfileAttachment) pulumi.StringOutput { return v.WafProfileId }).(pulumi.StringOutput)
}

type SwsSecurityProfileWafProfileAttachmentArrayOutput struct{ *pulumi.OutputState }

func (SwsSecurityProfileWafProfileAttachmentArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*SwsSecurityProfileWafProfileAttachment)(nil)).Elem()
}

func (o SwsSecurityProfileWafProfileAttachmentArrayOutput) ToSwsSecurityProfileWafProfileAttachmentArrayOutput() SwsSecurityProfileWafProfileAttachmentArrayOutput {
	return o
}

func (o SwsSecurityProfileWafProfileAttachmentArrayOutput) ToSwsSecurityProfileWafProfileAttachmentArrayOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentArrayOutput {
	return o
}

func (o SwsSecurityProfileWafProfileAttachmentArrayOutput) Index(i pulumi.IntInput) SwsSecurityProfileWafProfileAttachmentOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *SwsSecurityProfileWafProfileAttachment {
		return vs[0].([]*SwsSecurityProfileWafProfileAttachment)[vs[1].(int)]
	}).(SwsSecurityProfileWafProfileAttachmentOutput)
}

type SwsSecurityProfileWafProfileAttachmentMapOutput struct{ *pulumi.OutputState }

func (SwsSecurityProfileWafProfileAttachmentMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*SwsSecurityProfileWafProfileAttachment)(nil)).Elem()
}

func (o SwsSecurityProfileWafProfileAttachmentMapOutput) ToSwsSecurityProfileWafProfileAttachmentMapOutput() SwsSecurityProfileWafProfileAttachmentMapOutput {
	return o
}

func (o SwsSecurityProfileWafProfileAttachmentMapOutput) ToSwsSecurityProfileWafProfileAttachmentMapOutputWithContext(ctx context.Context) SwsSecurityProfileWafProfileAttachmentMapOutput {
	return o
}

func (o SwsSecurityProfileWafProfileAttachmentMapOutput) MapIndex(k pulumi.StringInput) SwsSecurityProfileWafProfileAttachmentOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *SwsSecurityProfileWafProfileAttachment {
		return vs[0].(map[string]*SwsSecurityProfileWafProfileAttachment)[vs[1].(string)]
	}).(SwsSecurityProfileWafProfileAttachmentOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*SwsSecurityProfileWafProfileAttachmentInput)(nil)).Elem(), &SwsSecurityProfileWafProfileAttachment{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwsSecurityProfileWafProfileAttachmentArrayInput)(nil)).Elem(), SwsSecurityProfileWafProfileAttachmentArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*SwsSecurityProfileWafProfileAttachmentMapInput)(nil)).Elem(), SwsSecurityProfileWafProfileAttachmentMap{})
	pulumi.RegisterOutputType(SwsSecurityProfileWafProfileAttachmentOutput{})
	pulumi.RegisterOutputType(SwsSecurityProfileWafProfileAttachmentArrayOutput{})
	pulumi.RegisterOutputType(SwsSecurityProfileWafProfileAttachmentMapOutput{})
}
