// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Manage a YDB Topic. For more information, see [the official documentation](https://yandex.cloud/docs/ydb/concepts/#ydb).
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			databaseName, err := yandex.NewYdbDatabaseServerless(ctx, "databaseName", &yandex.YdbDatabaseServerlessArgs{
//				LocationId: pulumi.String("ru-central1"),
//			})
//			if err != nil {
//				return err
//			}
//			// Create a new YDB Topic.
//			_, err = yandex.NewYdbTopic(ctx, "myTopic", &yandex.YdbTopicArgs{
//				DatabaseEndpoint: databaseName.YdbFullEndpoint,
//				SupportedCodecs: pulumi.StringArray{
//					pulumi.String("raw"),
//					pulumi.String("gzip"),
//				},
//				PartitionsCount:   pulumi.Int(1),
//				RetentionPeriodMs: 2000000,
//				Consumers: yandex.YdbTopicConsumerArray{
//					&yandex.YdbTopicConsumerArgs{
//						Name: pulumi.String("consumer-name"),
//						SupportedCodecs: pulumi.StringArray{
//							pulumi.String("raw"),
//							pulumi.String("gzip"),
//						},
//						StartingMessageTimestampMs: pulumi.Int(0),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `databaseEndpoint` (**Required**)(String). YDB database endpoint.
// - `description` (String). Topic description.
// - `id` (String).
// - `maxPartitionsCount` (Number). Number of max active partitions. Default value `1`.
// - `meteringMode` (String). Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
// - `name` (**Required**)(String). Topic name.
// - `partitionWriteSpeedKbps` (Number). Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
// - `partitionsCount` (Number). Number of min partitions. Default value `1`.
// - `retentionPeriodHours` (Number). Data retention time. Default value `86400000`.
// - `retentionStorageMb` (Number).
// - `supportedCodecs` (Set Of String). Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
// - `autoPartitioningSettings` [Block].
//   - `autoPartitioningStrategy` (String). The auto partitioning strategy to use
//   - `autoPartitioningWriteSpeedStrategy` [Block].
//   - `downUtilizationPercent` (Number). The down utilization percentage threshold
//   - `stabilizationWindow` (Number). The stabilization window in seconds
//   - `upUtilizationPercent` (Number). The up utilization percentage threshold
//
// - `consumer` [Block]. Topic Readers.
//   - `important` (Bool). Defines an important consumer. No data will be deleted from the topic until all the important consumers read them. Default value `false`.
//   - `name` (**Required**)(String). Reader's name.
//   - `startingMessageTimestampMs` (Number). Timestamp in UNIX timestamp format from which the reader will start reading data. Default value `0`.
//   - `supportedCodecs` (Set Of String). Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
//
// - `timeouts` [Block].
//   - `create` (String).
//   - `default` (String).
//   - `delete` (String).
//   - `read` (String).
//   - `update` (String).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_ydb_topic.<resource Name> <resource Id>
//
// ```sh
// $ pulumi import yandex:index/ydbTopic:YdbTopic my_topic ...
// ```
type YdbTopic struct {
	pulumi.CustomResourceState

	AutoPartitioningSettings YdbTopicAutoPartitioningSettingsOutput `pulumi:"autoPartitioningSettings"`
	// Topic Readers.
	Consumers YdbTopicConsumerArrayOutput `pulumi:"consumers"`
	// YDB database endpoint.
	DatabaseEndpoint pulumi.StringOutput `pulumi:"databaseEndpoint"`
	// Topic description.
	Description pulumi.StringPtrOutput `pulumi:"description"`
	// Number of max active partitions. Default value `1`.
	MaxPartitionsCount pulumi.IntOutput `pulumi:"maxPartitionsCount"`
	// Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
	MeteringMode pulumi.StringOutput `pulumi:"meteringMode"`
	// Topic name.
	Name pulumi.StringOutput `pulumi:"name"`
	// Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
	PartitionWriteSpeedKbps pulumi.IntOutput `pulumi:"partitionWriteSpeedKbps"`
	// Number of min partitions. Default value `1`.
	PartitionsCount pulumi.IntOutput `pulumi:"partitionsCount"`
	// Data retention time. Default value `86400000`.
	RetentionPeriodHours pulumi.IntOutput `pulumi:"retentionPeriodHours"`
	RetentionStorageMb   pulumi.IntOutput `pulumi:"retentionStorageMb"`
	// Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
	SupportedCodecs pulumi.StringArrayOutput `pulumi:"supportedCodecs"`
}

// NewYdbTopic registers a new resource with the given unique name, arguments, and options.
func NewYdbTopic(ctx *pulumi.Context,
	name string, args *YdbTopicArgs, opts ...pulumi.ResourceOption) (*YdbTopic, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.DatabaseEndpoint == nil {
		return nil, errors.New("invalid value for required argument 'DatabaseEndpoint'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource YdbTopic
	err := ctx.RegisterResource("yandex:index/ydbTopic:YdbTopic", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetYdbTopic gets an existing YdbTopic resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetYdbTopic(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *YdbTopicState, opts ...pulumi.ResourceOption) (*YdbTopic, error) {
	var resource YdbTopic
	err := ctx.ReadResource("yandex:index/ydbTopic:YdbTopic", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering YdbTopic resources.
type ydbTopicState struct {
	AutoPartitioningSettings *YdbTopicAutoPartitioningSettings `pulumi:"autoPartitioningSettings"`
	// Topic Readers.
	Consumers []YdbTopicConsumer `pulumi:"consumers"`
	// YDB database endpoint.
	DatabaseEndpoint *string `pulumi:"databaseEndpoint"`
	// Topic description.
	Description *string `pulumi:"description"`
	// Number of max active partitions. Default value `1`.
	MaxPartitionsCount *int `pulumi:"maxPartitionsCount"`
	// Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
	MeteringMode *string `pulumi:"meteringMode"`
	// Topic name.
	Name *string `pulumi:"name"`
	// Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
	PartitionWriteSpeedKbps *int `pulumi:"partitionWriteSpeedKbps"`
	// Number of min partitions. Default value `1`.
	PartitionsCount *int `pulumi:"partitionsCount"`
	// Data retention time. Default value `86400000`.
	RetentionPeriodHours *int `pulumi:"retentionPeriodHours"`
	RetentionStorageMb   *int `pulumi:"retentionStorageMb"`
	// Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
	SupportedCodecs []string `pulumi:"supportedCodecs"`
}

type YdbTopicState struct {
	AutoPartitioningSettings YdbTopicAutoPartitioningSettingsPtrInput
	// Topic Readers.
	Consumers YdbTopicConsumerArrayInput
	// YDB database endpoint.
	DatabaseEndpoint pulumi.StringPtrInput
	// Topic description.
	Description pulumi.StringPtrInput
	// Number of max active partitions. Default value `1`.
	MaxPartitionsCount pulumi.IntPtrInput
	// Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
	MeteringMode pulumi.StringPtrInput
	// Topic name.
	Name pulumi.StringPtrInput
	// Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
	PartitionWriteSpeedKbps pulumi.IntPtrInput
	// Number of min partitions. Default value `1`.
	PartitionsCount pulumi.IntPtrInput
	// Data retention time. Default value `86400000`.
	RetentionPeriodHours pulumi.IntPtrInput
	RetentionStorageMb   pulumi.IntPtrInput
	// Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
	SupportedCodecs pulumi.StringArrayInput
}

func (YdbTopicState) ElementType() reflect.Type {
	return reflect.TypeOf((*ydbTopicState)(nil)).Elem()
}

type ydbTopicArgs struct {
	AutoPartitioningSettings *YdbTopicAutoPartitioningSettings `pulumi:"autoPartitioningSettings"`
	// Topic Readers.
	Consumers []YdbTopicConsumer `pulumi:"consumers"`
	// YDB database endpoint.
	DatabaseEndpoint string `pulumi:"databaseEndpoint"`
	// Topic description.
	Description *string `pulumi:"description"`
	// Number of max active partitions. Default value `1`.
	MaxPartitionsCount *int `pulumi:"maxPartitionsCount"`
	// Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
	MeteringMode *string `pulumi:"meteringMode"`
	// Topic name.
	Name *string `pulumi:"name"`
	// Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
	PartitionWriteSpeedKbps *int `pulumi:"partitionWriteSpeedKbps"`
	// Number of min partitions. Default value `1`.
	PartitionsCount *int `pulumi:"partitionsCount"`
	// Data retention time. Default value `86400000`.
	RetentionPeriodHours *int `pulumi:"retentionPeriodHours"`
	RetentionStorageMb   *int `pulumi:"retentionStorageMb"`
	// Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
	SupportedCodecs []string `pulumi:"supportedCodecs"`
}

// The set of arguments for constructing a YdbTopic resource.
type YdbTopicArgs struct {
	AutoPartitioningSettings YdbTopicAutoPartitioningSettingsPtrInput
	// Topic Readers.
	Consumers YdbTopicConsumerArrayInput
	// YDB database endpoint.
	DatabaseEndpoint pulumi.StringInput
	// Topic description.
	Description pulumi.StringPtrInput
	// Number of max active partitions. Default value `1`.
	MaxPartitionsCount pulumi.IntPtrInput
	// Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
	MeteringMode pulumi.StringPtrInput
	// Topic name.
	Name pulumi.StringPtrInput
	// Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
	PartitionWriteSpeedKbps pulumi.IntPtrInput
	// Number of min partitions. Default value `1`.
	PartitionsCount pulumi.IntPtrInput
	// Data retention time. Default value `86400000`.
	RetentionPeriodHours pulumi.IntPtrInput
	RetentionStorageMb   pulumi.IntPtrInput
	// Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
	SupportedCodecs pulumi.StringArrayInput
}

func (YdbTopicArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ydbTopicArgs)(nil)).Elem()
}

type YdbTopicInput interface {
	pulumi.Input

	ToYdbTopicOutput() YdbTopicOutput
	ToYdbTopicOutputWithContext(ctx context.Context) YdbTopicOutput
}

func (*YdbTopic) ElementType() reflect.Type {
	return reflect.TypeOf((**YdbTopic)(nil)).Elem()
}

func (i *YdbTopic) ToYdbTopicOutput() YdbTopicOutput {
	return i.ToYdbTopicOutputWithContext(context.Background())
}

func (i *YdbTopic) ToYdbTopicOutputWithContext(ctx context.Context) YdbTopicOutput {
	return pulumi.ToOutputWithContext(ctx, i).(YdbTopicOutput)
}

// YdbTopicArrayInput is an input type that accepts YdbTopicArray and YdbTopicArrayOutput values.
// You can construct a concrete instance of `YdbTopicArrayInput` via:
//
//	YdbTopicArray{ YdbTopicArgs{...} }
type YdbTopicArrayInput interface {
	pulumi.Input

	ToYdbTopicArrayOutput() YdbTopicArrayOutput
	ToYdbTopicArrayOutputWithContext(context.Context) YdbTopicArrayOutput
}

type YdbTopicArray []YdbTopicInput

func (YdbTopicArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*YdbTopic)(nil)).Elem()
}

func (i YdbTopicArray) ToYdbTopicArrayOutput() YdbTopicArrayOutput {
	return i.ToYdbTopicArrayOutputWithContext(context.Background())
}

func (i YdbTopicArray) ToYdbTopicArrayOutputWithContext(ctx context.Context) YdbTopicArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(YdbTopicArrayOutput)
}

// YdbTopicMapInput is an input type that accepts YdbTopicMap and YdbTopicMapOutput values.
// You can construct a concrete instance of `YdbTopicMapInput` via:
//
//	YdbTopicMap{ "key": YdbTopicArgs{...} }
type YdbTopicMapInput interface {
	pulumi.Input

	ToYdbTopicMapOutput() YdbTopicMapOutput
	ToYdbTopicMapOutputWithContext(context.Context) YdbTopicMapOutput
}

type YdbTopicMap map[string]YdbTopicInput

func (YdbTopicMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*YdbTopic)(nil)).Elem()
}

func (i YdbTopicMap) ToYdbTopicMapOutput() YdbTopicMapOutput {
	return i.ToYdbTopicMapOutputWithContext(context.Background())
}

func (i YdbTopicMap) ToYdbTopicMapOutputWithContext(ctx context.Context) YdbTopicMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(YdbTopicMapOutput)
}

type YdbTopicOutput struct{ *pulumi.OutputState }

func (YdbTopicOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**YdbTopic)(nil)).Elem()
}

func (o YdbTopicOutput) ToYdbTopicOutput() YdbTopicOutput {
	return o
}

func (o YdbTopicOutput) ToYdbTopicOutputWithContext(ctx context.Context) YdbTopicOutput {
	return o
}

func (o YdbTopicOutput) AutoPartitioningSettings() YdbTopicAutoPartitioningSettingsOutput {
	return o.ApplyT(func(v *YdbTopic) YdbTopicAutoPartitioningSettingsOutput { return v.AutoPartitioningSettings }).(YdbTopicAutoPartitioningSettingsOutput)
}

// Topic Readers.
func (o YdbTopicOutput) Consumers() YdbTopicConsumerArrayOutput {
	return o.ApplyT(func(v *YdbTopic) YdbTopicConsumerArrayOutput { return v.Consumers }).(YdbTopicConsumerArrayOutput)
}

// YDB database endpoint.
func (o YdbTopicOutput) DatabaseEndpoint() pulumi.StringOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.StringOutput { return v.DatabaseEndpoint }).(pulumi.StringOutput)
}

// Topic description.
func (o YdbTopicOutput) Description() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.StringPtrOutput { return v.Description }).(pulumi.StringPtrOutput)
}

// Number of max active partitions. Default value `1`.
func (o YdbTopicOutput) MaxPartitionsCount() pulumi.IntOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.IntOutput { return v.MaxPartitionsCount }).(pulumi.IntOutput)
}

// Resource metering mode (`reservedCapacity` - based on the allocated resources or `requestUnits` - based on actual usage). This option applies to topics in serverless databases.
func (o YdbTopicOutput) MeteringMode() pulumi.StringOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.StringOutput { return v.MeteringMode }).(pulumi.StringOutput)
}

// Topic name.
func (o YdbTopicOutput) Name() pulumi.StringOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.StringOutput { return v.Name }).(pulumi.StringOutput)
}

// Maximum allowed write speed per partition. If a write speed for a given partition exceeds this value, the write speed will be capped. Default value: `1024 (1MB)`.
func (o YdbTopicOutput) PartitionWriteSpeedKbps() pulumi.IntOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.IntOutput { return v.PartitionWriteSpeedKbps }).(pulumi.IntOutput)
}

// Number of min partitions. Default value `1`.
func (o YdbTopicOutput) PartitionsCount() pulumi.IntOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.IntOutput { return v.PartitionsCount }).(pulumi.IntOutput)
}

// Data retention time. Default value `86400000`.
func (o YdbTopicOutput) RetentionPeriodHours() pulumi.IntOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.IntOutput { return v.RetentionPeriodHours }).(pulumi.IntOutput)
}

func (o YdbTopicOutput) RetentionStorageMb() pulumi.IntOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.IntOutput { return v.RetentionStorageMb }).(pulumi.IntOutput)
}

// Supported data encodings. Can be one of `gzip`, `raw` or `zstd`.
func (o YdbTopicOutput) SupportedCodecs() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *YdbTopic) pulumi.StringArrayOutput { return v.SupportedCodecs }).(pulumi.StringArrayOutput)
}

type YdbTopicArrayOutput struct{ *pulumi.OutputState }

func (YdbTopicArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*YdbTopic)(nil)).Elem()
}

func (o YdbTopicArrayOutput) ToYdbTopicArrayOutput() YdbTopicArrayOutput {
	return o
}

func (o YdbTopicArrayOutput) ToYdbTopicArrayOutputWithContext(ctx context.Context) YdbTopicArrayOutput {
	return o
}

func (o YdbTopicArrayOutput) Index(i pulumi.IntInput) YdbTopicOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *YdbTopic {
		return vs[0].([]*YdbTopic)[vs[1].(int)]
	}).(YdbTopicOutput)
}

type YdbTopicMapOutput struct{ *pulumi.OutputState }

func (YdbTopicMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*YdbTopic)(nil)).Elem()
}

func (o YdbTopicMapOutput) ToYdbTopicMapOutput() YdbTopicMapOutput {
	return o
}

func (o YdbTopicMapOutput) ToYdbTopicMapOutputWithContext(ctx context.Context) YdbTopicMapOutput {
	return o
}

func (o YdbTopicMapOutput) MapIndex(k pulumi.StringInput) YdbTopicOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *YdbTopic {
		return vs[0].(map[string]*YdbTopic)[vs[1].(string)]
	}).(YdbTopicOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*YdbTopicInput)(nil)).Elem(), &YdbTopic{})
	pulumi.RegisterInputType(reflect.TypeOf((*YdbTopicArrayInput)(nil)).Elem(), YdbTopicArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*YdbTopicMapInput)(nil)).Elem(), YdbTopicMap{})
	pulumi.RegisterOutputType(YdbTopicOutput{})
	pulumi.RegisterOutputType(YdbTopicArrayOutput{})
	pulumi.RegisterOutputType(YdbTopicMapOutput{})
}
