// Code generated by pulumi-language-go DO NOT EDIT.
// *** WARNING: Do not edit by hand unless you're certain you know what you are doing! ***

package yandex

import (
	"context"
	"reflect"

	"errors"
	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex/internal"
)

// Yandex Database table.
//
// ## Example Usage
//
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new row-oriented YDB Table.
//			_, err := yandex.NewYdbTable(ctx, "testTable", &yandex.YdbTableArgs{
//				Path:             pulumi.String("test_dir/test_table_3_col"),
//				ConnectionString: pulumi.Any(yandex_ydb_database_serverless.Database1.Ydb_full_endpoint),
//				Columns: yandex.YdbTableColumnArray{
//					&yandex.YdbTableColumnArgs{
//						Name:    pulumi.String("a"),
//						Type:    pulumi.String("Utf8"),
//						NotNull: pulumi.Bool(true),
//					},
//					&yandex.YdbTableColumnArgs{
//						Name:    pulumi.String("b"),
//						Type:    pulumi.String("Uint32"),
//						NotNull: pulumi.Bool(true),
//					},
//					&yandex.YdbTableColumnArgs{
//						Name:    pulumi.String("c"),
//						Type:    pulumi.String("Int32"),
//						NotNull: pulumi.Bool(false),
//					},
//					&yandex.YdbTableColumnArgs{
//						Name: pulumi.String("d"),
//						Type: pulumi.String("Timestamp"),
//					},
//				},
//				PrimaryKeys: pulumi.StringArray{
//					pulumi.String("a"),
//					pulumi.String("b"),
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
// ```go
// package main
//
// import (
//
//	"github.com/pulumi/pulumi/sdk/v3/go/pulumi"
//	"github.com/simple-container-com/pulumi-yandex/sdk/go/yandex"
//
// )
//
//	func main() {
//		pulumi.Run(func(ctx *pulumi.Context) error {
//			// Create a new column-oriented YDB Table.
//			_, err := yandex.NewYdbTable(ctx, "testTable", &yandex.YdbTableArgs{
//				Path:             pulumi.String("test_dir/test_table_3_col"),
//				ConnectionString: pulumi.Any(yandex_ydb_database_serverless.Database1.Ydb_full_endpoint),
//				Columns: yandex.YdbTableColumnArray{
//					&yandex.YdbTableColumnArgs{
//						Name:    pulumi.String("a"),
//						Type:    pulumi.String("Utf8"),
//						NotNull: pulumi.Bool(true),
//					},
//					&yandex.YdbTableColumnArgs{
//						Name:    pulumi.String("b"),
//						Type:    pulumi.String("Uint32"),
//						NotNull: pulumi.Bool(true),
//					},
//					&yandex.YdbTableColumnArgs{
//						Name:    pulumi.String("c"),
//						Type:    pulumi.String("Int32"),
//						NotNull: pulumi.Bool(false),
//					},
//					&yandex.YdbTableColumnArgs{
//						Name: pulumi.String("d"),
//						Type: pulumi.String("Timestamp"),
//					},
//				},
//				PrimaryKeys: pulumi.StringArray{
//					pulumi.String("a"),
//					pulumi.String("b"),
//				},
//				Store: pulumi.String("column"),
//				PartitioningSettings: &yandex.YdbTablePartitioningSettingsArgs{
//					PartitionBies: pulumi.StringArray{
//						pulumi.String("b"),
//						pulumi.String("a"),
//					},
//				},
//			})
//			if err != nil {
//				return err
//			}
//			return nil
//		})
//	}
//
// ```
//
// ## Arguments & Attributes Reference
//
// - `attributes` (Map Of String). A map of table attributes.
// - `connectionString` (**Required**)(String). Connection string for database.
// - `id` (String).
// - `keyBloomFilter` (Bool). Use the Bloom filter for the primary key.
// - `path` (**Required**)(String). Table path.
// - `primaryKey` (**Required**)(List Of String). A list of table columns to be used as primary key.
// - `readReplicasSettings` (String). Read replication settings.
// - `store` (String). Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
// - `column` [Block]. A list of column configuration options.
//   - `family` (String). Column group.
//   - `name` (**Required**)(String). Column name.
//   - `notNull` (Bool). A column cannot have the NULL data type. Default: `false`.
//   - `type` (**Required**)(String). Column data type. YQL data types are used.
//
// - `family` [Block]. A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
//   - `compression` (**Required**)(String). Data codec (acceptable values: off, lz4).
//   - `data` (**Required**)(String). Type of storage device for column data in this group (acceptable values: ssd, rot (from HDD spindle rotation)).
//   - `name` (**Required**)(String). Column family name.
//
// - `partitioningSettings` [Block]. Table partitioning settings.
//   - `autoPartitioningByLoad` (Bool).
//   - `autoPartitioningBySizeEnabled` (Bool).
//   - `autoPartitioningMaxPartitionsCount` (Number).
//   - `autoPartitioningMinPartitionsCount` (Number).
//   - `autoPartitioningPartitionSizeMb` (Number).
//   - `partitionBy` (List Of String). Partitioning keys constitute a subset of the table's primary keys. If not set, primary keys will be used.
//   - `uniformPartitions` (Number).
//   - `partitionAtKeys` [Block].
//   - `keys` (**Required**)(List Of String).
//
// - `timeouts` [Block].
//   - `create` (String).
//   - `default` (String).
//   - `delete` (String).
//   - `read` (String).
//   - `update` (String).
//
// - `ttl` [Block]. The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
//   - `columnName` (**Required**)(String). Column name for TTL.
//   - `expireInterval` (**Required**)(String). Interval in the ISO 8601 format.
//   - `unit` (String).
//
// ## Import
//
// The resource can be imported by using their `resource ID`. For getting it you can use Yandex Cloud [Web Console](https://console.yandex.cloud) or Yandex Cloud [CLI](https://yandex.cloud/docs/cli/quickstart).
//
// terraform import yandex_ydb_table.<resource Name> <resource Id>
//
// ```sh
// $ pulumi import yandex:index/ydbTable:YdbTable test_table ...
// ```
type YdbTable struct {
	pulumi.CustomResourceState

	// A map of table attributes.
	Attributes pulumi.StringMapOutput `pulumi:"attributes"`
	// A list of column configuration options.
	Columns YdbTableColumnArrayOutput `pulumi:"columns"`
	// Connection string for database.
	ConnectionString pulumi.StringOutput `pulumi:"connectionString"`
	// A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
	Families YdbTableFamilyArrayOutput `pulumi:"families"`
	// Use the Bloom filter for the primary key.
	KeyBloomFilter pulumi.BoolOutput `pulumi:"keyBloomFilter"`
	// Table partitioning settings.
	PartitioningSettings YdbTablePartitioningSettingsOutput `pulumi:"partitioningSettings"`
	// Table path.
	Path pulumi.StringOutput `pulumi:"path"`
	// A list of table columns to be used as primary key.
	PrimaryKeys pulumi.StringArrayOutput `pulumi:"primaryKeys"`
	// Read replication settings.
	ReadReplicasSettings pulumi.StringOutput `pulumi:"readReplicasSettings"`
	// Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
	Store pulumi.StringPtrOutput `pulumi:"store"`
	// The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
	Ttl YdbTableTtlPtrOutput `pulumi:"ttl"`
}

// NewYdbTable registers a new resource with the given unique name, arguments, and options.
func NewYdbTable(ctx *pulumi.Context,
	name string, args *YdbTableArgs, opts ...pulumi.ResourceOption) (*YdbTable, error) {
	if args == nil {
		return nil, errors.New("missing one or more required arguments")
	}

	if args.Columns == nil {
		return nil, errors.New("invalid value for required argument 'Columns'")
	}
	if args.ConnectionString == nil {
		return nil, errors.New("invalid value for required argument 'ConnectionString'")
	}
	if args.Path == nil {
		return nil, errors.New("invalid value for required argument 'Path'")
	}
	if args.PrimaryKeys == nil {
		return nil, errors.New("invalid value for required argument 'PrimaryKeys'")
	}
	opts = internal.PkgResourceDefaultOpts(opts)
	var resource YdbTable
	err := ctx.RegisterResource("yandex:index/ydbTable:YdbTable", name, args, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// GetYdbTable gets an existing YdbTable resource's state with the given name, ID, and optional
// state properties that are used to uniquely qualify the lookup (nil if not required).
func GetYdbTable(ctx *pulumi.Context,
	name string, id pulumi.IDInput, state *YdbTableState, opts ...pulumi.ResourceOption) (*YdbTable, error) {
	var resource YdbTable
	err := ctx.ReadResource("yandex:index/ydbTable:YdbTable", name, id, state, &resource, opts...)
	if err != nil {
		return nil, err
	}
	return &resource, nil
}

// Input properties used for looking up and filtering YdbTable resources.
type ydbTableState struct {
	// A map of table attributes.
	Attributes map[string]string `pulumi:"attributes"`
	// A list of column configuration options.
	Columns []YdbTableColumn `pulumi:"columns"`
	// Connection string for database.
	ConnectionString *string `pulumi:"connectionString"`
	// A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
	Families []YdbTableFamily `pulumi:"families"`
	// Use the Bloom filter for the primary key.
	KeyBloomFilter *bool `pulumi:"keyBloomFilter"`
	// Table partitioning settings.
	PartitioningSettings *YdbTablePartitioningSettings `pulumi:"partitioningSettings"`
	// Table path.
	Path *string `pulumi:"path"`
	// A list of table columns to be used as primary key.
	PrimaryKeys []string `pulumi:"primaryKeys"`
	// Read replication settings.
	ReadReplicasSettings *string `pulumi:"readReplicasSettings"`
	// Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
	Store *string `pulumi:"store"`
	// The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
	Ttl *YdbTableTtl `pulumi:"ttl"`
}

type YdbTableState struct {
	// A map of table attributes.
	Attributes pulumi.StringMapInput
	// A list of column configuration options.
	Columns YdbTableColumnArrayInput
	// Connection string for database.
	ConnectionString pulumi.StringPtrInput
	// A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
	Families YdbTableFamilyArrayInput
	// Use the Bloom filter for the primary key.
	KeyBloomFilter pulumi.BoolPtrInput
	// Table partitioning settings.
	PartitioningSettings YdbTablePartitioningSettingsPtrInput
	// Table path.
	Path pulumi.StringPtrInput
	// A list of table columns to be used as primary key.
	PrimaryKeys pulumi.StringArrayInput
	// Read replication settings.
	ReadReplicasSettings pulumi.StringPtrInput
	// Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
	Store pulumi.StringPtrInput
	// The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
	Ttl YdbTableTtlPtrInput
}

func (YdbTableState) ElementType() reflect.Type {
	return reflect.TypeOf((*ydbTableState)(nil)).Elem()
}

type ydbTableArgs struct {
	// A map of table attributes.
	Attributes map[string]string `pulumi:"attributes"`
	// A list of column configuration options.
	Columns []YdbTableColumn `pulumi:"columns"`
	// Connection string for database.
	ConnectionString string `pulumi:"connectionString"`
	// A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
	Families []YdbTableFamily `pulumi:"families"`
	// Use the Bloom filter for the primary key.
	KeyBloomFilter *bool `pulumi:"keyBloomFilter"`
	// Table partitioning settings.
	PartitioningSettings *YdbTablePartitioningSettings `pulumi:"partitioningSettings"`
	// Table path.
	Path string `pulumi:"path"`
	// A list of table columns to be used as primary key.
	PrimaryKeys []string `pulumi:"primaryKeys"`
	// Read replication settings.
	ReadReplicasSettings *string `pulumi:"readReplicasSettings"`
	// Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
	Store *string `pulumi:"store"`
	// The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
	Ttl *YdbTableTtl `pulumi:"ttl"`
}

// The set of arguments for constructing a YdbTable resource.
type YdbTableArgs struct {
	// A map of table attributes.
	Attributes pulumi.StringMapInput
	// A list of column configuration options.
	Columns YdbTableColumnArrayInput
	// Connection string for database.
	ConnectionString pulumi.StringInput
	// A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
	Families YdbTableFamilyArrayInput
	// Use the Bloom filter for the primary key.
	KeyBloomFilter pulumi.BoolPtrInput
	// Table partitioning settings.
	PartitioningSettings YdbTablePartitioningSettingsPtrInput
	// Table path.
	Path pulumi.StringInput
	// A list of table columns to be used as primary key.
	PrimaryKeys pulumi.StringArrayInput
	// Read replication settings.
	ReadReplicasSettings pulumi.StringPtrInput
	// Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
	Store pulumi.StringPtrInput
	// The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
	Ttl YdbTableTtlPtrInput
}

func (YdbTableArgs) ElementType() reflect.Type {
	return reflect.TypeOf((*ydbTableArgs)(nil)).Elem()
}

type YdbTableInput interface {
	pulumi.Input

	ToYdbTableOutput() YdbTableOutput
	ToYdbTableOutputWithContext(ctx context.Context) YdbTableOutput
}

func (*YdbTable) ElementType() reflect.Type {
	return reflect.TypeOf((**YdbTable)(nil)).Elem()
}

func (i *YdbTable) ToYdbTableOutput() YdbTableOutput {
	return i.ToYdbTableOutputWithContext(context.Background())
}

func (i *YdbTable) ToYdbTableOutputWithContext(ctx context.Context) YdbTableOutput {
	return pulumi.ToOutputWithContext(ctx, i).(YdbTableOutput)
}

// YdbTableArrayInput is an input type that accepts YdbTableArray and YdbTableArrayOutput values.
// You can construct a concrete instance of `YdbTableArrayInput` via:
//
//	YdbTableArray{ YdbTableArgs{...} }
type YdbTableArrayInput interface {
	pulumi.Input

	ToYdbTableArrayOutput() YdbTableArrayOutput
	ToYdbTableArrayOutputWithContext(context.Context) YdbTableArrayOutput
}

type YdbTableArray []YdbTableInput

func (YdbTableArray) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*YdbTable)(nil)).Elem()
}

func (i YdbTableArray) ToYdbTableArrayOutput() YdbTableArrayOutput {
	return i.ToYdbTableArrayOutputWithContext(context.Background())
}

func (i YdbTableArray) ToYdbTableArrayOutputWithContext(ctx context.Context) YdbTableArrayOutput {
	return pulumi.ToOutputWithContext(ctx, i).(YdbTableArrayOutput)
}

// YdbTableMapInput is an input type that accepts YdbTableMap and YdbTableMapOutput values.
// You can construct a concrete instance of `YdbTableMapInput` via:
//
//	YdbTableMap{ "key": YdbTableArgs{...} }
type YdbTableMapInput interface {
	pulumi.Input

	ToYdbTableMapOutput() YdbTableMapOutput
	ToYdbTableMapOutputWithContext(context.Context) YdbTableMapOutput
}

type YdbTableMap map[string]YdbTableInput

func (YdbTableMap) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*YdbTable)(nil)).Elem()
}

func (i YdbTableMap) ToYdbTableMapOutput() YdbTableMapOutput {
	return i.ToYdbTableMapOutputWithContext(context.Background())
}

func (i YdbTableMap) ToYdbTableMapOutputWithContext(ctx context.Context) YdbTableMapOutput {
	return pulumi.ToOutputWithContext(ctx, i).(YdbTableMapOutput)
}

type YdbTableOutput struct{ *pulumi.OutputState }

func (YdbTableOutput) ElementType() reflect.Type {
	return reflect.TypeOf((**YdbTable)(nil)).Elem()
}

func (o YdbTableOutput) ToYdbTableOutput() YdbTableOutput {
	return o
}

func (o YdbTableOutput) ToYdbTableOutputWithContext(ctx context.Context) YdbTableOutput {
	return o
}

// A map of table attributes.
func (o YdbTableOutput) Attributes() pulumi.StringMapOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.StringMapOutput { return v.Attributes }).(pulumi.StringMapOutput)
}

// A list of column configuration options.
func (o YdbTableOutput) Columns() YdbTableColumnArrayOutput {
	return o.ApplyT(func(v *YdbTable) YdbTableColumnArrayOutput { return v.Columns }).(YdbTableColumnArrayOutput)
}

// Connection string for database.
func (o YdbTableOutput) ConnectionString() pulumi.StringOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.StringOutput { return v.ConnectionString }).(pulumi.StringOutput)
}

// A list of column group configuration options. The `family` block may be used to group columns into [families](https://ydb.tech/en/docs/yql/reference/syntax/create_table#column-family) to set shared parameters for them.
func (o YdbTableOutput) Families() YdbTableFamilyArrayOutput {
	return o.ApplyT(func(v *YdbTable) YdbTableFamilyArrayOutput { return v.Families }).(YdbTableFamilyArrayOutput)
}

// Use the Bloom filter for the primary key.
func (o YdbTableOutput) KeyBloomFilter() pulumi.BoolOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.BoolOutput { return v.KeyBloomFilter }).(pulumi.BoolOutput)
}

// Table partitioning settings.
func (o YdbTableOutput) PartitioningSettings() YdbTablePartitioningSettingsOutput {
	return o.ApplyT(func(v *YdbTable) YdbTablePartitioningSettingsOutput { return v.PartitioningSettings }).(YdbTablePartitioningSettingsOutput)
}

// Table path.
func (o YdbTableOutput) Path() pulumi.StringOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.StringOutput { return v.Path }).(pulumi.StringOutput)
}

// A list of table columns to be used as primary key.
func (o YdbTableOutput) PrimaryKeys() pulumi.StringArrayOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.StringArrayOutput { return v.PrimaryKeys }).(pulumi.StringArrayOutput)
}

// Read replication settings.
func (o YdbTableOutput) ReadReplicasSettings() pulumi.StringOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.StringOutput { return v.ReadReplicasSettings }).(pulumi.StringOutput)
}

// Table storage type. Set to `column` for column-oriented tables. Omit for row-oriented tables (default).
func (o YdbTableOutput) Store() pulumi.StringPtrOutput {
	return o.ApplyT(func(v *YdbTable) pulumi.StringPtrOutput { return v.Store }).(pulumi.StringPtrOutput)
}

// The `TTL` block supports allow you to create a special column type, [TTL column](https://ydb.tech/en/docs/concepts/ttl), whose values determine the time-to-live for rows.
func (o YdbTableOutput) Ttl() YdbTableTtlPtrOutput {
	return o.ApplyT(func(v *YdbTable) YdbTableTtlPtrOutput { return v.Ttl }).(YdbTableTtlPtrOutput)
}

type YdbTableArrayOutput struct{ *pulumi.OutputState }

func (YdbTableArrayOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*[]*YdbTable)(nil)).Elem()
}

func (o YdbTableArrayOutput) ToYdbTableArrayOutput() YdbTableArrayOutput {
	return o
}

func (o YdbTableArrayOutput) ToYdbTableArrayOutputWithContext(ctx context.Context) YdbTableArrayOutput {
	return o
}

func (o YdbTableArrayOutput) Index(i pulumi.IntInput) YdbTableOutput {
	return pulumi.All(o, i).ApplyT(func(vs []interface{}) *YdbTable {
		return vs[0].([]*YdbTable)[vs[1].(int)]
	}).(YdbTableOutput)
}

type YdbTableMapOutput struct{ *pulumi.OutputState }

func (YdbTableMapOutput) ElementType() reflect.Type {
	return reflect.TypeOf((*map[string]*YdbTable)(nil)).Elem()
}

func (o YdbTableMapOutput) ToYdbTableMapOutput() YdbTableMapOutput {
	return o
}

func (o YdbTableMapOutput) ToYdbTableMapOutputWithContext(ctx context.Context) YdbTableMapOutput {
	return o
}

func (o YdbTableMapOutput) MapIndex(k pulumi.StringInput) YdbTableOutput {
	return pulumi.All(o, k).ApplyT(func(vs []interface{}) *YdbTable {
		return vs[0].(map[string]*YdbTable)[vs[1].(string)]
	}).(YdbTableOutput)
}

func init() {
	pulumi.RegisterInputType(reflect.TypeOf((*YdbTableInput)(nil)).Elem(), &YdbTable{})
	pulumi.RegisterInputType(reflect.TypeOf((*YdbTableArrayInput)(nil)).Elem(), YdbTableArray{})
	pulumi.RegisterInputType(reflect.TypeOf((*YdbTableMapInput)(nil)).Elem(), YdbTableMap{})
	pulumi.RegisterOutputType(YdbTableOutput{})
	pulumi.RegisterOutputType(YdbTableArrayOutput{})
	pulumi.RegisterOutputType(YdbTableMapOutput{})
}
